.TH "deprecated" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBp4est_wrap_set_partitioning\fP (p4est_wrap_t *pp, int partition_for_coarsening)\fP" 1c
The function will be removed in the future\&. Flags for partitioning can be set using \fBp4est_wrap_new_params\fP\&. 
.IP "\fBGlobal \fBp8est_wrap_set_partitioning\fP (p8est_wrap_t *pp, int partition_for_coarsening)\fP" 1c
The function will be removed in the future\&. Flags for partitioning can be set using \fBp8est_wrap_new_params\fP\&.
.PP

