.TH "example_simple2" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example_simple2 \- Documentation for selected 2D example programs 
The \fBp4est\fP library comes with various example programs\&.
.PP
They are kept under the subdirectory \fCexample\fP\&. Most have both a 2D and a 3D version\&. When the library is configured \fC--enable-mpi\fP, they can all be run in parallel on any number of MPI ranks, even on small computers\&.
.PP
One first helpful program to try out is called \fCp4est_simple\fP (2D version) and \fCp8est_simple\fP (3D version), both under \fCsimple\fP\&. We showcase some 2D results further below on this page, and we encourage everyone to play with the command line arguments\&.
.SS "The first step example"
Quite some time later, we created a range of step-by-step examples under \fCsteps\fP\&. Let us begin here with the first one that generates a mesh spelling 'Hello, World!': \fBsteps/p4est_step1\&.c\fP\&.
.PP
This program performs refinement on a simple domain based on hardcoded image data\&. As a result, the output VTK file displays the phrase 'Hello World' by the mesh refinement\&.
.PP
Usage may be one of:
.PP
.RS 4
\fCp4est_step1\fP 
.RE
.PP
or with MPI: 
.PP
.RS 4
\fCmpirun -np 3 p4est_step1\fP 
.RE
.PP
.IP "\(bu" 2
No\&. of trees: 1
.IP "\(bu" 2
Maximum refinement level: 6
.PP

.PP
.SS "The historic simple example"
Another illustrative example can be found in \fBsimple/simple2\&.c\fP\&. The refinement pattern is generated by some hardcoded prescriptions based on a quadrant's tree number, refinement level and coordinates\&. Please see the documentation under that link for a full list of configurations\&.
.PP
This program creates/refines & coarsens/balances/partitions one of several available geometries specified on the command line\&. As a result, the output VTK files document all the steps of the mesh manipulation process\&.
.PP
.IP "\(bu" 2
Example: periodic
.PP
Create a connectivity structure for a periodic unit square\&. The left and right faces are identified, and bottom and top opposite\&.
.PP
Usage: 
.PP
.RS 4
\fCp4est_simple periodic 5\fP 
.RE
.PP
or with MPI: 
.PP
.RS 4
\fCmpirun -np 4 p4est_simple periodic 5\fP 
.RE
.PP
.IP "  \(bu" 4
No\&. of trees: 1
.IP "  \(bu" 4
Maximum refinement level: chosen on the command line as 5
.PP

.PP
.PP
.PP
.IP "\(bu" 2
Example: circle
.PP
Create a connectivity structure for an donut-like circle\&. The circle consists of 6 trees connecting each other by their faces\&. The trees are laid out as a hexagon between $[-2, 2]$ in the y direction and $[-\sqrt{3}, \sqrt{3}]$ in the x direction\&. The hexagon has flat sides along the y direction and pointy ends in x\&.
.PP
Usage: 
.PP
.RS 4
\fCp4est_simple circle 5\fP 
.RE
.PP
or with MPI: 
.PP
.RS 4
\fCmpirun -np 4 p4est_simple circle 5\fP 
.RE
.PP
.IP "  \(bu" 4
No\&. of trees: 6
.IP "  \(bu" 4
Maximum refinement level: chosen on the command line as 5
.PP

.PP
.PP
.PP
.IP "\(bu" 2
Example: drop
.PP
Create a connectivity structure for a five-trees geometry with a hole\&. The geometry covers the square $[0, 3]^2$, where the hole is $[1, 2]^2$\&.
.PP
Usage: 
.PP
.RS 4
\fCp4est_simple drop 5\fP 
.RE
.PP
or with MPI: 
.PP
.RS 4
\fCmpirun -np 7 p4est_simple drop 5\fP 
.RE
.PP
.IP "  \(bu" 4
No\&. of trees: 5
.IP "  \(bu" 4
Maximum refinement level: chosen on the command line as 5 
.PP

.IP "\(bu" 2
Example: moebius
.PP
Create a connectivity structure for a five-tree moebius band\&.
.PP
Usage: 
.PP
.RS 4
\fCp4est_simple moebius 5\fP 
.RE
.PP
or with MPI: 
.PP
.RS 4
\fCmpirun -np 4 p4est_simple moebius 5\fP 
.RE
.PP
.IP "  \(bu" 4
No\&. of trees: 5
.IP "  \(bu" 4
Maximum refinement level: chosen on the command line as 5
.PP

.PP
.PP
 
