.TH "p4est_corner_info_t" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_corner_info_t \- Information about the neighbors of a corner\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_connectivity\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBicorner\fP"
.br
.RI "The number of the originating corner\&. "
.ti -1c
.RI "sc_array_t \fBcorner_transforms\fP"
.br
.RI "The array of neighbors of the originating corner\&. "
.in -1c
.SH "Detailed Description"
.PP 
Information about the neighbors of a corner\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
