.TH "p4est_iter_corner_info" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_iter_corner_info \- The information that is available to the user-defined p4est_iter_corner_t callback\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_iterate\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_t\fP * \fBp4est\fP"
.br
.ti -1c
.RI "\fBp4est_ghost_t\fP * \fBghost_layer\fP"
.br
.ti -1c
.RI "int8_t \fBtree_boundary\fP"
.br
.RI "boolean: interior face (0), tree boundary face (true) "
.ti -1c
.RI "sc_array_t \fBsides\fP"
.br
.RI "array of type p4est_iter_corner_side_t type "
.in -1c
.SH "Detailed Description"
.PP 
The information that is available to the user-defined p4est_iter_corner_t callback\&. 

If tree_boundary is false, the corner is on the interior of a tree\&. When tree_boundary is false, sides[0] contains the lowest z-order quadrant that touches the corner\&. When tree_boundary is true, its value is P4EST_CONNECT_FACE/CORNER depending on the location of the corner relative to the tree\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
