.TH "src/p4est_iterate.h" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/p4est_iterate.h \- Iteration over mesh topology via callbacks\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <p4est_ghost\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBp4est_iter_volume_info\fP"
.br
.RI "The information that is available to the user-defined p4est_iter_volume_t callback function\&. "
.ti -1c
.RI "struct \fBp4est_iter_face_side_full\fP"
.br
.RI "Shortcut to access full face information\&. "
.ti -1c
.RI "struct \fBp4est_iter_face_side_hanging\fP"
.br
.RI "Shortcut to access hanging face information\&. "
.ti -1c
.RI "struct \fBp4est_iter_face_side\fP"
.br
.RI "Information about one side of a face in the forest\&. "
.ti -1c
.RI "union \fBp4est_iter_face_side::p4est_iter_face_side_data\fP"
.br
.ti -1c
.RI "struct \fBp4est_iter_face_info\fP"
.br
.RI "The information that is available to the user-defined p4est_iter_face_t callback\&. "
.ti -1c
.RI "struct \fBp4est_iter_corner_side\fP"
.br
.RI "Information about one side of a corner in the forest\&. "
.ti -1c
.RI "struct \fBp4est_iter_corner_info\fP"
.br
.RI "The information that is available to the user-defined p4est_iter_corner_t callback\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBp4est_iter_volume_info\fP \fBp4est_iter_volume_info_t\fP"
.br
.RI "The information that is available to the user-defined p4est_iter_volume_t callback function\&. "
.ti -1c
.RI "typedef void(* \fBp4est_iter_volume_t\fP) (\fBp4est_iter_volume_info_t\fP *info, void *user_data)"
.br
.RI "The prototype for a function that p4est_iterate will execute at every quadrant local to the current process\&. "
.ti -1c
.RI "typedef struct \fBp4est_iter_face_side_full\fP \fBp4est_iter_face_side_full_t\fP"
.br
.RI "Shortcut to access full face information\&. "
.ti -1c
.RI "typedef struct \fBp4est_iter_face_side_hanging\fP \fBp4est_iter_face_side_hanging_t\fP"
.br
.RI "Shortcut to access hanging face information\&. "
.ti -1c
.RI "typedef struct \fBp4est_iter_face_side\fP \fBp4est_iter_face_side_t\fP"
.br
.RI "Information about one side of a face in the forest\&. "
.ti -1c
.RI "typedef struct \fBp4est_iter_face_info\fP \fBp4est_iter_face_info_t\fP"
.br
.RI "The information that is available to the user-defined p4est_iter_face_t callback\&. "
.ti -1c
.RI "typedef void(* \fBp4est_iter_face_t\fP) (\fBp4est_iter_face_info_t\fP *info, void *user_data)"
.br
.RI "The prototype for a function that p4est_iterate will execute wherever two quadrants share a face: the face can be a 2:1 hanging face, it does not have to be conformal\&. "
.ti -1c
.RI "typedef struct \fBp4est_iter_corner_side\fP \fBp4est_iter_corner_side_t\fP"
.br
.RI "Information about one side of a corner in the forest\&. "
.ti -1c
.RI "typedef struct \fBp4est_iter_corner_info\fP \fBp4est_iter_corner_info_t\fP"
.br
.RI "The information that is available to the user-defined p4est_iter_corner_t callback\&. "
.ti -1c
.RI "typedef void(* \fBp4est_iter_corner_t\fP) (\fBp4est_iter_corner_info_t\fP *info, void *user_data)"
.br
.RI "The prototype for a function that p4est_iterate will execute wherever quadrants meet at a conformal corner\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBp4est_iterate\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_ghost_t\fP *ghost_layer, void *user_data, \fBp4est_iter_volume_t\fP iter_volume, \fBp4est_iter_face_t\fP iter_face, \fBp4est_iter_corner_t\fP iter_corner)"
.br
.RI "Execute user supplied callbacks at every volume, face, and corner in the local forest\&. "
.in -1c
.SH "Detailed Description"
.PP 
Iteration over mesh topology via callbacks\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBp4est_iter_corner_info\fP \fBp4est_iter_corner_info_t\fP"

.PP
The information that is available to the user-defined p4est_iter_corner_t callback\&. If tree_boundary is false, the corner is on the interior of a tree\&. When tree_boundary is false, sides[0] contains the lowest z-order quadrant that touches the corner\&. When tree_boundary is true, its value is P4EST_CONNECT_FACE/CORNER depending on the location of the corner relative to the tree\&. 
.SS "typedef struct \fBp4est_iter_corner_side\fP \fBp4est_iter_corner_side_t\fP"

.PP
Information about one side of a corner in the forest\&. If a \fIquad\fP is local (\fIis_ghost\fP is false), then its \fIquadid\fP indexes the tree's quadrant array; otherwise, it indexes the ghosts array\&. If a quadrant should be present, but it is not included in the ghost layer, then quad = NULL, is_ghost is true, and quadid = -1\&.
.PP
the \fIfaces\fP field provides some additional information about the local topology: if side[i]->faces[j] == side[k]->faces[l], this indicates that there is a common face between these two sides of the corner\&. 
.SS "typedef void(* p4est_iter_corner_t) (\fBp4est_iter_corner_info_t\fP *info, void *user_data)"

.PP
The prototype for a function that p4est_iterate will execute wherever quadrants meet at a conformal corner\&. i\&.e\&. the callback will not execute on a hanging corner\&.
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP information about a quadrant provided to the user 
.br
\fIuser_data\fP the user context passed to \fBp4est_iterate()\fP
.RE
.PP
\fBNote\fP
.RS 4
the forest does not need to be corner balanced for \fBp4est_iterate()\fP to correctly execute a callback function at corners, only face balanced (see \fBp4est_balance()\fP)\&. 
.RE
.PP

.SS "typedef struct \fBp4est_iter_face_info\fP \fBp4est_iter_face_info_t\fP"

.PP
The information that is available to the user-defined p4est_iter_face_t callback\&. The orientation is 0 if the face is within one tree; otherwise, it is the same as the orientation value between the two trees given in the connectivity\&. If the face is on the outside boundary of the forest, then there is only one side\&. If tree_boundary is false, the face is on the interior of a tree\&. When tree_boundary is false, sides[0] contains the lowest z-order quadrant that touches the face\&. When tree_boundary is true, its value is P4EST_CONNECT_FACE\&. 
.SS "typedef struct \fBp4est_iter_face_side\fP \fBp4est_iter_face_side_t\fP"

.PP
Information about one side of a face in the forest\&. If a \fIquad\fP is local (\fIis_ghost\fP is false), then its \fIquadid\fP indexes the tree's quadrant array; otherwise, it indexes the ghosts array\&. If the face is hanging, then the quadrants are listed in z-order\&. If a quadrant should be present, but it is not included in the ghost layer, then quad = NULL, is_ghost is true, and quadid = -1\&. 
.SS "typedef void(* p4est_iter_face_t) (\fBp4est_iter_face_info_t\fP *info, void *user_data)"

.PP
The prototype for a function that p4est_iterate will execute wherever two quadrants share a face: the face can be a 2:1 hanging face, it does not have to be conformal\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP information about a quadrant provided to the user 
.br
\fIuser_data\fP the user context passed to \fBp4est_iterate()\fP
.RE
.PP
\fBNote\fP
.RS 4
the forest must be face balanced for \fBp4est_iterate()\fP to execute a callback function on faces (see \fBp4est_balance()\fP)\&. 
.RE
.PP

.SS "typedef struct \fBp4est_iter_volume_info\fP \fBp4est_iter_volume_info_t\fP"

.PP
The information that is available to the user-defined p4est_iter_volume_t callback function\&. \fItreeid\fP gives the index in \fIp4est->trees\fP of the tree to which \fIquad\fP belongs\&. \fIquadid\fP gives the index of \fIquad\fP within \fItree's\fP quadrants array\&. 
.SS "typedef void(* p4est_iter_volume_t) (\fBp4est_iter_volume_info_t\fP *info, void *user_data)"

.PP
The prototype for a function that p4est_iterate will execute at every quadrant local to the current process\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfo\fP information about a quadrant provided to the user 
.br
\fIuser_data\fP the user context passed to \fBp4est_iterate()\fP 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBuserdata/userdata_run2\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void p4est_iterate (\fBp4est_t\fP * p4est, \fBp4est_ghost_t\fP * ghost_layer, void * user_data, \fBp4est_iter_volume_t\fP iter_volume, \fBp4est_iter_face_t\fP iter_face, \fBp4est_iter_corner_t\fP iter_corner)"

.PP
Execute user supplied callbacks at every volume, face, and corner in the local forest\&. p4est_iterate executes the user-supplied callback functions at every volume, face, and corner in the local forest\&. The ghost_layer may be NULL\&. The \fIuser_data\fP pointer is not touched by p4est_iterate, but is passed to each of the callbacks\&. Any of the callbacks may be NULL\&. The callback functions are interspersed with each other, i\&.e\&. some face callbacks will occur between volume callbacks, and some corner callbacks will occur between face callbacks:
.PP
1) volume callbacks occur in the sorted Morton-index order\&. 2) a face callback is not executed until after the volume callbacks have been executed for the quadrants that share it\&. 3) a corner callback is not executed until the face callbacks have been executed for all faces that touch the corner\&. 4) it is not always the case that every face callback for a given quadrant is executed before any of the corner callbacks\&. 5) callbacks are not executed at faces or corners that only involve ghost quadrants, i\&.e\&. that are not adjacent in the local section of the forest\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP the forest 
.br
\fIghost_layer\fP optional: when not given, callbacks at the boundaries of the local partition cannot provide quadrant data about ghost quadrants: missing (p4est_quadrant_t *) pointers are set to NULL, missing indices are set to -1\&. 
.br
\fIuser_data\fP optional context to supply to each callback 
.br
\fIiter_volume\fP callback function for every quadrant's interior 
.br
\fIiter_face\fP callback function for every face between quadrants 
.br
\fIiter_corner\fP callback function for every corner between quadrants 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsteps/p4est_step3\&.c\fP, and \fBuserdata/userdata_run2\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
