.TH "p4est_lnodes_buffer" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_lnodes_buffer \- p4est_lnodes_buffer_t handles the communication of data associated with nodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_lnodes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_array_t * \fBrequests\fP"
.br
.ti -1c
.RI "sc_array_t * \fBsend_buffers\fP"
.br
.ti -1c
.RI "sc_array_t * \fBrecv_buffers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
p4est_lnodes_buffer_t handles the communication of data associated with nodes\&. 

\fIsend_buffers\fP is an array of arrays: one buffer for each process to which the current process sends node-data\&. It should not be altered between a shared_*_begin and a shared_*_end call\&.
.PP
\fIrecv_buffers\fP is an array of arrays that is used in lnodes_share_all_*\&. \fIrecv_buffers\fP[j] corresponds with lnodes->sharers[j]: it is the same length as \fIlnodes->sharers\fP[j]->shared_nodes\&. At the completion of lnodes_share_all or lnodes_share_all_end, recv_buffers[j] contains the node-data from the process lnodes->sharers[j]->rank (unless j is the current rank, in which case recv_buffers[j] is empty)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
