.TH "src/p6est_ghost.h" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/p6est_ghost.h \- passing columns of layers and data to neighboring processes  

.SH SYNOPSIS
.br
.PP
\fC#include <p6est\&.h>\fP
.br
\fC#include <p4est_ghost\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBp6est_ghost\fP"
.br
.RI "columns of layers that neighbor the local domain "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBp6est_ghost\fP \fBp6est_ghost_t\fP"
.br
.RI "columns of layers that neighbor the local domain "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBp6est_ghost_memory_used\fP (\fBp6est_ghost_t\fP *ghost)"
.br
.RI "Calculate the memory usage of the ghost layer\&. "
.ti -1c
.RI "\fBp6est_ghost_t\fP * \fBp6est_ghost_new\fP (\fBp6est_t\fP *\fBp4est\fP, \fBp4est_connect_type_t\fP btype)"
.br
.RI "Builds the ghost layer\&. "
.ti -1c
.RI "void \fBp6est_ghost_expand\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp6est_ghost_t\fP *ghost)"
.br
.RI "Expand the size of the ghost layer and mirrors by one additional layer of adjacency\&. "
.ti -1c
.RI "void \fBp6est_ghost_destroy\fP (\fBp6est_ghost_t\fP *ghost)"
.br
.RI "Frees all memory used for the ghost layer\&. "
.ti -1c
.RI "ssize_t \fBp6est_ghost_bsearch\fP (\fBp6est_ghost_t\fP *ghost, int which_proc, \fBp4est_topidx_t\fP which_tree, const \fBp4est_quadrant_t\fP *column, const \fBp2est_quadrant_t\fP *layer)"
.br
.RI "Conduct binary search for exact match on a range of the ghost layer\&. "
.ti -1c
.RI "ssize_t \fBp6est_ghost_contains\fP (\fBp6est_ghost_t\fP *ghost, int which_proc, \fBp4est_topidx_t\fP which_tree, const \fBp4est_quadrant_t\fP *column, const \fBp2est_quadrant_t\fP *layer)"
.br
.RI "Conduct binary search for ancestor on range of the ghost layer\&. "
.ti -1c
.RI "int \fBp6est_layer_exists\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp6est_ghost_t\fP *ghost, \fBp4est_topidx_t\fP treeid, const \fBp4est_quadrant_t\fP *column, const \fBp2est_quadrant_t\fP *layer, sc_array_t *exists_arr, sc_array_t *rproc_arr, sc_array_t *rquad_arr)"
.br
.RI "Checks if layer exists in the local forest or the ghost layer\&. "
.ti -1c
.RI "int \fBp6est_is_balanced\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp8est_connect_type_t\fP btype)"
.br
.RI "Check a forest to see if it is balanced\&. "
.ti -1c
.RI "unsigned \fBp6est_ghost_checksum\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp6est_ghost_t\fP *ghost)"
.br
.RI "Compute the parallel checksum of a ghost layer\&. "
.in -1c
.SH "Detailed Description"
.PP 
passing columns of layers and data to neighboring processes 


.SH "Function Documentation"
.PP 
.SS "ssize_t p6est_ghost_bsearch (\fBp6est_ghost_t\fP * ghost, int which_proc, \fBp4est_topidx_t\fP which_tree, const \fBp4est_quadrant_t\fP * column, const \fBp2est_quadrant_t\fP * layer)"

.PP
Conduct binary search for exact match on a range of the ghost layer\&. 
.PP
\fBParameters\fP
.RS 4
\fIghost\fP The ghost layer\&. 
.br
\fIwhich_proc\fP The owner of the searched quadrant\&. Can be -1\&. 
.br
\fIwhich_tree\fP The tree of the searched quadrant\&. Can be -1\&. 
.br
\fIcolumn\fP The column that is being searched for\&. 
.br
\fIlayer\fP The layer that is being searched for\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Offset in the ghost layer, or -1 if not found\&. 
.RE
.PP

.SS "unsigned p6est_ghost_checksum (\fBp6est_t\fP * p6est, \fBp6est_ghost_t\fP * ghost)"

.PP
Compute the parallel checksum of a ghost layer\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The MPI information of this \fBp4est\fP will be used\&. 
.br
\fIghost\fP A ghost layer obtained from the \fBp4est\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Parallel checksum on rank 0, 0 otherwise\&. 
.RE
.PP

.SS "ssize_t p6est_ghost_contains (\fBp6est_ghost_t\fP * ghost, int which_proc, \fBp4est_topidx_t\fP which_tree, const \fBp4est_quadrant_t\fP * column, const \fBp2est_quadrant_t\fP * layer)"

.PP
Conduct binary search for ancestor on range of the ghost layer\&. 
.PP
\fBParameters\fP
.RS 4
\fIghost\fP The ghost layer\&. 
.br
\fIwhich_proc\fP The owner of the searched quadrant\&. Can be -1\&. 
.br
\fIwhich_tree\fP The tree of the searched quadrant\&. Can be -1\&. 
.br
\fIcolumn\fP The column that is being searched for\&. 
.br
\fIlayer\fP The layer that is being searched for\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Offset in the ghost layer, or -1 if not found\&. 
.RE
.PP

.SS "void p6est_ghost_expand (\fBp6est_t\fP * p6est, \fBp6est_ghost_t\fP * ghost)"

.PP
Expand the size of the ghost layer and mirrors by one additional layer of adjacency\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP The forest from which the ghost layer was generated\&. 
.br
\fIghost\fP The ghost layer to be expanded\&. 
.RE
.PP

.SS "size_t p6est_ghost_memory_used (\fBp6est_ghost_t\fP * ghost)"

.PP
Calculate the memory usage of the ghost layer\&. 
.PP
\fBParameters\fP
.RS 4
\fIghost\fP Ghost layer structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Memory used in bytes\&. 
.RE
.PP

.SS "\fBp6est_ghost_t\fP* p6est_ghost_new (\fBp6est_t\fP * p4est, \fBp4est_connect_type_t\fP btype)"

.PP
Builds the ghost layer\&. This will gather the quadrants from each neighboring proc to build one layer of face and corner based ghost elements around the ones they own\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The forest for which the ghost layer will be generated\&. 
.br
\fIbtype\fP Which ghosts to include (across face, corner or default, full)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A fully initialized ghost layer\&. 
.RE
.PP

.SS "int p6est_is_balanced (\fBp6est_t\fP * p6est, \fBp8est_connect_type_t\fP btype)"

.PP
Check a forest to see if it is balanced\&. This function builds the ghost layer and discards it when done\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The \fBp4est\fP to be tested\&. 
.br
\fIbtype\fP Balance type (face, corner or default, full)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns true if balanced, false otherwise\&. 
.RE
.PP

.SS "int p6est_layer_exists (\fBp6est_t\fP * p6est, \fBp6est_ghost_t\fP * ghost, \fBp4est_topidx_t\fP treeid, const \fBp4est_quadrant_t\fP * column, const \fBp2est_quadrant_t\fP * layer, sc_array_t * exists_arr, sc_array_t * rproc_arr, sc_array_t * rquad_arr)"

.PP
Checks if layer exists in the local forest or the ghost layer\&. For quadrants across tree corners it checks if the quadrant exists in any of the corner neighbors, thus it can execute multiple queries\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The forest in which to search for \fIq\fP 
.br
\fIghost\fP The ghost layer in which to search for \fIq\fP 
.br
\fItreeid\fP The tree to which \fIq\fP belongs (can be extended)\&. 
.br
\fIcolumn\fP The column that is being searched for\&. 
.br
\fIlayer\fP The layer that is being searched for\&. 
.br
\fIexists_arr\fP Must exist and be of of elem_size = sizeof (int) for inter-tree corner cases\&. Is resized by this function to one entry for each corner search and set to true/false depending on its existence in the local forest or ghost_layer\&. 
.br
\fIrproc_arr\fP If not NULL is filled with one rank per query\&. 
.br
\fIrquad_arr\fP If not NULL is filled with one quadrant per query\&. Its piggy3 member is defined as well\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the quadrant exists in the local forest or in the ghost_layer, and false if doesn't exist in either\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
