.TH "src/p6est.h" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/p6est.h \- A hybrid 2D+1D AMR extension\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <p4est\&.h>\fP
.br
\fC#include <p8est_connectivity\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBp6est_connectivity\fP"
.br
.RI "This structure holds the 2D+1D inter-tree connectivity information\&. "
.ti -1c
.RI "struct \fBp2est_quadrant\fP"
.br
.RI "A 1D quadrant datatype: this is used to encode a 'layer' of a column in the 2D+1D AMR scheme\&. "
.ti -1c
.RI "union \fBp2est_quadrant::p6est_quadrant_data\fP"
.br
.ti -1c
.RI "struct \fBp6est\fP"
.br
.RI "The \fBp6est\fP forest datatype\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBP2EST_QUADRANT_INIT\fP(q)     ((void) memset ((q), \-1, sizeof (\fBp2est_quadrant_t\fP)))"
.br
.RI "set statically allocated quadrant to defined values "
.ti -1c
.RI "#define \fBP6EST_COLUMN_GET_RANGE\fP(q,  f,  l)"
.br
.ti -1c
.RI "#define \fBP6EST_COLUMN_SET_RANGE\fP(q,  f,  l)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBp6est_connectivity\fP \fBp6est_connectivity_t\fP"
.br
.RI "This structure holds the 2D+1D inter-tree connectivity information\&. "
.ti -1c
.RI "typedef struct \fBp2est_quadrant\fP \fBp2est_quadrant_t\fP"
.br
.RI "A 1D quadrant datatype: this is used to encode a 'layer' of a column in the 2D+1D AMR scheme\&. "
.ti -1c
.RI "typedef struct \fBp6est\fP \fBp6est_t\fP"
.br
.RI "The \fBp6est\fP forest datatype\&. "
.ti -1c
.RI "typedef void(* \fBp6est_init_t\fP) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layer)"
.br
.RI "Callback function prototype to initialize the layers's user data\&. "
.ti -1c
.RI "typedef void(* \fBp6est_replace_t\fP) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, int num_outcolumns, int num_outlayers, \fBp4est_quadrant_t\fP *outcolumns[], \fBp2est_quadrant_t\fP *outlayers[], int num_incolumns, int num_inlayers, \fBp4est_quadrant_t\fP *incolumns[], \fBp2est_quadrant_t\fP *inlayers[])"
.br
.RI "Callback function prototype to transfer information from outgoing layers to incoming layers\&. "
.ti -1c
.RI "typedef int(* \fBp6est_refine_column_t\fP) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column)"
.br
.RI "Callback function prototype to decide whether to horizontally refine a column, i\&.e\&., horizontally refine all of the layers in the column\&. "
.ti -1c
.RI "typedef int(* \fBp6est_refine_layer_t\fP) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layer)"
.br
.RI "Callback function prototype to decide whether to vertically refine a layer\&. "
.ti -1c
.RI "typedef int(* \fBp6est_coarsen_column_t\fP) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *columns[])"
.br
.RI "Callback function prototype to decide for horizontal coarsening\&. "
.ti -1c
.RI "typedef int(* \fBp6est_coarsen_layer_t\fP) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layers[])"
.br
.RI "Callback function prototype to decide for vertical coarsening\&. "
.ti -1c
.RI "typedef int(* \fBp6est_weight_t\fP) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layer)"
.br
.RI "Callback function prototype to calculate weights for partitioning\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBp6est_comm_tag_t\fP { \fBP6EST_COMM_PARTITION\fP = 1, \fBP6EST_COMM_GHOST\fP, \fBP6EST_COMM_BALANCE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBp6est_connectivity_t\fP * \fBp6est_connectivity_new\fP (\fBp4est_connectivity_t\fP *conn4, double *top_vertices, double height[3])"
.br
.RI "Create a p6est_connectivity_t from a p4est_connectivity_t\&. "
.ti -1c
.RI "void \fBp6est_connectivity_destroy\fP (\fBp6est_connectivity_t\fP *conn)"
.br
.RI "Destroy a \fBp6est_connectivity\fP structure\&. "
.ti -1c
.RI "void \fBp6est_tree_get_vertices\fP (\fBp6est_connectivity_t\fP *conn, \fBp4est_topidx_t\fP which_tree, double vertices[24])"
.br
.RI "Get the vertices of the corners of a tree\&. "
.ti -1c
.RI "void \fBp6est_qcoord_to_vertex\fP (\fBp6est_connectivity_t\fP *connectivity, \fBp4est_topidx_t\fP treeid, \fBp4est_qcoord_t\fP x, \fBp4est_qcoord_t\fP y, \fBp4est_qcoord_t\fP z, double vxyz[3])"
.br
.RI "Transform a quadrant coordinate into the space spanned by tree vertices\&. "
.ti -1c
.RI "\fBp6est_t\fP * \fBp6est_new\fP (sc_MPI_Comm mpicomm, \fBp6est_connectivity_t\fP *connectivity, size_t data_size, \fBp6est_init_t\fP init_fn, void *user_pointer)"
.br
.RI "Create a new forest\&. "
.ti -1c
.RI "\fBp6est_t\fP * \fBp6est_new_from_p4est\fP (\fBp4est_t\fP *\fBp4est\fP, double *top_vertices, double height[3], int min_zlevel, size_t data_size, \fBp6est_init_t\fP init_fn, void *user_pointer)"
.br
.RI "Create a new forest from an already created \fBp4est\fP that represents columns\&. "
.ti -1c
.RI "void \fBp6est_destroy\fP (\fBp6est_t\fP *\fBp6est\fP)"
.br
.RI "Destroy a \fBp6est\fP\&. "
.ti -1c
.RI "\fBp6est_t\fP * \fBp6est_copy\fP (\fBp6est_t\fP *input, int copy_data)"
.br
.RI "Make a deep copy of a \fBp6est\fP\&. "
.ti -1c
.RI "void \fBp6est_reset_data\fP (\fBp6est_t\fP *\fBp6est\fP, size_t data_size, \fBp6est_init_t\fP init_fn, void *user_pointer)"
.br
.RI "Reset user pointer and element data\&. "
.ti -1c
.RI "void \fBp6est_refine_columns\fP (\fBp6est_t\fP *\fBp6est\fP, int refine_recursive, \fBp6est_refine_column_t\fP refine_fn, \fBp6est_init_t\fP init_fn)"
.br
.RI "Refine the columns of a sheet\&. "
.ti -1c
.RI "void \fBp6est_refine_layers\fP (\fBp6est_t\fP *\fBp6est\fP, int refine_recursive, \fBp6est_refine_layer_t\fP refine_fn, \fBp6est_init_t\fP init_fn)"
.br
.RI "Refine the layers within the columns of a sheet\&. "
.ti -1c
.RI "void \fBp6est_coarsen_columns\fP (\fBp6est_t\fP *\fBp6est\fP, int coarsen_recursive, \fBp6est_coarsen_column_t\fP coarsen_fn, \fBp6est_init_t\fP init_fn)"
.br
.RI "Coarsen the columns of a sheet\&. "
.ti -1c
.RI "void \fBp6est_coarsen_layers\fP (\fBp6est_t\fP *\fBp6est\fP, int coarsen_recursive, \fBp6est_coarsen_layer_t\fP coarsen_fn, \fBp6est_init_t\fP init_fn)"
.br
.RI "Coarsen the layers of a sheet\&. "
.ti -1c
.RI "void \fBp6est_balance\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp8est_connect_type_t\fP btype, \fBp6est_init_t\fP init_fn)"
.br
.RI "Balance a forest\&. "
.ti -1c
.RI "\fBp4est_gloidx_t\fP \fBp6est_partition\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp6est_weight_t\fP weight_fn)"
.br
.RI "Equally partition the forest\&. "
.ti -1c
.RI "void \fBp6est_partition_correct\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_locidx_t\fP *num_layers_in_proc)"
.br
.ti -1c
.RI "void \fBp6est_partition_to_p4est_partition\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_locidx_t\fP *num_layers_in_proc, \fBp4est_locidx_t\fP *num_columns_in_proc)"
.br
.ti -1c
.RI "void \fBp4est_partition_to_p6est_partition\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_locidx_t\fP *num_columns_in_proc, \fBp4est_locidx_t\fP *num_layers_in_proc)"
.br
.ti -1c
.RI "\fBp4est_gloidx_t\fP \fBp6est_partition_for_coarsening\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_locidx_t\fP *num_layers_in_proc)"
.br
.ti -1c
.RI "\fBp4est_gloidx_t\fP \fBp6est_partition_given\fP (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_locidx_t\fP *num_layers_in_proc)"
.br
.ti -1c
.RI "unsigned \fBp6est_checksum\fP (\fBp6est_t\fP *\fBp6est\fP)"
.br
.RI "Compute the checksum for a forest\&. "
.ti -1c
.RI "void \fBp6est_save\fP (const char *filename, \fBp6est_t\fP *\fBp6est\fP, int save_data)"
.br
.RI "Save the complete connectivity/p6est data to disk\&. "
.ti -1c
.RI "\fBp6est_t\fP * \fBp6est_load\fP (const char *filename, sc_MPI_Comm mpicomm, size_t data_size, int load_data, void *user_pointer, \fBp6est_connectivity_t\fP **connectivity)"
.br
.RI "Load the complete connectivity/p6est structure from disk\&. "
.ti -1c
.RI "void \fBp6est_compress_columns\fP (\fBp6est_t\fP *\fBp6est\fP)"
.br
.ti -1c
.RI "void \fBp6est_update_offsets\fP (\fBp6est_t\fP *\fBp6est\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBP2EST_DATA_UNINITIALIZED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A hybrid 2D+1D AMR extension\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define P6EST_COLUMN_GET_RANGE(q, f, l)"
\fBValue:\fP
.PP
.nf
  do {                                               \
    *(f) = (size_t) (q)->p\&.piggy3\&.local_num;         \
    *(l) = *(f) + (size_t) (q)->p\&.piggy3\&.which_tree; \
  } while (0);
.fi
.SS "#define P6EST_COLUMN_SET_RANGE(q, f, l)"
\fBValue:\fP
.PP
.nf
  do {                                                       \
    (q)->p\&.piggy3\&.local_num = (p4est_locidx_t) (f);          \
    (q)->p\&.piggy3\&.which_tree = (p4est_topidx_t) ((l) - (f)); \
  } while (0);
.fi
.SH "Typedef Documentation"
.PP 
.SS "typedef int(* p6est_coarsen_column_t) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *columns[])"

.PP
Callback function prototype to decide for horizontal coarsening\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolumns\fP Pointers to 4 sibling columns\&. 
.RE
.PP
\fBReturns\fP
.RS 4
nonzero if the columns shall be replaced with their parent\&. 
.RE
.PP

.SS "typedef int(* p6est_coarsen_layer_t) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layers[])"

.PP
Callback function prototype to decide for vertical coarsening\&. 
.PP
\fBParameters\fP
.RS 4
\fIlayers\fP Pointers to 2 vertical sibling layers\&. 
.RE
.PP
\fBReturns\fP
.RS 4
nonzero if the layers shall be replaced with their parent\&. 
.RE
.PP

.SS "typedef struct \fBp6est_connectivity\fP \fBp6est_connectivity_t\fP"

.PP
This structure holds the 2D+1D inter-tree connectivity information\&. It is essentially a wrapper of the 2D p4est_connecitivity_t datatype, with some additional information about how the third dimension is embedded\&. 
.SS "typedef void(* p6est_init_t) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layer)"

.PP
Callback function prototype to initialize the layers's user data\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP the forest 
.br
\fIwhich_tree\fP the tree in the forest 
.br
\fIcolumn\fP the column in the tree in the forest 
.br
\fIlayer\fP the layer in the column in the tree in the forest, whose \fIuser_data\fP is to be initialized 
.RE
.PP

.SS "typedef int(* p6est_refine_column_t) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column)"

.PP
Callback function prototype to decide whether to horizontally refine a column, i\&.e\&., horizontally refine all of the layers in the column\&. 
.PP
\fBReturns\fP
.RS 4
nonzero if the layer shall be refined\&. 
.RE
.PP

.SS "typedef int(* p6est_refine_layer_t) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layer)"

.PP
Callback function prototype to decide whether to vertically refine a layer\&. 
.PP
\fBReturns\fP
.RS 4
nonzero if the layer shall be refined\&. 
.RE
.PP

.SS "typedef void(* p6est_replace_t) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, int num_outcolumns, int num_outlayers, \fBp4est_quadrant_t\fP *outcolumns[], \fBp2est_quadrant_t\fP *outlayers[], int num_incolumns, int num_inlayers, \fBp4est_quadrant_t\fP *incolumns[], \fBp2est_quadrant_t\fP *inlayers[])"

.PP
Callback function prototype to transfer information from outgoing layers to incoming layers\&. This is used by extended routines when the layers of an existing, valid \fBp6est\fP are changed\&. The callback allows the user to make changes to newly initialized layers before the layers that they replace are destroyed\&.
.PP
\fBParameters\fP
.RS 4
\fInum_outcolumns\fP The number of columns that contain the outgoing layers: will be either 1 or 4\&. 
.br
\fInum_outlayers\fP The number of outgoing layers: will be either 1 (a single layer is being refined), 2 (two layers are being vertically coarsened), or 4 (four layers are being horizontally coarsened)\&. 
.br
\fIoutcolumns\fP The columns of the outgoing layers 
.br
\fIoutlayers\fP The outgoing layers: after the callback, the user_data, if \fIp6est->data_size\fP is nonzero, will be destroyed\&. 
.br
\fInum_incolumns\fP The number of columns that contain the outgoing layers: will be either 1 or 4\&. 
.br
\fInum_inlayers\fP The number of incoming layers: will be either 1 (coarsening), 2 (vertical refinement), or 4 (horizontal refinement) 
.br
\fIincolumns\fP The columns of the incoming layers 
.br
\fIinlayers\fP The incoming layers: prior to the callback, the user_data, if \fIp6est->data_size\fP is nonzero, is allocated, and the p6est_init_t callback, if it has been provided, will be called\&. 
.RE
.PP

.SS "typedef int(* p6est_weight_t) (\fBp6est_t\fP *\fBp6est\fP, \fBp4est_topidx_t\fP which_tree, \fBp4est_quadrant_t\fP *column, \fBp2est_quadrant_t\fP *layer)"

.PP
Callback function prototype to calculate weights for partitioning\&. 
.PP
\fBReturns\fP
.RS 4
a 32bit integer >= 0 as the quadrant weight\&. 
.RE
.PP
\fBNote\fP
.RS 4
Global sum of weights must fit into a 64bit integer\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void p6est_balance (\fBp6est_t\fP * p6est, \fBp8est_connect_type_t\fP btype, \fBp6est_init_t\fP init_fn)"

.PP
Balance a forest\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP The \fBp6est\fP to be worked on\&. 
.br
\fIbtype\fP Balance type (face, corner or default, full)\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.RE
.PP

.SS "unsigned p6est_checksum (\fBp6est_t\fP * p6est)"

.PP
Compute the checksum for a forest\&. Based on quadrant arrays only\&. It is independent of partition and mpisize\&. 
.PP
\fBReturns\fP
.RS 4
Returns the checksum on processor 0 only\&. 0 on other processors\&. 
.RE
.PP

.SS "void p6est_coarsen_columns (\fBp6est_t\fP * p6est, int coarsen_recursive, \fBp6est_coarsen_column_t\fP coarsen_fn, \fBp6est_init_t\fP init_fn)"

.PP
Coarsen the columns of a sheet\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP The forest is changed in place\&. 
.br
\fIcoarsen_recursive\fP Boolean to decide on recursive coarsening\&. 
.br
\fIcoarsen_fn\fP Callback function that returns true if a family of columns shall be coarsened 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.RE
.PP

.SS "void p6est_coarsen_layers (\fBp6est_t\fP * p6est, int coarsen_recursive, \fBp6est_coarsen_layer_t\fP coarsen_fn, \fBp6est_init_t\fP init_fn)"

.PP
Coarsen the layers of a sheet\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP The forest is changed in place\&. 
.br
\fIcoarsen_recursive\fP Boolean to decide on recursive coarsening\&. 
.br
\fIcoarsen_fn\fP Callback function that returns true if a family of layers shall be coarsened 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.RE
.PP

.SS "\fBp6est_connectivity_t\fP* p6est_connectivity_new (\fBp4est_connectivity_t\fP * conn4, double * top_vertices, double height[3])"

.PP
Create a p6est_connectivity_t from a p4est_connectivity_t\&. All fields are copied, so all inputs can be safey destroyed\&.
.PP
\fBParameters\fP
.RS 4
\fIconn4\fP the 2D connectivity 
.br
\fItop_vertices\fP if NULL, then the sheet has a uniform vertical profile; otherwise, \fItop_vertices\fP gives the vertices of the top of the sheet; should be the same size as \fIconn4->tree_to_vertex\fP 
.br
\fIheight\fP if \fItop_vertices\fP == NULL, then this gives the offset from the bottom of the sheet to the top\&.
.RE
.PP
\fBReturns\fP
.RS 4
the 2D+1D connectivity information\&. 
.RE
.PP

.SS "\fBp6est_t\fP* p6est_copy (\fBp6est_t\fP * input, int copy_data)"

.PP
Make a deep copy of a \fBp6est\fP\&. The connectivity is not duplicated\&. Copying of quadrant user data is optional\&. If old and new data sizes are 0, the user_data field is copied regardless\&.
.PP
\fBParameters\fP
.RS 4
\fIcopy_data\fP If true, data are copied\&. If false, data_size is set to 0\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a valid \fBp6est\fP that does not depend on the input\&. 
.RE
.PP

.SS "void p6est_destroy (\fBp6est_t\fP * p6est)"

.PP
Destroy a \fBp6est\fP\&. 
.PP
\fBNote\fP
.RS 4
The connectivity structure is not destroyed with the \fBp6est\fP\&. 
.RE
.PP

.SS "\fBp6est_t\fP* p6est_load (const char * filename, sc_MPI_Comm mpicomm, size_t data_size, int load_data, void * user_pointer, \fBp6est_connectivity_t\fP ** connectivity)"

.PP
Load the complete connectivity/p6est structure from disk\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file to read\&. 
.br
\fImpicomm\fP A valid MPI communicator\&. 
.br
\fIdata_size\fP Size of data for each quadrant which can be zero\&. Then user_data_pool is set to NULL\&. If data_size is zero, load_data is ignored\&. 
.br
\fIload_data\fP If true, the element data is loaded\&. This is only permitted if the saved data size matches\&. If false, the stored data size is ignored\&. 
.br
\fIuser_pointer\fP Assign to the user_pointer member of the \fBp6est\fP before init_fn is called the first time\&. 
.br
\fIconnectivity\fP Connectivity must be destroyed separately\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a valid forest structure\&. A pointer to a valid connectivity structure is returned through the last argument\&. 
.RE
.PP
\fBNote\fP
.RS 4
Aborts on file errors or invalid file contents\&. 
.RE
.PP

.SS "\fBp6est_t\fP* p6est_new (sc_MPI_Comm mpicomm, \fBp6est_connectivity_t\fP * connectivity, size_t data_size, \fBp6est_init_t\fP init_fn, void * user_pointer)"

.PP
Create a new forest\&. The new forest consists of equi-partitioned root quadrants\&. When there are more processors than trees, some processors are empty\&.
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP A valid MPI communicator\&. 
.br
\fIconnectivity\fP This is the connectivity information that the forest is built with\&. Note the \fBp6est\fP does not take ownership of the memory\&. 
.br
\fIdata_size\fP This is the size of data for each quadrant which can be zero\&. Then user_data_pool is set to NULL\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.br
\fIuser_pointer\fP Assign to the user_pointer member of the \fBp6est\fP before init_fn is called the first time\&.
.RE
.PP
\fBReturns\fP
.RS 4
This returns a valid forest\&.
.RE
.PP
\fBNote\fP
.RS 4
The connectivity structure must not be destroyed during the lifetime of this forest\&. 
.RE
.PP

.SS "\fBp6est_t\fP* p6est_new_from_p4est (\fBp4est_t\fP * p4est, double * top_vertices, double height[3], int min_zlevel, size_t data_size, \fBp6est_init_t\fP init_fn, void * user_pointer)"

.PP
Create a new forest from an already created \fBp4est\fP that represents columns\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP A valid \fBp4est\fP\&. A deep copy will be created, so this can be destroyed without affectin the new \fBp6est\fP object\&. 
.br
\fItop_vertices\fP the same as in p6est_conectivity_new() 
.br
\fIheight\fP the same as in p6est_conectivity_new() 
.br
\fImin_zlevel\fP the same as in \fBp6est_new()\fP 
.br
\fIdata_size\fP the same as in \fBp6est_new()\fP 
.br
\fIinit_fn\fP the same as in \fBp6est_new()\fP 
.br
\fIuser_pointer\fP the same as in \fBp6est_new()\fP
.RE
.PP
\fBReturns\fP
.RS 4
This returns a valid forest\&. The user must destroy the connectivity for the new \fBp6est\fP independently\&.
.RE
.PP
\fBNote\fP
.RS 4
p4est->p\&.user_data is not retained\&. 
.RE
.PP

.SS "\fBp4est_gloidx_t\fP p6est_partition (\fBp6est_t\fP * p6est, \fBp6est_weight_t\fP weight_fn)"

.PP
Equally partition the forest\&. The forest will be partitioned between processors where they each have an approximately equal number of quadrants\&.
.PP
Note that \fIp6est->layers\fP and \fIp6est->global_first_layers\fP may change during this call\&. Address pointers referencing these objects from before \fIp6est_partition\fP is called become invalid\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP The forest that will be partitioned\&. 
.br
\fIweight_fn\fP A weighting function or NULL for uniform partitioning\&. 
.RE
.PP

.SS "void p6est_qcoord_to_vertex (\fBp6est_connectivity_t\fP * connectivity, \fBp4est_topidx_t\fP treeid, \fBp4est_qcoord_t\fP x, \fBp4est_qcoord_t\fP y, \fBp4est_qcoord_t\fP z, double vxyz[3])"

.PP
Transform a quadrant coordinate into the space spanned by tree vertices\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnectivity\fP Connectivity must provide the vertices\&. 
.br
\fItreeid\fP Identify the tree that contains x, y\&. 
.br
\fIx\fP Quadrant coordinate relative to treeid\&. 
.br
\fIy\fP Quadrant coordinate relative to treeid\&. 
.br
\fIz\fP Quadrant coordinate relative to treeid\&. 
.br
\fIvxyz\fP Transformed coordinates in vertex space\&. 
.RE
.PP

.SS "void p6est_refine_columns (\fBp6est_t\fP * p6est, int refine_recursive, \fBp6est_refine_column_t\fP refine_fn, \fBp6est_init_t\fP init_fn)"

.PP
Refine the columns of a sheet\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP The forest is changed in place\&. 
.br
\fIrefine_recursive\fP Boolean to decide on recursive refinement\&. 
.br
\fIrefine_fn\fP Callback function that must return true if a column shall be refined into smaller columns\&. If refine_recursive is true, refine_fn is called for every existing and newly created column\&. Otherwise, it is called for every existing column\&. It is possible that a refinement request made by the callback is ignored\&. To catch this case, you can examine whether init_fn gets called, or use p6est_refine_columns_ext in \fBp6est_extended\&.h\fP and examine whether replace_fn gets called\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data of newly created layers within columns, which are already allocated\&. This function pointer may be NULL\&. 
.RE
.PP

.SS "void p6est_refine_layers (\fBp6est_t\fP * p6est, int refine_recursive, \fBp6est_refine_layer_t\fP refine_fn, \fBp6est_init_t\fP init_fn)"

.PP
Refine the layers within the columns of a sheet\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp6est\fP\fP The forest is changed in place\&. 
.br
\fIrefine_recursive\fP Boolean to decide on recursive refinement\&. 
.br
\fIrefine_fn\fP Callback function that must return true if a layer shall be refined into smaller layers\&. If refine_recursive is true, refine_fn is called for every existing and newly created layer\&. Otherwise, it is called for every existing layer\&. It is possible that a refinement request made by the callback is ignored\&. To catch this case, you can examine whether init_fn gets called, or use p6est_refine_layers_ext in \fBp6est_extended\&.h\fP and examine whether replace_fn gets called\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data of newly created layers, which are already allocated\&. This function pointer may be NULL\&. 
.RE
.PP

.SS "void p6est_reset_data (\fBp6est_t\fP * p6est, size_t data_size, \fBp6est_init_t\fP init_fn, void * user_pointer)"

.PP
Reset user pointer and element data\&. When the data size is changed the quadrant data is freed and allocated\&. The initialization callback is invoked on each quadrant\&. Old user_data content is disregarded\&.
.PP
\fBParameters\fP
.RS 4
\fIdata_size\fP This is the size of data for each quadrant which can be zero\&. Then user_data_pool is set to NULL\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.br
\fIuser_pointer\fP Assign to the user_pointer member of the \fBp6est\fP before init_fn is called the first time\&. 
.RE
.PP

.SS "void p6est_save (const char * filename, \fBp6est_t\fP * p6est, int save_data)"

.PP
Save the complete connectivity/p6est data to disk\&. This is a collective
.PP
operation that all MPI processes need to call\&. All processes write into the same file, so the filename given needs to be identical over all parallel invocations\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file to write\&. 
.br
\fI\fBp6est\fP\fP Valid forest structure\&. 
.br
\fIsave_data\fP If true, the element data is saved\&. Otherwise, a data size of 0 is saved\&. 
.RE
.PP
\fBNote\fP
.RS 4
Aborts on file errors\&. 
.RE
.PP

.SS "void p6est_tree_get_vertices (\fBp6est_connectivity_t\fP * conn, \fBp4est_topidx_t\fP which_tree, double vertices[24])"

.PP
Get the vertices of the corners of a tree\&. 
.PP
\fBParameters\fP
.RS 4
\fIconn\fP the 2D+1D connectivity structure 
.br
\fIwhich_tree\fP a tree in the forest 
.br
\fIvertices\fP the coordinates of the corners of the tree 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
