.TH "p8est_wrap_leaf" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_wrap_leaf
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp8est_wrap_t\fP * \fBpp\fP"
.br
.RI "Must contain a valid ghost\&. "
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.RI "Current tree number\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBwhich_quad\fP"
.br
.RI "Quadrant number relative to tree\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBlocal_quad\fP"
.br
.RI "Quadrant number relative to proc\&. "
.ti -1c
.RI "\fBp8est_tree_t\fP * \fBtree\fP"
.br
.RI "Current tree\&. "
.ti -1c
.RI "sc_array_t * \fBtquadrants\fP"
.br
.RI "Current tree's quadrants\&. "
.ti -1c
.RI "\fBp8est_quadrant_t\fP * \fBquad\fP"
.br
.RI "Current quadrant\&. "
.ti -1c
.RI "int \fBis_mirror\fP"
.br
.RI "Quadrant at parallel boundary? "
.ti -1c
.RI "sc_array_t * \fBmirrors\fP"
.br
.RI "If not NULL, from pp's ghost\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBnm\fP"
.br
.RI "Internal: mirror counter\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBnext_mirror_quadrant\fP"
.br
.RI "Internal: next\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
