.TH "p8est_transfer_context" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_transfer_context \- Context data to allow for split begin/end data transfer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_communication\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvariable\fP"
.br
.ti -1c
.RI "int \fBnum_senders\fP"
.br
.ti -1c
.RI "int \fBnum_receivers\fP"
.br
.ti -1c
.RI "sc_MPI_Request * \fBrecv_req\fP"
.br
.ti -1c
.RI "sc_MPI_Request * \fBsend_req\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Context data to allow for split begin/end data transfer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
