.TH "src/p8est.h" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/p8est.h \- The top-level 3D \fBp8est\fP interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <p8est_connectivity\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBp8est_quadrant\fP"
.br
.RI "The 3D quadrant (i\&.e\&., octant) datatype\&. "
.ti -1c
.RI "union \fBp8est_quadrant::p8est_quadrant_data\fP"
.br
.RI "Union for quadrant data\&. "
.ti -1c
.RI "struct \fBp8est_tree\fP"
.br
.RI "The \fBp8est\fP tree datatype\&. "
.ti -1c
.RI "struct \fBp8est\fP"
.br
.RI "The \fBp8est\fP forest datatype\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBP8EST_OLD_MAXLEVEL\fP   19   /* old means prior to mid\-2020 */"
.br
.RI "The finest level of the octree for representing nodes\&. "
.ti -1c
.RI "#define \fBP8EST_MAXLEVEL\fP   30"
.br
.RI "The finest level for representing quadrant midpoint coordinates\&. "
.ti -1c
.RI "#define \fBP8EST_OLD_QMAXLEVEL\fP   18  /* old means prior to mid\-2020 */"
.br
.RI "The finest level of the octree for representing octants\&. "
.ti -1c
.RI "#define \fBP8EST_QMAXLEVEL\fP   29"
.br
.RI "The finest level of the quadtree for representing quadrant corners\&. "
.ti -1c
.RI "#define \fBP8EST_ROOT_LEN\fP   ((\fBp4est_qcoord_t\fP) 1 << \fBP8EST_MAXLEVEL\fP)"
.br
.RI "The length of a side of the root quadrant\&. "
.ti -1c
.RI "#define \fBP8EST_QUADRANT_LEN\fP(l)   ((\fBp4est_qcoord_t\fP) 1 << (\fBP8EST_MAXLEVEL\fP \- (l)))"
.br
.RI "The length of a quadrant of level l\&. "
.ti -1c
.RI "#define \fBP8EST_QUADRANT_MASK\fP(l)   (~(\fBP8EST_QUADRANT_LEN\fP (l) \- 1))"
.br
.RI "Create a mask of 1-bits from the left and maxlevel-level zero bits\&. "
.ti -1c
.RI "#define \fBP8EST_LAST_OFFSET\fP(l)   (\fBP8EST_ROOT_LEN\fP \- \fBP8EST_QUADRANT_LEN\fP (l))"
.br
.RI "The offset of the highest (farthest from the origin) quadrant at level l\&. "
.ti -1c
.RI "#define \fBP8EST_QUADRANT_INIT\fP(q)     ((void) memset ((q), \-1, sizeof (\fBp8est_quadrant_t\fP)))"
.br
.RI "set statically allocated quadrant to defined values "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBp8est_quadrant\fP \fBp8est_quadrant_t\fP"
.br
.RI "The 3D quadrant (i\&.e\&., octant) datatype\&. "
.ti -1c
.RI "typedef struct \fBp8est_tree\fP \fBp8est_tree_t\fP"
.br
.RI "The \fBp8est\fP tree datatype\&. "
.ti -1c
.RI "typedef struct \fBp8est_inspect\fP \fBp8est_inspect_t\fP"
.br
.RI "Data pertaining to selecting, inspecting, and profiling algorithms\&. "
.ti -1c
.RI "typedef struct \fBp8est\fP \fBp8est_t\fP"
.br
.RI "The \fBp8est\fP forest datatype\&. "
.ti -1c
.RI "typedef void(* \fBp8est_init_t\fP) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrant)"
.br
.RI "Callback function prototype to initialize the quadrant's user data\&. "
.ti -1c
.RI "typedef int(* \fBp8est_refine_t\fP) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrant)"
.br
.RI "Callback function prototype to decide for refinement\&. "
.ti -1c
.RI "typedef int(* \fBp8est_coarsen_t\fP) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrants[])"
.br
.RI "Callback function prototype to decide for coarsening\&. "
.ti -1c
.RI "typedef int(* \fBp8est_weight_t\fP) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrant)"
.br
.RI "Callback function prototype to calculate weights for partitioning\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBp8est_memory_used\fP (\fBp8est_t\fP *\fBp8est\fP)"
.br
.RI "Calculate local memory usage of a forest structure\&. "
.ti -1c
.RI "long \fBp8est_revision\fP (\fBp8est_t\fP *\fBp8est\fP)"
.br
.RI "Return the revision counter of the forest\&. "
.ti -1c
.RI "void \fBp8est_qcoord_to_vertex\fP (\fBp8est_connectivity_t\fP *connectivity, \fBp4est_topidx_t\fP treeid, \fBp4est_qcoord_t\fP x, \fBp4est_qcoord_t\fP y, \fBp4est_qcoord_t\fP z, double vxyz[3])"
.br
.RI "Transform a quadrant coordinate into the space spanned by tree vertices\&. "
.ti -1c
.RI "\fBp8est_t\fP * \fBp8est_new\fP (sc_MPI_Comm mpicomm, \fBp8est_connectivity_t\fP *connectivity, size_t data_size, \fBp8est_init_t\fP init_fn, void *user_pointer)"
.br
.RI "Create a new forest with an initial coarse mesh\&. "
.ti -1c
.RI "void \fBp8est_destroy\fP (\fBp8est_t\fP *\fBp8est\fP)"
.br
.RI "Destroy a \fBp8est\fP\&. "
.ti -1c
.RI "\fBp8est_t\fP * \fBp8est_copy\fP (\fBp8est_t\fP *input, int copy_data)"
.br
.RI "Make a deep copy of a \fBp8est\fP\&. "
.ti -1c
.RI "void \fBp8est_reset_data\fP (\fBp8est_t\fP *\fBp8est\fP, size_t data_size, \fBp8est_init_t\fP init_fn, void *user_pointer)"
.br
.RI "Reset user pointer and element data\&. "
.ti -1c
.RI "void \fBp8est_refine\fP (\fBp8est_t\fP *\fBp8est\fP, int refine_recursive, \fBp8est_refine_t\fP refine_fn, \fBp8est_init_t\fP init_fn)"
.br
.RI "Refine a forest\&. "
.ti -1c
.RI "void \fBp8est_coarsen\fP (\fBp8est_t\fP *\fBp8est\fP, int coarsen_recursive, \fBp8est_coarsen_t\fP coarsen_fn, \fBp8est_init_t\fP init_fn)"
.br
.RI "Coarsen a forest\&. "
.ti -1c
.RI "void \fBp8est_balance\fP (\fBp8est_t\fP *\fBp8est\fP, \fBp8est_connect_type_t\fP btype, \fBp8est_init_t\fP init_fn)"
.br
.RI "2:1 balance the size differences of neighboring elements in a forest\&. "
.ti -1c
.RI "void \fBp8est_partition\fP (\fBp8est_t\fP *\fBp8est\fP, int allow_for_coarsening, \fBp8est_weight_t\fP weight_fn)"
.br
.RI "Equally partition the forest\&. "
.ti -1c
.RI "unsigned \fBp8est_checksum\fP (\fBp8est_t\fP *\fBp8est\fP)"
.br
.RI "Compute the checksum for a forest\&. "
.ti -1c
.RI "unsigned \fBp8est_checksum_partition\fP (\fBp8est_t\fP *\fBp8est\fP)"
.br
.RI "Compute a partition-dependent checksum for a forest\&. "
.ti -1c
.RI "void \fBp8est_save\fP (const char *filename, \fBp8est_t\fP *\fBp8est\fP, int save_data)"
.br
.RI "Save the complete connectivity/p8est data to disk\&. "
.ti -1c
.RI "\fBp8est_t\fP * \fBp8est_load\fP (const char *filename, sc_MPI_Comm mpicomm, size_t data_size, int load_data, void *user_pointer, \fBp8est_connectivity_t\fP **connectivity)"
.br
.RI "Load the complete connectivity/p8est structure from disk\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBP8EST_DATA_UNINITIALIZED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The top-level 3D \fBp8est\fP interface\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef int(* p8est_coarsen_t) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrants[])"

.PP
Callback function prototype to decide for coarsening\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP the forest 
.br
\fIwhich_tree\fP the tree containing \fIquadrant\fP 
.br
\fIquadrants\fP Pointers to 8 siblings in Morton ordering\&. 
.RE
.PP
\fBReturns\fP
.RS 4
nonzero if the quadrants shall be replaced with their parent\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "typedef void(* p8est_init_t) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrant)"

.PP
Callback function prototype to initialize the quadrant's user data\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP the forest 
.br
\fIwhich_tree\fP the tree containing \fIquadrant\fP 
.br
\fIquadrant\fP the quadrant to be initialized: if data_size > 0, the data to be initialized is at \fIquadrant->p\&.user_data\fP; otherwise, the non-pointer user data (such as \fIquadrant->p\&.user_int\fP) can be initialized 
.RE
.PP

.SS "typedef struct \fBp8est_inspect\fP \fBp8est_inspect_t\fP"

.PP
Data pertaining to selecting, inspecting, and profiling algorithms\&. A pointer to this structure is hooked into the \fBp8est\fP main structure\&. Declared in \fBp8est_extended\&.h\fP\&. Used to profile important algorithms\&. 
.SS "typedef int(* p8est_refine_t) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrant)"

.PP
Callback function prototype to decide for refinement\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP the forest 
.br
\fIwhich_tree\fP the tree containing \fIquadrant\fP 
.br
\fIquadrant\fP the quadrant that may be refined 
.RE
.PP
\fBReturns\fP
.RS 4
nonzero if the quadrant shall be refined\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "typedef int(* p8est_weight_t) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, \fBp8est_quadrant_t\fP *quadrant)"

.PP
Callback function prototype to calculate weights for partitioning\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP the forest 
.br
\fIwhich_tree\fP the tree containing \fIquadrant\fP 
.RE
.PP
\fBReturns\fP
.RS 4
a 32bit integer >= 0 as the quadrant weight\&. 
.RE
.PP
\fBNote\fP
.RS 4
Global sum of weights must fit into a 64bit integer\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void p8est_balance (\fBp8est_t\fP * p8est, \fBp8est_connect_type_t\fP btype, \fBp8est_init_t\fP init_fn)"

.PP
2:1 balance the size differences of neighboring elements in a forest\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The \fBp8est\fP to be worked on\&. 
.br
\fIbtype\fP Balance type (face, edge, or corner/full)\&. Examples: Finite volume or discontinuous Galerkin methods only require face balance\&. Continuous finite element methods usually require edge balance\&. Corner balance is almost never required mathematically; it just produces a smoother mesh grading\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "unsigned p8est_checksum (\fBp8est_t\fP * p8est)"

.PP
Compute the checksum for a forest\&. Based on quadrant arrays only\&. It is independent of partition and mpisize\&. 
.PP
\fBReturns\fP
.RS 4
Returns the checksum on all processors\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "unsigned p8est_checksum_partition (\fBp8est_t\fP * p8est)"

.PP
Compute a partition-dependent checksum for a forest\&. 
.PP
\fBReturns\fP
.RS 4
Returns the checksum on all processors\&. 
.RE
.PP

.SS "void p8est_coarsen (\fBp8est_t\fP * p8est, int coarsen_recursive, \fBp8est_coarsen_t\fP coarsen_fn, \fBp8est_init_t\fP init_fn)"

.PP
Coarsen a forest\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The forest is changed in place\&. 
.br
\fIcoarsen_recursive\fP Boolean to decide on recursive coarsening\&. 
.br
\fIcoarsen_fn\fP Callback function that returns true if a family of quadrants shall be coarsened 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "\fBp8est_t\fP* p8est_copy (\fBp8est_t\fP * input, int copy_data)"

.PP
Make a deep copy of a \fBp8est\fP\&. The connectivity is not duplicated\&. Copying of quadrant user data is optional\&. If old and new data sizes are 0, the user_data field is copied regardless\&. The inspect member of the copy is set to NULL\&. The revision counter of the copy is set to zero\&.
.PP
\fBParameters\fP
.RS 4
\fIcopy_data\fP If true, data are copied\&. If false, data_size is set to 0\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a valid \fBp8est\fP that does not depend on the input, except for borrowing the same connectivity\&. Its revision counter is 0\&. 
.RE
.PP

.SS "void p8est_destroy (\fBp8est_t\fP * p8est)"

.PP
Destroy a \fBp8est\fP\&. 
.PP
\fBNote\fP
.RS 4
The connectivity structure is not destroyed with the \fBp8est\fP\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "\fBp8est_t\fP* p8est_load (const char * filename, sc_MPI_Comm mpicomm, size_t data_size, int load_data, void * user_pointer, \fBp8est_connectivity_t\fP ** connectivity)"

.PP
Load the complete connectivity/p8est structure from disk\&. This is a collective operation that all MPI processes need to call\&. All processes read from the same file, so the filename given needs to be identical over all parallel invocations\&.
.PP
By default, a file can only be loaded with the same number of processors that it was stored with\&. The defaults can be changed with \fBp8est_load_ext()\fP in \fBp8est_extended\&.h\fP\&.
.PP
The revision counter of the loaded \fBp4est\fP is set to zero\&.
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file to read\&. 
.br
\fImpicomm\fP A valid MPI communicator\&. 
.br
\fIdata_size\fP Size of data for each quadrant which can be zero\&. Then user_data_pool is set to NULL\&. If data_size is zero, load_data is ignored\&. 
.br
\fIload_data\fP If true, the element data is loaded\&. This is only permitted if the saved data size matches\&. If false, the stored data size is ignored\&. 
.br
\fIuser_pointer\fP Assign to the user_pointer member of the \fBp8est\fP before init_fn is called the first time\&. 
.br
\fIconnectivity\fP Connectivity must be destroyed separately\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a valid forest structure\&. A pointer to a valid connectivity structure is returned through the last argument\&. 
.RE
.PP
\fBNote\fP
.RS 4
Aborts on file errors or invalid file contents\&. 
.RE
.PP

.SS "size_t p8est_memory_used (\fBp8est_t\fP * p8est)"

.PP
Calculate local memory usage of a forest structure\&. Not collective\&. The memory used on the current rank is returned\&. The connectivity structure is not counted since it is not owned; use p8est_connectivity_memory_usage (p8est->connectivity)\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP Valid forest structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Memory used in bytes\&. 
.RE
.PP

.SS "\fBp8est_t\fP* p8est_new (sc_MPI_Comm mpicomm, \fBp8est_connectivity_t\fP * connectivity, size_t data_size, \fBp8est_init_t\fP init_fn, void * user_pointer)"

.PP
Create a new forest with an initial coarse mesh\&. The new forest consists of equi-partitioned root quadrants\&. When there are more processors than trees, some processors are empty\&.
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP A valid MPI communicator\&. 
.br
\fIconnectivity\fP This is the connectivity information that the forest is built with\&. Note the \fBp8est\fP does not take ownership of the memory\&. 
.br
\fIdata_size\fP This is the size of data for each quadrant which can be zero\&. Then user_data_pool is set to NULL\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.br
\fIuser_pointer\fP Assign to the user_pointer member of the \fBp8est\fP before init_fn is called the first time\&.
.RE
.PP
\fBReturns\fP
.RS 4
This returns a valid forest\&.
.RE
.PP
\fBNote\fP
.RS 4
The connectivity structure must not be destroyed during the lifetime of this forest\&. 
.RE
.PP

.SS "void p8est_partition (\fBp8est_t\fP * p8est, int allow_for_coarsening, \fBp8est_weight_t\fP weight_fn)"

.PP
Equally partition the forest\&. The partition can be by element count or by a user-defined weight\&.
.PP
The forest will be partitioned between processors such that they have an approximately equal number of quadrants (or sum of weights)\&.
.PP
The user data of a quadrant is transferred along within this function\&.
.PP
On one process, the function noops and does not call the weight callback\&. Otherwise, the weight callback is called once per quadrant in order\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The forest that will be partitioned\&. 
.br
\fIallow_for_coarsening\fP Slightly modify partition such that quadrant families are not split between ranks\&. 
.br
\fIweight_fn\fP A weighting function or NULL for uniform partitioning\&. When running with mpisize == 1, never called\&. Otherwise, called in order for all quadrants if not NULL\&. A weighting function with constant weight 1 on each quadrant is equivalent to weight_fn == NULL but other constant weightings may result in different uniform partitionings\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "void p8est_qcoord_to_vertex (\fBp8est_connectivity_t\fP * connectivity, \fBp4est_topidx_t\fP treeid, \fBp4est_qcoord_t\fP x, \fBp4est_qcoord_t\fP y, \fBp4est_qcoord_t\fP z, double vxyz[3])"

.PP
Transform a quadrant coordinate into the space spanned by tree vertices\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnectivity\fP Connectivity must provide the vertices\&. 
.br
\fItreeid\fP Identify the tree that contains x, y, z\&. 
.br
\fIx,y,z\fP Quadrant coordinates relative to treeid\&. 
.br
\fIvxyz\fP Transformed coordinates in vertex space\&. 
.RE
.PP

.SS "void p8est_refine (\fBp8est_t\fP * p8est, int refine_recursive, \fBp8est_refine_t\fP refine_fn, \fBp8est_init_t\fP init_fn)"

.PP
Refine a forest\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The forest is changed in place\&. 
.br
\fIrefine_recursive\fP Boolean to decide on recursive refinement\&. 
.br
\fIrefine_fn\fP Callback function that must return true if a quadrant shall be refined\&. If refine_recursive is true, refine_fn is called for every existing and newly created quadrant\&. Otherwise, it is called for every existing quadrant\&. It is possible that a refinement request made by the callback is ignored\&. To catch this case, you can examine whether init_fn gets called, or use p8est_refine_ext in \fBp8est_extended\&.h\fP and examine whether replace_fn gets called\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data of newly created quadrants, which is already allocated\&. This function pointer may be NULL\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "void p8est_reset_data (\fBp8est_t\fP * p8est, size_t data_size, \fBp8est_init_t\fP init_fn, void * user_pointer)"

.PP
Reset user pointer and element data\&. When the data size is changed the quadrant data is freed and allocated\&. The initialization callback is invoked on each quadrant\&. Old user_data content is disregarded\&.
.PP
\fBParameters\fP
.RS 4
\fIdata_size\fP This is the size of data for each quadrant which can be zero\&. Then user_data_pool is set to NULL\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. May be NULL\&. 
.br
\fIuser_pointer\fP Assign to the user_pointer member of the \fBp8est\fP before init_fn is called the first time\&. 
.RE
.PP

.SS "long p8est_revision (\fBp8est_t\fP * p8est)"

.PP
Return the revision counter of the forest\&. Not collective, even though the revision value is the same on all ranks\&. A newly created forest starts with a revision counter of zero\&. Every refine, coarsen, partition, and balance that actually changes the mesh increases the counter by one\&. Operations with no effect keep the old value\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The forest must be valid\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Non-negative number\&. 
.RE
.PP

.SS "void p8est_save (const char * filename, \fBp8est_t\fP * p8est, int save_data)"

.PP
Save the complete connectivity/p8est data to disk\&. This is a collective operation that all MPI processes need to call\&. All processes write into the same file, so the filename given needs to be identical over all parallel invocations\&.
.PP
By default, we write the current processor count and partition into the file header\&. This makes the file depend on mpisize\&. For changing this see \fBp8est_save_ext()\fP in \fBp8est_extended\&.h\fP\&.
.PP
The revision counter is not saved to the file, since that would make files different that come from different revisions but store the same mesh\&.
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file to write\&. 
.br
\fI\fBp8est\fP\fP Valid forest structure\&. 
.br
\fIsave_data\fP If true, the element data is saved\&. Otherwise, a data size of 0 is saved\&. 
.RE
.PP
\fBNote\fP
.RS 4
Aborts on file errors\&. 
.PP
If \fBp4est\fP is not configured to use MPI-IO, some processes return from this function before the file is complete, in which case immediate read-access to the file may require a call to sc_MPI_Barrier\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
