.TH "deprecated" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBsc_options_destroy_deep\fP (sc_options_t *opt)\fP" 1c
This function is kept for backwards compatibility\&. It is best to destroy any key-value container outside of the lifetime of the options object\&. 
.PP

