.TH "io" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io \- I/O
.PP
 \- Functionality specific to file/data input/output\&.  

.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsc_io\&.h\fP"
.br
.RI "Helper routines for general and parallel I/O\&. "
.ti -1c
.RI "file \fBsc_scda\&.h\fP"
.br
.RI "Routines for parallel I/O with the \fBscda\fP format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functionality specific to file/data input/output\&. 

Generic I/O support: \fBsc_io\&.h\fP
.PP
The I/O support provides functions to read and write data based on C-standard functions and also an other set of functions to read and write based on MPI I/O if it is enabled\&. Furthermore, there are functions to encode and decode based on zlib and to write VTK files\&.
.PP
Parallel file format: \fBsc_scda\&.h\fP
.PP
This file contains routines for parallel I/O format\&. In particular there are functions to write and read data in parallel according to a user prescribed partition of contigously indexed potentially variable-sized elements\&. In addition, the user can also write and read data in serial and the data can be stored element-wise compressed\&.
.PP
If MPI I/O is available, it is used to write and read in parallel\&. The configuration case of MPI without MPI I/O is deprecated\&. Without MPI this module still enables the user to write and read equivalent files but only in serial\&.
.PP
We elaborate further on the workflow in \fBParallel I/O workflow\fP \&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
