.TH "sc" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc \- The sc Library
.PP
 \- The SC Library provides support for parallel scientific applications\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBContainers\fP"
.br
.RI "The library provides dynamic containers such as lists, arrays, and hash tables\&. "
.ti -1c
.RI "\fBI/O\fP"
.br
.RI "Functionality specific to file/data input/output\&. "
.ti -1c
.RI "\fBLog Priorities\fP"
.br
.RI "The log level is a number designating the priority of a log action\&. "
.ti -1c
.RI "\fBOption Parser\fP"
.br
.RI "The option parser reads the command line as well as configuration files\&. "
.ti -1c
.RI "\fBParallelism\fP"
.br
.RI "The sc library provides several mechanisms to work with MPI\&. "
.in -1c
.SH "Detailed Description"
.PP 
The SC Library provides support for parallel scientific applications\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
