.TH "src/sc.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc.h \- Support for process management (memory allocation, logging, etc\&.)  

.SH SYNOPSIS
.br
.PP
\fC#include <sc_config\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sc_mpi\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GNU_SOURCE\fP"
.br
.ti -1c
.RI "#define \fB_sc_const\fP   const"
.br
.RI "Portable way to work with really old compilers without const\&. "
.ti -1c
.RI "#define \fB_sc_restrict\fP   restrict"
.br
.RI "Portable way to work with really old compilers without restrict\&. "
.ti -1c
.RI "#define \fBSC_CALC_VERSION\fP(major,  minor,  patchlevel)                          (((major) * 1000 + (minor)) * 1000 + (patchlevel))"
.br
.RI "Test for gcc version without features\&.h\&. "
.ti -1c
.RI "#define \fBSC_GCC_VERSION\fP           \fBSC_CALC_VERSION\fP (0, 0, 0)"
.br
.RI "Assemble GCC version using a 1000-per-digit scheme\&. "
.ti -1c
.RI "#define \fBSC_NOCOUNT_MALLOC\fP"
.br
.ti -1c
.RI "#define \fBSC_NOCOUNT_REFCOUNT\fP"
.br
.ti -1c
.RI "#define \fBSC_NOCOUNT_LOGINDENT\fP"
.br
.ti -1c
.RI "#define \fB__STDC_LIMIT_MACROS\fP"
.br
.RI "Activate C99 limit macros for older C++ compilers\&. "
.ti -1c
.RI "#define \fB__STDC_CONSTANT_MACROS\fP"
.br
.RI "Activate C99 constant macros for older C++ compilers\&. "
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.ti -1c
.RI "#define \fBM_E\fP   2\&.71828182845904523536"
.br
.ti -1c
.RI "#define \fBM_LOG2E\fP   1\&.44269504088896340736"
.br
.ti -1c
.RI "#define \fBM_LOG10E\fP   0\&.434294481903251827651"
.br
.ti -1c
.RI "#define \fBM_LN2\fP   0\&.693147180559945309417"
.br
.ti -1c
.RI "#define \fBM_LN10\fP   2\&.30258509299404568402"
.br
.ti -1c
.RI "#define \fBM_PI\fP   3\&.14159265358979323846"
.br
.ti -1c
.RI "#define \fBM_PI_2\fP   1\&.57079632679489661923"
.br
.ti -1c
.RI "#define \fBM_PI_4\fP   0\&.785398163397448309616"
.br
.ti -1c
.RI "#define \fBM_1_PI\fP   0\&.318309886183790671538"
.br
.ti -1c
.RI "#define \fBM_2_PI\fP   0\&.636619772367581343076"
.br
.ti -1c
.RI "#define \fBM_2_SQRTPI\fP   1\&.12837916709551257390"
.br
.ti -1c
.RI "#define \fBM_SQRT2\fP   1\&.41421356237309504880"
.br
.ti -1c
.RI "#define \fBM_SQRT1_2\fP   0\&.707106781186547524401"
.br
.ti -1c
.RI "#define \fBSC_INIT_COMM_CLEAN\fP"
.br
.RI "Indicate that we do not modify the communicator in sc_init\&. "
.ti -1c
.RI "#define \fBSC_NOARGS\fP"
.br
.RI "For compatibility of varargs with C++\&. "
.ti -1c
.RI "#define \fBSC_EPS\fP   2\&.220446049250313e\-16"
.br
.RI "Define machine epsilon for the double type\&. "
.ti -1c
.RI "#define \fBSC_1000_EPS\fP   (1000\&. * 2\&.220446049250313e\-16)"
.br
.RI "Define 1000 times the machine epsilon for the double type\&. "
.ti -1c
.RI "#define \fBSC_NOOP\fP()   ((void) (0))"
.br
.RI "A macro to do and return nothing as an expression\&. "
.ti -1c
.RI "#define \fBSC_ABORT\fP(s)     \fBsc_abort_verbose\fP (__FILE__, __LINE__, (s))"
.br
.ti -1c
.RI "#define \fBSC_ABORT_NOT_REACHED\fP()   SC_ABORT ('Unreachable code')"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORT\fP(q,  s)     ((q) ? (void) 0 : SC_ABORT (s))"
.br
.ti -1c
.RI "#define \fBSC_CHECK_MPI\fP(r)   SC_CHECK_ABORT ((r) == \fBsc_MPI_SUCCESS\fP, 'MPI error')"
.br
.ti -1c
.RI "#define \fBSC_ABORTF\fP(fmt, \&.\&.\&.)     \fBsc_abort_verbosef\fP (__FILE__, __LINE__, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORTF\fP(q,  fmt, \&.\&.\&.)     ((q) ? (void) 0 : SC_ABORTF (fmt, __VA_ARGS__))"
.br
.ti -1c
.RI "#define \fBSC_ABORT1\fP(fmt,  a)     \fBsc_abort_verbosef\fP (__FILE__, __LINE__, (fmt), (a))"
.br
.ti -1c
.RI "#define \fBSC_ABORT2\fP(fmt,  a,  b)     \fBsc_abort_verbosef\fP (__FILE__, __LINE__, (fmt), (a), (b))"
.br
.ti -1c
.RI "#define \fBSC_ABORT3\fP(fmt,  a,  b,  c)     \fBsc_abort_verbosef\fP (__FILE__, __LINE__, (fmt), (a), (b), (c))"
.br
.ti -1c
.RI "#define \fBSC_ABORT4\fP(fmt,  a,  b,  c,  d)     \fBsc_abort_verbosef\fP (__FILE__, __LINE__, (fmt), (a), (b), (c), (d))"
.br
.ti -1c
.RI "#define \fBSC_ABORT5\fP(fmt,  a,  b,  c,  d,  e)     \fBsc_abort_verbosef\fP (__FILE__, __LINE__, (fmt), (a), (b), (c), (d), (e))"
.br
.ti -1c
.RI "#define \fBSC_ABORT6\fP(fmt,  a,  b,  c,  d,  e,  f)     \fBsc_abort_verbosef\fP (__FILE__, __LINE__, (fmt), (a), (b), (c), (d), (e), (f))"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORT1\fP(q,  fmt,  a)     ((q) ? (void) 0 : SC_ABORT1 ((fmt), (a)))"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORT2\fP(q,  fmt,  a,  b)     ((q) ? (void) 0 : SC_ABORT2 ((fmt), (a), (b)))"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORT3\fP(q,  fmt,  a,  b,  c)     ((q) ? (void) 0 : SC_ABORT3 ((fmt), (a), (b), (c)))"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORT4\fP(q,  fmt,  a,  b,  c,  d)     ((q) ? (void) 0 : SC_ABORT4 ((fmt), (a), (b), (c), (d)))"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORT5\fP(q,  fmt,  a,  b,  c,  d,  e)     ((q) ? (void) 0 : SC_ABORT5 ((fmt), (a), (b), (c), (d), (e)))"
.br
.ti -1c
.RI "#define \fBSC_CHECK_ABORT6\fP(q,  fmt,  a,  b,  c,  d,  e,  f)     ((q) ? (void) 0 : SC_ABORT6 ((fmt), (a), (b), (c), (d), (e), (f)))"
.br
.ti -1c
.RI "#define \fBSC_ASSERT\fP(c)   \fBSC_NOOP\fP ()"
.br
.ti -1c
.RI "#define \fBSC_EXECUTE_ASSERT_FALSE\fP(expression)     do { (void) (expression); } while (0)"
.br
.ti -1c
.RI "#define \fBSC_EXECUTE_ASSERT_TRUE\fP(expression)     do { (void) (expression); } while (0)"
.br
.ti -1c
.RI "#define \fBSC_ALLOC\fP(t,  n)   (t *) sc_malloc (\fBsc_package_id\fP, (n) * sizeof(t))"
.br
.ti -1c
.RI "#define \fBSC_ALLOC_ZERO\fP(t,  n)"
.br
.ti -1c
.RI "#define \fBSC_REALLOC\fP(p,  t,  n)"
.br
.ti -1c
.RI "#define \fBSC_STRDUP\fP(s)   sc_strdup (\fBsc_package_id\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_FREE\fP(p)   sc_free (\fBsc_package_id\fP, (p))"
.br
.ti -1c
.RI "#define \fBSC_ALIGN_UP\fP(x,  n)   ( ((n) <= 0) ? (x) : ((x) + (n) \- 1) / (n) * (n) )"
.br
.ti -1c
.RI "#define \fBSC_ARG_ALIGN\fP(p,  t,  n)   \fBSC_NOOP\fP ()"
.br
.ti -1c
.RI "#define \fBSC_ATTR_ALIGN\fP(n)"
.br
.ti -1c
.RI "#define \fBSC_BZERO\fP(p,  n)   ((void) memset ((p), 0, (n) * sizeof (*(p))))"
.br
.RI "Sets n elements of a memory range to zero\&. "
.ti -1c
.RI "#define \fBSC_MIN\fP(a,  b)   (((a) < (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBSC_MAX\fP(a,  b)   (((a) > (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBSC_SQR\fP(a)   ((a) * (a))"
.br
.ti -1c
.RI "#define \fBSC_LOG2_8\fP(x)   (\fBsc_log2_lookup_table\fP[(x)])"
.br
.ti -1c
.RI "#define \fBSC_LOG2_16\fP(x)"
.br
.ti -1c
.RI "#define \fBSC_LOG2_32\fP(x)"
.br
.ti -1c
.RI "#define \fBSC_LOG2_64\fP(x)"
.br
.ti -1c
.RI "#define \fBSC_ROUNDUP2_32\fP(x)     (((x) <= 0) ? 0 : (1 << (SC_LOG2_32 ((x) \- 1) + 1)))"
.br
.ti -1c
.RI "#define \fBSC_ROUNDUP2_64\fP(x)     (((x) <= 0) ? 0 : (1LL << (SC_LOG2_64 ((x) \- 1LL) + 1)))"
.br
.ti -1c
.RI "#define \fBSC_LC_GLOBAL\fP   1"
.br
.RI "log only for master process "
.ti -1c
.RI "#define \fBSC_LC_NORMAL\fP   2"
.br
.RI "log for every process "
.ti -1c
.RI "#define \fBSC_LP_DEFAULT\fP   (\-1)"
.br
.RI "Selects the SC default threshold\&. "
.ti -1c
.RI "#define \fBSC_LP_ALWAYS\fP   0"
.br
.RI "Log absolutely everything\&. "
.ti -1c
.RI "#define \fBSC_LP_TRACE\fP   1"
.br
.RI "Prefix file and line number\&. "
.ti -1c
.RI "#define \fBSC_LP_DEBUG\fP   2"
.br
.RI "Any information on the internal state\&. "
.ti -1c
.RI "#define \fBSC_LP_VERBOSE\fP   3"
.br
.RI "Information on conditions, decisions\&. "
.ti -1c
.RI "#define \fBSC_LP_INFO\fP   4"
.br
.RI "Most relevant things a function is doing\&. "
.ti -1c
.RI "#define \fBSC_LP_STATISTICS\fP   5"
.br
.RI "Important for consistency/performance\&. "
.ti -1c
.RI "#define \fBSC_LP_PRODUCTION\fP   6"
.br
.RI "A few lines at most for a major api function\&. "
.ti -1c
.RI "#define \fBSC_LP_ESSENTIAL\fP   7"
.br
.RI "Log a few lines max (version info) per program\&. "
.ti -1c
.RI "#define \fBSC_LP_ERROR\fP   8"
.br
.RI "Log errors only\&. "
.ti -1c
.RI "#define \fBSC_LP_SILENT\fP   9"
.br
.RI "Never log anything\&. "
.ti -1c
.RI "#define \fBSC_LP_THRESHOLD\fP   \fBSC_LP_INFO\fP"
.br
.RI "The log threshold chosen by \fBSC_LP_DEFAULT\fP\&. "
.ti -1c
.RI "#define \fBSC_LP_APPLICATION\fP   \fBSC_LP_STATISTICS\fP"
.br
.RI "This threshold is intended for applications with conservative logging\&. "
.ti -1c
.RI "#define \fBSC_GEN_LOG\fP(package,  category,  priority,  s)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_LOG\fP(p,  s)   SC_GEN_LOG (\fBsc_package_id\fP, \fBSC_LC_GLOBAL\fP, (p), (s))"
.br
.ti -1c
.RI "#define \fBSC_LOG\fP(p,  s)   SC_GEN_LOG (\fBsc_package_id\fP, \fBSC_LC_NORMAL\fP, (p), (s))"
.br
.ti -1c
.RI "#define \fBSC_GEN_LOGF\fP(package,  category,  priority,  fmt, \&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_LOGF\fP(p,  fmt, \&.\&.\&.)     SC_GEN_LOGF (\fBsc_package_id\fP, \fBSC_LC_GLOBAL\fP, (p), (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_LOGF\fP(p,  fmt, \&.\&.\&.)     SC_GEN_LOGF (\fBsc_package_id\fP, \fBSC_LC_NORMAL\fP, (p), (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_TRACE\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_TRACE\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_LDEBUG\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_DEBUG\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_VERBOSE\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_VERBOSE\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_INFO\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_INFO\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_STATISTICS\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_STATISTICS\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_PRODUCTION\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_PRODUCTION\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_ESSENTIAL\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_ESSENTIAL\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_LERROR\fP(s)   SC_GLOBAL_LOG (\fBSC_LP_ERROR\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_TRACEF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_TRACE\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_LDEBUGF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_DEBUG\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_VERBOSEF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_VERBOSE\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_INFOF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_INFO\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_STATISTICSF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_STATISTICS\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_PRODUCTIONF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_PRODUCTION\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_ESSENTIALF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_ESSENTIAL\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_GLOBAL_LERRORF\fP(fmt, \&.\&.\&.)     SC_GLOBAL_LOGF (\fBSC_LP_ERROR\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_TRACE\fP(s)   SC_LOG (\fBSC_LP_TRACE\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_LDEBUG\fP(s)   SC_LOG (\fBSC_LP_DEBUG\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_VERBOSE\fP(s)   SC_LOG (\fBSC_LP_VERBOSE\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_INFO\fP(s)   SC_LOG (\fBSC_LP_INFO\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_STATISTICS\fP(s)   SC_LOG (\fBSC_LP_STATISTICS\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_PRODUCTION\fP(s)   SC_LOG (\fBSC_LP_PRODUCTION\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_ESSENTIAL\fP(s)   SC_LOG (\fBSC_LP_ESSENTIAL\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_LERROR\fP(s)   SC_LOG (\fBSC_LP_ERROR\fP, (s))"
.br
.ti -1c
.RI "#define \fBSC_TRACEF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_TRACE\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_LDEBUGF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_DEBUG\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_VERBOSEF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_VERBOSE\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_INFOF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_INFO\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_STATISTICSF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_STATISTICS\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_PRODUCTIONF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_PRODUCTION\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_ESSENTIALF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_ESSENTIAL\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBSC_LERRORF\fP(fmt, \&.\&.\&.)     SC_LOGF (\fBSC_LP_ERROR\fP, (fmt), __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fB_SC_TOSTRING\fP(x)   #x"
.br
.RI "Macros used to convert a macro definition such as the point version or some other numerical literal to a string\&. "
.ti -1c
.RI "#define \fBSC_TOSTRING\fP(x)   \fB_SC_TOSTRING\fP(x)"
.br
.RI "Macros used to convert a macro definition such as the point version or some other numerical literal to a string\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBsc_handler_t\fP) (void *data)"
.br
.ti -1c
.RI "typedef void(* \fBsc_log_handler_t\fP) (FILE *log_stream, const char *filename, int lineno, int package, int category, int priority, const char *msg)"
.br
.ti -1c
.RI "typedef void(* \fBsc_abort_handler_t\fP) (void)"
.br
.RI "Type of the abort handler function\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSC_ABORTF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_CHECK_ABORTF\fP (int success, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GEN_LOGF\fP (int package, int category, int priority, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_LOGF\fP (int priority, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_LOGF\fP (int priority, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_TRACEF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_LDEBUGF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_VERBOSEF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_INFOF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_STATISTICSF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_PRODUCTIONF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_ESSENTIALF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_GLOBAL_LERRORF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_TRACEF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_LDEBUGF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_VERBOSEF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_INFOF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_STATISTICSF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_PRODUCTIONF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_ESSENTIALF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBSC_LERRORF\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void * \fBsc_malloc\fP (int package, size_t size)"
.br
.ti -1c
.RI "void * \fBsc_calloc\fP (int package, size_t nmemb, size_t size)"
.br
.ti -1c
.RI "void * \fBsc_realloc\fP (int package, void *ptr, size_t size)"
.br
.ti -1c
.RI "char * \fBsc_strdup\fP (int package, const char *s)"
.br
.ti -1c
.RI "void \fBsc_free\fP (int package, void *ptr)"
.br
.ti -1c
.RI "int \fBsc_memory_status\fP (int package)"
.br
.ti -1c
.RI "void \fBsc_memory_check\fP (int package)"
.br
.ti -1c
.RI "int \fBsc_memory_check_noerr\fP (int package)"
.br
.RI "Return error count or zero if all is ok\&. "
.ti -1c
.RI "int \fBsc_int_compare\fP (const void *v1, const void *v2)"
.br
.ti -1c
.RI "int \fBsc_int8_compare\fP (const void *v1, const void *v2)"
.br
.ti -1c
.RI "int \fBsc_int16_compare\fP (const void *v1, const void *v2)"
.br
.ti -1c
.RI "int \fBsc_int32_compare\fP (const void *v1, const void *v2)"
.br
.ti -1c
.RI "int \fBsc_int64_compare\fP (const void *v1, const void *v2)"
.br
.ti -1c
.RI "int \fBsc_double_compare\fP (const void *v1, const void *v2)"
.br
.ti -1c
.RI "int \fBsc_atoi\fP (const char *nptr)"
.br
.RI "Safe version of the standard library atoi (3) function\&. "
.ti -1c
.RI "long \fBsc_atol\fP (const char *nptr)"
.br
.RI "Safe version of the standard library atol (3) function\&. "
.ti -1c
.RI "void \fBsc_set_log_defaults\fP (FILE *log_stream, sc_log_handler_t log_handler, int log_threshold)"
.br
.RI "Controls the default SC log behavior\&. "
.ti -1c
.RI "void \fBsc_set_abort_handler\fP (\fBsc_abort_handler_t\fP abort_handler)"
.br
.RI "Set the default SC abort behavior\&. "
.ti -1c
.RI "void \fBsc_log\fP (const char *filename, int lineno, int package, int category, int priority, const char *msg)"
.br
.RI "The central log function to be called by all packages\&. "
.ti -1c
.RI "void \fBsc_logf\fP (const char *filename, int lineno, int package, int category, int priority, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBsc_logv\fP (const char *filename, int lineno, int package, int category, int priority, const char *fmt, va_list ap)"
.br
.ti -1c
.RI "void \fBsc_log_indent_push_count\fP (int package, int count)"
.br
.RI "Add spaces to the start of a package's default log format\&. "
.ti -1c
.RI "void \fBsc_log_indent_pop_count\fP (int package, int count)"
.br
.RI "Remove spaces from the start of a package's default log format\&. "
.ti -1c
.RI "void \fBsc_log_indent_push\fP (void)"
.br
.RI "Add one space to the start of sc's default log format\&. "
.ti -1c
.RI "void \fBsc_log_indent_pop\fP (void)"
.br
.RI "Remove one space from the start of a sc's default log format\&. "
.ti -1c
.RI "void \fBsc_abort\fP (void)"
.br
.RI "Print a stack trace, call the abort handler and then call abort ()\&. "
.ti -1c
.RI "void \fBsc_abort_verbose\fP (const char *filename, int lineno, const char *msg)"
.br
.RI "Print a message to stderr and then call sc_abort ()\&. "
.ti -1c
.RI "void \fBsc_abort_verbosef\fP (const char *filename, int lineno, const char *fmt,\&.\&.\&.)"
.br
.RI "Print a message to stderr and then call sc_abort ()\&. "
.ti -1c
.RI "void \fBsc_abort_verbosev\fP (const char *filename, int lineno, const char *fmt, va_list ap)"
.br
.RI "Print a message to stderr and then call sc_abort ()\&. "
.ti -1c
.RI "void \fBsc_abort_collective\fP (const char *msg)"
.br
.RI "Collective abort where only root prints a message\&. "
.ti -1c
.RI "int \fBsc_package_register\fP (sc_log_handler_t log_handler, int log_threshold, const char *name, const char *full)"
.br
.RI "Register a software package with SC\&. "
.ti -1c
.RI "int \fBsc_package_is_registered\fP (int package_id)"
.br
.RI "Query whether an identifier matches a registered package\&. "
.ti -1c
.RI "void \fBsc_package_lock\fP (int package_id)"
.br
.RI "Acquire a pthread mutex lock\&. "
.ti -1c
.RI "void \fBsc_package_unlock\fP (int package_id)"
.br
.RI "Release a pthread mutex lock\&. "
.ti -1c
.RI "void \fBsc_package_set_verbosity\fP (int package_id, int log_priority)"
.br
.RI "Set the logging verbosity of a registered package\&. "
.ti -1c
.RI "void \fBsc_package_set_abort_alloc_mismatch\fP (int package_id, int set_abort)"
.br
.RI "Set the unregister behavior of \fBsc_package_unregister()\fP\&. "
.ti -1c
.RI "void \fBsc_package_unregister\fP (int package_id)"
.br
.RI "Unregister a software package with SC\&. "
.ti -1c
.RI "void \fBsc_package_print_summary\fP (int log_priority)"
.br
.RI "Print a summary of all packages registered with SC\&. "
.ti -1c
.RI "void \fBsc_init\fP (\fBsc_MPI_Comm\fP mpicomm, int catch_signals, int print_backtrace, sc_log_handler_t log_handler, int log_threshold)"
.br
.RI "Sets the global program identifier (e\&.g\&. "
.ti -1c
.RI "int \fBsc_is_initialized\fP (void)"
.br
.RI "Return whether SC has been initialized or not\&. "
.ti -1c
.RI "int \fBsc_get_package_id\fP (void)"
.br
.RI "Query SC's own package identity\&. "
.ti -1c
.RI "void \fBsc_finalize\fP (void)"
.br
.RI "Unregisters all packages, runs the memory check, removes the signal handlers and resets sc_identifier and sc_root_*\&. "
.ti -1c
.RI "int \fBsc_finalize_noabort\fP (void)"
.br
.RI "Unregisters all packages, runs the memory check, removes the signal handlers and resets sc_identifier and sc_root_*\&. "
.ti -1c
.RI "int \fBsc_is_root\fP (void)"
.br
.RI "Identify the root process\&. "
.ti -1c
.RI "void \fBsc_strcopy\fP (char *dest, size_t size, const char *src)"
.br
.RI "Provide a string copy function\&. "
.ti -1c
.RI "void \fBsc_snprintf\fP (char *str, size_t size, const char *format,\&.\&.\&.)"
.br
.RI "Wrap the system snprintf function, allowing for truncation\&. "
.ti -1c
.RI "const char * \fBsc_version\fP (void)"
.br
.RI "Return the full version of libsc\&. "
.ti -1c
.RI "int \fBsc_version_major\fP (void)"
.br
.RI "Return the major version of libsc\&. "
.ti -1c
.RI "int \fBsc_version_minor\fP (void)"
.br
.RI "Return the minor version of libsc\&. "
.ti -1c
.RI "int \fBsc_is_littleendian\fP (void)"
.br
.RI "Perform a runtime check for the integer endian convention\&. "
.ti -1c
.RI "int \fBsc_have_zlib\fP (void)"
.br
.RI "Return a boolean indicating whether zlib has been configured\&. "
.ti -1c
.RI "int \fBsc_have_json\fP (void)"
.br
.RI "Return whether we have found a JSON library at configure time\&. "
.ti -1c
.RI "void \fBsc_sleep\fP (unsigned milliseconds)"
.br
.RI "Portable function to sleep a prescribed amount of milliseconds\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBsc_log2_lookup_table\fP [256]"
.br
.RI "Lookup table to provide fast base-2 logarithm of integers\&. "
.ti -1c
.RI "int \fBsc_package_id\fP"
.br
.RI "libsc allows for multiple packages to use their own log priorities etc\&. "
.ti -1c
.RI "FILE * \fBsc_trace_file\fP"
.br
.RI "Optional trace file for logging (see \fBsc_init\fP)\&. "
.ti -1c
.RI "int \fBsc_trace_prio\fP"
.br
.RI "Optional minimum log priority for messages that go into the trace file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Support for process management (memory allocation, logging, etc\&.) 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SC_ALLOC_ZERO(t, n)"
\fBValue:\fP
.PP
.nf
                                               (t *) sc_calloc (sc_package_id, \
                                               (size_t) (n), sizeof(t))
.fi
.SS "#define SC_BZERO(p, n)   ((void) memset ((p), 0, (n) * sizeof (*(p))))"

.PP
Sets n elements of a memory range to zero\&. Assumes the pointer p is of the correct type\&. 
.SS "#define SC_GEN_LOG(package, category, priority, s)"
\fBValue:\fP
.PP
.nf
  ((priority) < SC_LP_THRESHOLD ? (void) 0 :                            \
   sc_log (__FILE__, __LINE__, (package), (category), (priority), (s)))
.fi
.SS "#define SC_GEN_LOGF(package, category, priority, fmt,  \&.\&.\&.)"
\fBValue:\fP
.PP
.nf
  ((priority) < SC_LP_THRESHOLD ? (void) 0 :                            \
   sc_logf (__FILE__, __LINE__, (package), (category), (priority),      \
            (fmt), __VA_ARGS__))
.fi
.SS "#define SC_LOG2_16(x)"
\fBValue:\fP
.PP
.nf
                       (((x) > 0xff) ?                                   \
                       (SC_LOG2_8 ((x) >> 8) + 8) : SC_LOG2_8 (x))
.fi
.SS "#define SC_LOG2_32(x)"
\fBValue:\fP
.PP
.nf
                       (((x) > 0xffff) ?                                 \
                       (SC_LOG2_16 ((x) >> 16)) + 16 : SC_LOG2_16 (x))
.fi
.SS "#define SC_LOG2_64(x)"
\fBValue:\fP
.PP
.nf
                       (((x) > 0xffffffffLL) ?                           \
                       (SC_LOG2_32 ((x) >> 32)) + 32 : SC_LOG2_32 (x))
.fi
.SS "#define SC_REALLOC(p, t, n)"
\fBValue:\fP
.PP
.nf
                                             (t *) sc_realloc (sc_package_id,          \
                                             (p), (n) * sizeof(t))
.fi
.SH "Function Documentation"
.PP 
.SS "int sc_atoi (const char * nptr)"

.PP
Safe version of the standard library atoi (3) function\&. 
.PP
\fBParameters\fP
.RS 4
\fInptr\fP NUL-terminated string\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Converted integer value\&. 0 if no valid number\&. INT_MAX on overflow, INT_MIN on underflow\&. 
.RE
.PP

.SS "long sc_atol (const char * nptr)"

.PP
Safe version of the standard library atol (3) function\&. 
.PP
\fBParameters\fP
.RS 4
\fInptr\fP NUL-terminated string\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Converted long value\&. 0 if no valid number\&. LONG_MAX on overflow, LONG_MIN on underflow\&. 
.RE
.PP

.SS "void sc_finalize (void)"

.PP
Unregisters all packages, runs the memory check, removes the signal handlers and resets sc_identifier and sc_root_*\&. This function aborts on any inconsistency found unless the global variable default_abort_mismatch is false\&. Function is optional if memory cleanliness is no concern\&. This function does not require sc_init to be called first\&. In any case it makes \fBsc_is_initialized\fP return false\&. 
.PP
\fBExamples\fP
.in +1c
\fBoptions\&.c\fP\&.
.SS "int sc_finalize_noabort (void)"

.PP
Unregisters all packages, runs the memory check, removes the signal handlers and resets sc_identifier and sc_root_*\&. This function never aborts but returns the number of errors encountered\&. Function is optional if memory cleanliness is no concern\&. This function does not require sc_init to be called first\&. In any case it makes \fBsc_is_initialized\fP return false\&. 
.PP
\fBReturns\fP
.RS 4
0 when everything is consistent, nonzero otherwise\&. 
.RE
.PP

.SS "int sc_get_package_id (void)"

.PP
Query SC's own package identity\&. 
.PP
\fBReturns\fP
.RS 4
This is -1 before \fBsc_init\fP has been called and a proper package identifier (>= 0) afterwards\&. After \fBsc_finalize\fP the identifier resets to -1\&. 
.RE
.PP
\fBNote\fP
.RS 4
This routine is not thread-safe\&. 
.RE
.PP

.SS "int sc_have_json (void)"

.PP
Return whether we have found a JSON library at configure time\&. 
.PP
\fBReturns\fP
.RS 4
True if and only if SC_HAVE_JSON is defined\&. 
.RE
.PP

.SS "int sc_have_zlib (void)"

.PP
Return a boolean indicating whether zlib has been configured\&. 
.PP
\fBReturns\fP
.RS 4
True if zlib including adler32_combine (3) has been found on running configure or respectively on calling cmake\&. 
.RE
.PP

.SS "void sc_init (\fBsc_MPI_Comm\fP mpicomm, int catch_signals, int print_backtrace, sc_log_handler_t log_handler, int log_threshold)"

.PP
Sets the global program identifier (e\&.g\&. the MPI rank) and some flags\&. This function is optional\&. This function must only be called before additional threads are created\&. If this function is not called or called with log_handler == NULL, the default SC log handler will be used\&. If this function is not called or called with log_threshold == SC_LP_DEFAULT, the default SC log threshold will be used\&. The default SC log settings can be changed with sc_set_log_defaults ()\&. 
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP MPI communicator, can be sc_MPI_COMM_NULL\&. If sc_MPI_COMM_NULL, the identifier is set to -1\&. Otherwise, sc_MPI_Init must have been called\&. Effectively, we just query size and rank\&. 
.br
\fIcatch_signals\fP If true, signals INT and SEGV are caught\&. 
.br
\fIprint_backtrace\fP If true, sc_abort prints a backtrace\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBoptions\&.c\fP\&.
.SS "int sc_is_initialized (void)"

.PP
Return whether SC has been initialized or not\&. 
.PP
\fBReturns\fP
.RS 4
True if libsc has been initialized with a call to \fBsc_init\fP and false otherwise\&. After \fBsc_finalize\fP the result resets to false\&. 
.RE
.PP
\fBNote\fP
.RS 4
This routine is not thread-safe\&. 
.RE
.PP

.SS "int sc_is_littleendian (void)"

.PP
Perform a runtime check for the integer endian convention\&. 
.PP
\fBReturns\fP
.RS 4
True if byte order is little endian, false otherwise\&. 
.RE
.PP

.SS "int sc_is_root (void)"

.PP
Identify the root process\&. Only meaningful between sc_init and sc_finalize and with a communicator that is not sc_MPI_COMM_NULL (otherwise always true)\&.
.PP
\fBReturns\fP
.RS 4
Return true for the root process and false otherwise\&. 
.RE
.PP

.SS "void sc_log (const char * filename, int lineno, int package, int category, int priority, const char * msg)"

.PP
The central log function to be called by all packages\&. Dispatches the log calls by package and filters by category and priority\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage\fP Must be a registered package id or -1\&. 
.br
\fIcategory\fP Must be SC_LC_NORMAL or SC_LC_GLOBAL\&. 
.br
\fIpriority\fP Must be > SC_LP_ALWAYS and < SC_LP_SILENT\&. 
.RE
.PP

.SS "int sc_package_is_registered (int package_id)"

.PP
Query whether an identifier matches a registered package\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Only a non-negative id can be registered\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if and only if the package id is non-negative and package is registered\&. 
.RE
.PP

.SS "void sc_package_lock (int package_id)"

.PP
Acquire a pthread mutex lock\&. If configured without --enable-pthread, this function does nothing\&. This function must be followed with a matching \fBsc_package_unlock\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Either -1 for an undefined package or an id returned from \fBsc_package_register\fP\&. Depending on the value, the appropriate mutex is chosen\&. Thus, we may overlap locking calls with distinct package_id\&. 
.RE
.PP

.SS "void sc_package_print_summary (int log_priority)"

.PP
Print a summary of all packages registered with SC\&. Uses the SC_LC_GLOBAL log category which by default only prints on rank 0\&. 
.PP
\fBParameters\fP
.RS 4
\fIlog_priority\fP Priority passed to sc log functions\&. 
.RE
.PP

.SS "int sc_package_register (sc_log_handler_t log_handler, int log_threshold, const char * name, const char * full)"

.PP
Register a software package with SC\&. This function must only be called before additional threads are created\&. The logging parameters are as in sc_set_log_defaults\&. 
.PP
\fBReturns\fP
.RS 4
Returns a unique package id\&. 
.RE
.PP

.SS "void sc_package_set_abort_alloc_mismatch (int package_id, int set_abort)"

.PP
Set the unregister behavior of \fBsc_package_unregister()\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Must be -1 for the default package or the identifier of a registered package\&. 
.br
\fIset_abort\fP True if \fBsc_package_unregister()\fP should abort if the number of allocs does not match the number of frees; false otherwise\&. 
.RE
.PP

.SS "void sc_package_set_verbosity (int package_id, int log_priority)"

.PP
Set the logging verbosity of a registered package\&. This can be called at any point in the program, any number of times\&. It can only lower the verbosity at and below the value of SC_LP_THRESHOLD\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Must be a registered package identifier\&. 
.RE
.PP

.SS "void sc_package_unlock (int package_id)"

.PP
Release a pthread mutex lock\&. If configured without --enable-pthread, this function does nothing\&. This function must be follow a matching \fBsc_package_lock\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Either -1 for an undefined package or an id returned from \fBsc_package_register\fP\&. Depending on the value, the appropriate mutex is chosen\&. Thus, we may overlap locking calls with distinct package_id\&. 
.RE
.PP

.SS "void sc_package_unregister (int package_id)"

.PP
Unregister a software package with SC\&. This function must only be called after additional threads are finished\&. 
.SS "void sc_set_abort_handler (\fBsc_abort_handler_t\fP abort_handler)"

.PP
Set the default SC abort behavior\&. 
.PP
\fBParameters\fP
.RS 4
\fIabort_handler\fP Set default SC above handler (NULL selects builtin)\&. If it returns, we abort (2) then\&. 
.RE
.PP

.SS "void sc_set_log_defaults (FILE * log_stream, sc_log_handler_t log_handler, int log_threshold)"

.PP
Controls the default SC log behavior\&. 
.PP
\fBParameters\fP
.RS 4
\fIlog_stream\fP Set stream to use by sc_logf (or NULL for stdout)\&. 
.br
\fIlog_handler\fP Set default SC log handler (NULL selects builtin)\&. 
.br
\fIlog_threshold\fP Set default SC log threshold (or SC_LP_DEFAULT)\&. May be SC_LP_ALWAYS or SC_LP_SILENT\&. 
.RE
.PP

.SS "void sc_sleep (unsigned milliseconds)"

.PP
Portable function to sleep a prescribed amount of milliseconds\&. 
.PP
\fBParameters\fP
.RS 4
\fImilliseconds\fP The number of milliseconds to sleep\&. 
.RE
.PP

.SS "void sc_snprintf (char * str, size_t size, const char * format,  \&.\&.\&.)"

.PP
Wrap the system snprintf function, allowing for truncation\&. The snprintf function may truncate the string written to the specified length\&. In some cases, compilers warn when this may occur\&. Here this is permitted behavior and we avoid the warning\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP Buffer of length at least \fIsize\fP\&. On output, not touched if NULL or \fIsize\fP == 0\&. Otherwise, '' on snprintf error or the proper result\&. The proper result is padded on the right with '\\0' if the allocation length of the string that is defined by \fIformat\fP is shorter than \fIsize\fP\&. 
.br
\fIsize\fP Allocation length of \fIstr\fP\&. 
.br
\fIformat\fP Format string as in man (3) snprintf\&. 
.RE
.PP

.SS "void sc_strcopy (char * dest, size_t size, const char * src)"

.PP
Provide a string copy function\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP Buffer of length at least \fIsize\fP\&. On output, not touched if NULL or \fIsize\fP == 0\&. Otherwise, \fIsrc\fP is copied to \fIdest\fP and \fIdest\fP is padded with '\\0' from the right if strlen (src) < size - 1\&. 
.br
\fIsize\fP Allocation length of \fIdest\fP\&. 
.br
\fIsrc\fP Null-terminated string\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Equivalent to \fBsc_snprintf\fP (dest, size, '%s', src)\&. 
.RE
.PP

.SS "const char* sc_version (void)"

.PP
Return the full version of libsc\&. 
.PP
\fBReturns\fP
.RS 4
Return the version of libsc using the format \fCVERSION_MAJOR\&.VERSION_MINOR\&.VERSION_POINT\fP, where \fCVERSION_POINT\fP can contain dots and characters, e\&.g\&. to indicate the additional number of commits and a git commit hash\&. 
.RE
.PP

.SS "int sc_version_major (void)"

.PP
Return the major version of libsc\&. 
.PP
\fBReturns\fP
.RS 4
Return the major version of libsc\&. 
.RE
.PP

.SS "int sc_version_minor (void)"

.PP
Return the minor version of libsc\&. 
.PP
\fBReturns\fP
.RS 4
Return the minor version of libsc\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "int sc_package_id\fC [extern]\fP"

.PP
libsc allows for multiple packages to use their own log priorities etc\&. This is the package id for core sc functions, which is meant to be read only\&. It starts out with a value of -1, which is fine by itself\&. It is set to a non-negative value by the (optional) \fBsc_init\fP\&. 
.PP
\fBExamples\fP
.in +1c
\fBoptions\&.c\fP\&.
.SS "FILE* sc_trace_file\fC [extern]\fP"

.PP
Optional trace file for logging (see \fBsc_init\fP)\&. Initialized to NULL\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
