.TH "src/sc3_mpi_types.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc3_mpi_types.h \- We provide MPI replacement data types for configuring without MPI\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc_config\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSC3_MPI_ERRORS_RETURN\fP   NULL"
.br
.RI "Wrap the parameter to return on MPI errors\&. "
.ti -1c
.RI "#define \fBSC3_MPI_MAX_ERROR_STRING\fP   BUFSIZ"
.br
.RI "Create a wrapped version of the maximum error string length\&. "
.ti -1c
.RI "#define \fBSC3_MPI_COMM_NULL\fP   ((\fBsc3_MPI_Comm_t\fP) NULL)"
.br
.RI "Wrapped invalid MPI communicator\&. "
.ti -1c
.RI "#define \fBSC3_MPI_COMM_WORLD\fP   ((\fBsc3_MPI_Comm_t\fP) 0x40)"
.br
.RI "Without --enable-mpi, a communicator of size 1 and rank 0\&. "
.ti -1c
.RI "#define \fBSC3_MPI_COMM_SELF\fP   ((\fBsc3_MPI_Comm_t\fP) 0x80)"
.br
.RI "Without --enable-mpi, a communicator of size 1 and rank 0\&. "
.ti -1c
.RI "#define \fBSC3_MPI_INFO_NULL\fP   ((\fBsc3_MPI_Info_t\fP) NULL)"
.br
.RI "Wrapped invalid MPI info object\&. "
.ti -1c
.RI "#define \fBSC3_MPI_WIN_NULL\fP   ((\fBsc3_MPI_Win_t\fP) NULL)"
.br
.RI "Invalid MPI 3 window object\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct sc3_MPI_Errhandler * \fBsc3_MPI_Errhandler_t\fP"
.br
.RI "Wrapped MPI error handler object\&. "
.ti -1c
.RI "typedef struct sc3_MPI_Comm * \fBsc3_MPI_Comm_t\fP"
.br
.RI "Wrapped MPI communicator\&. "
.ti -1c
.RI "typedef struct sc3_MPI_Info * \fBsc3_MPI_Info_t\fP"
.br
.RI "Wrapped MPI info object\&. "
.ti -1c
.RI "typedef enum \fBsc3_MPI_Datatype\fP \fBsc3_MPI_Datatype_t\fP"
.br
.RI "We wrap the MPI datatypes we use\&. "
.ti -1c
.RI "typedef enum \fBsc3_MPI_Op\fP \fBsc3_MPI_Op_t\fP"
.br
.RI "We wrap the MPI operation types we use\&. "
.ti -1c
.RI "typedef enum \fBsc3_MPI_Errorcode\fP \fBsc3_MPI_Errorcode_t\fP"
.br
.RI "We wrap some MPI error codes and the I/O error classes\&. "
.ti -1c
.RI "typedef enum \fBsc3_MPI_Enum\fP \fBsc3_MPI_Enum_t\fP"
.br
.RI "We need several parameters to MPI functions\&. "
.ti -1c
.RI "typedef enum \fBsc3_MPI_Comm_type\fP \fBsc3_MPI_Comm_type_t\fP"
.br
.RI "We wrap MPI 3 shared memory communicators\&. "
.ti -1c
.RI "typedef struct sc3_MPI_Win * \fBsc3_MPI_Win_t\fP"
.br
.RI "We wrap the MPI 3 window object\&. "
.ti -1c
.RI "typedef long \fBsc3_MPI_Aint_t\fP"
.br
.RI "We wrap the MPI address integer type\&. "
.ti -1c
.RI "typedef enum \fBsc3_MPI_Win_mode\fP \fBsc3_MPI_Win_mode_t\fP"
.br
.RI "Wrap MPI 3 window lock modes\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsc3_MPI_Datatype\fP { \fBSC3_MPI_DATATYPE_NULL\fP = 0, \fBSC3_MPI_BYTE\fP, \fBSC3_MPI_INT\fP, \fBSC3_MPI_2INT\fP, \fBSC3_MPI_UNSIGNED\fP, \fBSC3_MPI_LONG\fP, \fBSC3_MPI_LONG_LONG\fP, \fBSC3_MPI_FLOAT\fP, \fBSC3_MPI_DOUBLE\fP, \fBSC3_MPI_DOUBLE_INT\fP }"
.br
.RI "We wrap the MPI datatypes we use\&. "
.ti -1c
.RI "enum \fBsc3_MPI_Op\fP { \fBSC3_MPI_OP_NULL\fP = 0, \fBSC3_MPI_MIN\fP, \fBSC3_MPI_MAX\fP, \fBSC3_MPI_MINLOC\fP, \fBSC3_MPI_MAXLOC\fP, \fBSC3_MPI_LOR\fP, \fBSC3_MPI_LAND\fP, \fBSC3_MPI_LXOR\fP, \fBSC3_MPI_BOR\fP, \fBSC3_MPI_BAND\fP, \fBSC3_MPI_BXOR\fP, \fBSC3_MPI_REPLACE\fP, \fBSC3_MPI_SUM\fP, \fBSC3_MPI_PROD\fP }"
.br
.RI "We wrap the MPI operation types we use\&. "
.ti -1c
.RI "enum \fBsc3_MPI_Errorcode\fP { \fBSC3_MPI_SUCCESS\fP = 0, \fBSC3_MPI_ERR_ARG\fP = 14000, \fBSC3_MPI_ERR_COUNT\fP, \fBSC3_MPI_ERR_UNKNOWN\fP, \fBSC3_MPI_ERR_OTHER\fP, \fBSC3_MPI_ERR_NO_MEM\fP, \fBSC3_MPI_ERR_FILE\fP, \fBSC3_MPI_ERR_NOT_SAME\fP, \fBSC3_MPI_ERR_AMODE\fP, \fBSC3_MPI_ERR_UNSUPPORTED_DATAREP\fP, \fBSC3_MPI_ERR_UNSUPPORTED_OPERATION\fP, \fBSC3_MPI_ERR_NO_SUCH_FILE\fP, \fBSC3_MPI_ERR_FILE_EXISTS\fP, \fBSC3_MPI_ERR_BAD_FILE\fP, \fBSC3_MPI_ERR_ACCESS\fP, \fBSC3_MPI_ERR_NO_SPACE\fP, \fBSC3_MPI_ERR_QUOTA\fP, \fBSC3_MPI_ERR_READ_ONLY\fP, \fBSC3_MPI_ERR_FILE_IN_USE\fP, \fBSC3_MPI_ERR_DUP_DATAREP\fP, \fBSC3_MPI_ERR_CONVERSION\fP, \fBSC3_MPI_ERR_IO\fP, \fBSC3_MPI_ERR_LASTCODE\fP }"
.br
.RI "We wrap some MPI error codes and the I/O error classes\&. "
.ti -1c
.RI "enum \fBsc3_MPI_Enum\fP { \fBSC3_MPI_UNDEFINED\fP = 0x11 }"
.br
.RI "We need several parameters to MPI functions\&. "
.ti -1c
.RI "enum \fBsc3_MPI_Comm_type\fP { \fBSC3_MPI_COMM_TYPE_SHARED\fP = 0x12 }"
.br
.RI "We wrap MPI 3 shared memory communicators\&. "
.ti -1c
.RI "enum \fBsc3_MPI_Win_mode\fP { \fBSC3_MPI_LOCK_SHARED\fP = 0x13, \fBSC3_MPI_LOCK_EXCLUSIVE\fP = 0x14, \fBSC3_MPI_MODE_NOCHECK\fP = 0x15 }"
.br
.RI "Wrap MPI 3 window lock modes\&. "
.in -1c
.SH "Detailed Description"
.PP 
We provide MPI replacement data types for configuring without MPI\&. 

Included from both \fBsc_mpi\&.h\fP and the future \fCsc3_mpi\&.h\fP\&.
.PP
This header file provides definitions of MPI data types for the case that no MPI implementation is available or MPI is not configured\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef struct sc3_MPI_Comm* \fBsc3_MPI_Comm_t\fP"

.PP
Wrapped MPI communicator\&. Without --enable-mpi, it reports size 1 and rank 0\&. 
.SS "typedef enum \fBsc3_MPI_Comm_type\fP \fBsc3_MPI_Comm_type_t\fP"

.PP
We wrap MPI 3 shared memory communicators\&. Without --enable-mpi, they have size 1 and rank 0\&. 
.SS "typedef struct sc3_MPI_Info* \fBsc3_MPI_Info_t\fP"

.PP
Wrapped MPI info object\&. Without --enable-mpi, the set and get methods do nothing\&. 
.SS "typedef struct sc3_MPI_Win* \fBsc3_MPI_Win_t\fP"

.PP
We wrap the MPI 3 window object\&. With MPI 3 windows available, the functionality is unchanged\&. Without MPI 3 available, it is primitive but allows basic use\&.
.PP
When created with a communicator size of one, or when \fCconfigure\fP does not define SC_ENABLE_MPIWINSHARED, we use the wrapper and do not go through MPI\&. When shared windows are not supported and the communicator has size > 1, the wrapper cannot query or lock and unlock the window of remote ranks\&. Any such attempt will result in a fatal error returned\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBsc3_MPI_Comm_type\fP"

.PP
We wrap MPI 3 shared memory communicators\&. Without --enable-mpi, they have size 1 and rank 0\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC3_MPI_COMM_TYPE_SHARED \fP\fP
MPI 3 shared window communicator\&. 
.SS "enum \fBsc3_MPI_Datatype\fP"

.PP
We wrap the MPI datatypes we use\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC3_MPI_DATATYPE_NULL \fP\fP
The invalid data type\&. 
.TP
\fB\fISC3_MPI_BYTE \fP\fP
Same as in original MPI\&. 1 byte\&. It is preferred over MPI_CHAR since the latter may amount to multiple bytes for wide chars\&. 
.TP
\fB\fISC3_MPI_INT \fP\fP
Same as in original MPI\&. System int type\&. 
.TP
\fB\fISC3_MPI_2INT \fP\fP
Same as in original MPI\&. Two system ints\&. 
.TP
\fB\fISC3_MPI_UNSIGNED \fP\fP
Same as in original MPI\&. System unsigned\&. 
.TP
\fB\fISC3_MPI_LONG \fP\fP
Same as in original MPI\&. System long type\&. 
.TP
\fB\fISC3_MPI_LONG_LONG \fP\fP
Same as in original MPI\&. System long long\&. 
.TP
\fB\fISC3_MPI_FLOAT \fP\fP
Same as in original MPI\&. 
.TP
\fB\fISC3_MPI_DOUBLE \fP\fP
Same as in original MPI\&. 
.TP
\fB\fISC3_MPI_DOUBLE_INT \fP\fP
Same as in original MPI\&. Double and int\&. 
.SS "enum \fBsc3_MPI_Enum\fP"

.PP
We need several parameters to MPI functions\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC3_MPI_UNDEFINED \fP\fP
An input parameter with undefined value\&. 
.SS "enum \fBsc3_MPI_Errorcode\fP"

.PP
We wrap some MPI error codes and the I/O error classes\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC3_MPI_SUCCESS \fP\fP
An MPI function has exited successfully\&. 
.TP
\fB\fISC3_MPI_ERR_ARG \fP\fP
An MPI function encountered invalid arguments\&. 
.TP
\fB\fISC3_MPI_ERR_COUNT \fP\fP
An MPI function encountered an invalid count argument\&. 
.TP
\fB\fISC3_MPI_ERR_UNKNOWN \fP\fP
An MPI function has produced an unknown error\&. 
.TP
\fB\fISC3_MPI_ERR_OTHER \fP\fP
An MPI function has produced some known error\&. 
.TP
\fB\fISC3_MPI_ERR_NO_MEM \fP\fP
An MPI function ran out of memory\&. 
.SS "enum \fBsc3_MPI_Op\fP"

.PP
We wrap the MPI operation types we use\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC3_MPI_OP_NULL \fP\fP
The invalid operation\&. 
.TP
\fB\fISC3_MPI_MIN \fP\fP
The usual minimum reduction operation\&. 
.TP
\fB\fISC3_MPI_MAX \fP\fP
The usual maximum reduction operation\&. 
.TP
\fB\fISC3_MPI_MINLOC \fP\fP
Find minimum value and its rank\&. 
.TP
\fB\fISC3_MPI_MAXLOC \fP\fP
Find maximum value and its rank\&. 
.TP
\fB\fISC3_MPI_LOR \fP\fP
Logical OR\&. 
.TP
\fB\fISC3_MPI_LAND \fP\fP
Logical AND\&. 
.TP
\fB\fISC3_MPI_LXOR \fP\fP
Logical XOR\&. 
.TP
\fB\fISC3_MPI_BOR \fP\fP
Bitwise OR\&. 
.TP
\fB\fISC3_MPI_BAND \fP\fP
Bitwise AND\&. 
.TP
\fB\fISC3_MPI_BXOR \fP\fP
Bitwise XOR\&. 
.TP
\fB\fISC3_MPI_REPLACE \fP\fP
The MPI replace operation\&. 
.TP
\fB\fISC3_MPI_SUM \fP\fP
The usual sum reduction operation\&. 
.TP
\fB\fISC3_MPI_PROD \fP\fP
The usual product reduction operation\&. 
.SS "enum \fBsc3_MPI_Win_mode\fP"

.PP
Wrap MPI 3 window lock modes\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC3_MPI_LOCK_SHARED \fP\fP
Shared (multiple readers) lock\&. 
.TP
\fB\fISC3_MPI_LOCK_EXCLUSIVE \fP\fP
Exclusive (usually reader) lock\&. 
.TP
\fB\fISC3_MPI_MODE_NOCHECK \fP\fP
Option to \fCMPI_Win_lock\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
