.TH "sc_amr_control" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_amr_control
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const double * \fBerrors\fP"
.br
.ti -1c
.RI "\fBsc_statinfo_t\fP \fBestats\fP"
.br
.ti -1c
.RI "\fBsc_MPI_Comm\fP \fBmpicomm\fP"
.br
.ti -1c
.RI "long \fBnum_procs_long\fP"
.br
.ti -1c
.RI "long \fBnum_total_elements\fP"
.br
.ti -1c
.RI "double \fBcoarsen_threshold\fP"
.br
.ti -1c
.RI "double \fBrefine_threshold\fP"
.br
.ti -1c
.RI "long \fBnum_total_coarsen\fP"
.br
.ti -1c
.RI "long \fBnum_total_refine\fP"
.br
.ti -1c
.RI "long \fBnum_total_estimated\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
