.TH "sc_containers" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_containers \- Containers
.PP
 \- The library provides dynamic containers such as lists, arrays, and hash tables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsc_containers\&.h\fP"
.br
.RI "Dynamic containers such as lists, arrays, and hash tables\&. "
.ti -1c
.RI "file \fBsc_keyvalue\&.h\fP"
.br
.RI "This file provides a lookup structure for key-value pairs\&. "
.ti -1c
.RI "file \fBsc_string\&.h\fP"
.br
.RI "This file declares a simple string object that can be appended to\&. "
.in -1c
.SH "Detailed Description"
.PP 
The library provides dynamic containers such as lists, arrays, and hash tables\&. 

The \fBsc_array\fP structure serves as lightweight resizable array\&. Based on this array, we implement the \fBsc_hash\fP table and the \fBsc_hash_array\fP\&. We also add a string implementation in \fBsc_string\&.h\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
