.TH "src/sc_containers.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_containers.h \- Dynamic containers such as lists, arrays, and hash tables\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsc_array\fP"
.br
.RI "The \fBsc_array\fP object provides a dynamic array of equal-size elements\&. "
.ti -1c
.RI "struct \fBsc_mstamp\fP"
.br
.RI "A data container to create memory items of the same size\&. "
.ti -1c
.RI "struct \fBsc_mempool\fP"
.br
.RI "The \fBsc_mempool\fP object provides a large pool of equal-size elements\&. "
.ti -1c
.RI "struct \fBsc_link\fP"
.br
.RI "The \fBsc_link\fP structure is one link of a linked list\&. "
.ti -1c
.RI "struct \fBsc_list\fP"
.br
.RI "The \fBsc_list\fP object provides a linked list\&. "
.ti -1c
.RI "struct \fBsc_hash\fP"
.br
.RI "The \fBsc_hash\fP implements a hash table\&. "
.ti -1c
.RI "struct \fBsc_hash_array\fP"
.br
.RI "The \fBsc_hash_array\fP implements an array backed up by a hash table\&. "
.ti -1c
.RI "struct \fBsc_recycle_array\fP"
.br
.RI "The \fBsc_recycle_array\fP object provides an array of slots that can be reused\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBsc_hash_rot\fP(x,  k)   (((x) << (k)) | ((x) >> (32 \- (k))))"
.br
.RI "Bijective bit rotation as building block for hash functions\&. "
.ti -1c
.RI "#define \fBsc_hash_mix\fP(a,  b,  c)"
.br
.RI "Integer bit mixer as building block for hash functions\&. "
.ti -1c
.RI "#define \fBsc_hash_final\fP(a,  b,  c)"
.br
.RI "Integer bit operations as building block for hash functions\&. "
.ti -1c
.RI "#define \fBSC_ARRAY_IS_OWNER\fP(a)   ((a)\->byte_alloc >= 0)"
.br
.RI "Test whether the sc_array_t owns its \fIarray\fP\&. "
.ti -1c
.RI "#define \fBSC_ARRAY_BYTE_ALLOC\fP(a)"
.br
.RI "Return the allocated size of the array\&. "
.ti -1c
.RI "#define \fBsc_array_new_size\fP(s,  c)   (\fBsc_array_new_count\fP ((s), (c)))"
.br
.RI "Deprecated: use \fBsc_array_new_count\fP\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int(* \fBsc_hash_function_t\fP) (const void *v, const void *u)"
.br
.RI "Function to compute a hash value of an object\&. "
.ti -1c
.RI "typedef int(* \fBsc_equal_function_t\fP) (const void *v1, const void *v2, const void *u)"
.br
.RI "Function to check equality of two objects\&. "
.ti -1c
.RI "typedef int(* \fBsc_hash_foreach_t\fP) (void **v, const void *u)"
.br
.RI "Function to call on every data item of a hash table or hash array\&. "
.ti -1c
.RI "typedef struct \fBsc_array\fP \fBsc_array_t\fP"
.br
.RI "The \fBsc_array\fP object provides a dynamic array of equal-size elements\&. "
.ti -1c
.RI "typedef size_t(* \fBsc_array_type_t\fP) (\fBsc_array_t\fP *array, size_t index, void *data)"
.br
.RI "Function to determine the enumerable type of an object in an array\&. "
.ti -1c
.RI "typedef struct \fBsc_mstamp\fP \fBsc_mstamp_t\fP"
.br
.RI "A data container to create memory items of the same size\&. "
.ti -1c
.RI "typedef struct \fBsc_mempool\fP \fBsc_mempool_t\fP"
.br
.RI "The \fBsc_mempool\fP object provides a large pool of equal-size elements\&. "
.ti -1c
.RI "typedef struct \fBsc_link\fP \fBsc_link_t\fP"
.br
.RI "The \fBsc_link\fP structure is one link of a linked list\&. "
.ti -1c
.RI "typedef struct \fBsc_list\fP \fBsc_list_t\fP"
.br
.RI "The \fBsc_list\fP object provides a linked list\&. "
.ti -1c
.RI "typedef struct \fBsc_hash\fP \fBsc_hash_t\fP"
.br
.RI "The \fBsc_hash\fP implements a hash table\&. "
.ti -1c
.RI "typedef struct sc_hash_array_data \fBsc_hash_array_data_t\fP"
.br
.RI "Internal context structure for \fBsc_hash_array\fP\&. "
.ti -1c
.RI "typedef struct \fBsc_hash_array\fP \fBsc_hash_array_t\fP"
.br
.RI "The \fBsc_hash_array\fP implements an array backed up by a hash table\&. "
.ti -1c
.RI "typedef struct \fBsc_recycle_array\fP \fBsc_recycle_array_t\fP"
.br
.RI "The \fBsc_recycle_array\fP object provides an array of slots that can be reused\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBsc_array_memory_used\fP (\fBsc_array_t\fP *array, int is_dynamic)"
.br
.RI "Calculate the memory used by an array\&. "
.ti -1c
.RI "\fBsc_array_t\fP * \fBsc_array_new\fP (size_t elem_size)"
.br
.RI "Creates a new array structure with 0 elements\&. "
.ti -1c
.RI "\fBsc_array_t\fP * \fBsc_array_new_count\fP (size_t elem_size, size_t elem_count)"
.br
.RI "Creates a new array structure with a given length (number of elements)\&. "
.ti -1c
.RI "\fBsc_array_t\fP * \fBsc_array_new_view\fP (\fBsc_array_t\fP *array, size_t offset, size_t length)"
.br
.RI "Creates a new view of an existing sc_array_t\&. "
.ti -1c
.RI "\fBsc_array_t\fP * \fBsc_array_new_data\fP (void *base, size_t elem_size, size_t elem_count)"
.br
.RI "Creates a new view of an existing plain C array\&. "
.ti -1c
.RI "void \fBsc_array_destroy\fP (\fBsc_array_t\fP *array)"
.br
.RI "Destroys an array structure\&. "
.ti -1c
.RI "void \fBsc_array_destroy_null\fP (\fBsc_array_t\fP **parray)"
.br
.RI "Destroys an array structure and sets the pointer to NULL\&. "
.ti -1c
.RI "void \fBsc_array_init\fP (\fBsc_array_t\fP *array, size_t elem_size)"
.br
.RI "Initializes an already allocated (or static) array structure\&. "
.ti -1c
.RI "void \fBsc_array_init_size\fP (\fBsc_array_t\fP *array, size_t elem_size, size_t elem_count)"
.br
.RI "Initializes an already allocated (or static) array structure and allocates a given number of elements\&. "
.ti -1c
.RI "void \fBsc_array_init_count\fP (\fBsc_array_t\fP *array, size_t elem_size, size_t elem_count)"
.br
.RI "Initializes an already allocated (or static) array structure and allocates a given number of elements\&. "
.ti -1c
.RI "void \fBsc_array_init_view\fP (\fBsc_array_t\fP *view, \fBsc_array_t\fP *array, size_t offset, size_t length)"
.br
.RI "Initializes an already allocated (or static) view from existing sc_array_t\&. "
.ti -1c
.RI "void \fBsc_array_init_reshape\fP (\fBsc_array_t\fP *view, \fBsc_array_t\fP *array, size_t elem_size, size_t elem_count)"
.br
.RI "Initialize an already allocated (or static) view from existing sc_array_t\&. "
.ti -1c
.RI "void \fBsc_array_init_data\fP (\fBsc_array_t\fP *view, void *base, size_t elem_size, size_t elem_count)"
.br
.RI "Initializes an already allocated (or static) view from given plain C data\&. "
.ti -1c
.RI "void \fBsc_array_memset\fP (\fBsc_array_t\fP *array, int c)"
.br
.RI "Run memset on the array storage\&. "
.ti -1c
.RI "void \fBsc_array_reset\fP (\fBsc_array_t\fP *array)"
.br
.RI "Sets the array count to zero and frees all elements\&. "
.ti -1c
.RI "void \fBsc_array_truncate\fP (\fBsc_array_t\fP *array)"
.br
.RI "Sets the array count to zero, but does not free elements\&. "
.ti -1c
.RI "void \fBsc_array_rewind\fP (\fBsc_array_t\fP *array, size_t new_count)"
.br
.RI "Shorten an array without reallocating it\&. "
.ti -1c
.RI "void \fBsc_array_resize\fP (\fBsc_array_t\fP *array, size_t new_count)"
.br
.RI "Sets the element count to new_count\&. "
.ti -1c
.RI "void \fBsc_array_copy\fP (\fBsc_array_t\fP *dest, \fBsc_array_t\fP *src)"
.br
.RI "Copy the contents of one array into another\&. "
.ti -1c
.RI "void \fBsc_array_copy_into\fP (\fBsc_array_t\fP *dest, size_t dest_offset, \fBsc_array_t\fP *src)"
.br
.RI "Copy the contents of one array into some portion of another\&. "
.ti -1c
.RI "void \fBsc_array_move_part\fP (\fBsc_array_t\fP *dest, size_t dest_offset, \fBsc_array_t\fP *src, size_t src_offset, size_t count)"
.br
.RI "Copy part of one array into another using memmove (3)\&. "
.ti -1c
.RI "void \fBsc_array_sort\fP (\fBsc_array_t\fP *array, int(*compar)(const void *, const void *))"
.br
.RI "Sorts the array in ascending order wrt\&. "
.ti -1c
.RI "int \fBsc_array_is_sorted\fP (\fBsc_array_t\fP *array, int(*compar)(const void *, const void *))"
.br
.RI "Check whether the array is sorted wrt\&. "
.ti -1c
.RI "int \fBsc_array_is_equal\fP (\fBsc_array_t\fP *array, \fBsc_array_t\fP *other)"
.br
.RI "Check whether two arrays have equal size, count, and content\&. "
.ti -1c
.RI "void \fBsc_array_uniq\fP (\fBsc_array_t\fP *array, int(*compar)(const void *, const void *))"
.br
.RI "Removed duplicate entries from a sorted array\&. "
.ti -1c
.RI "ssize_t \fBsc_array_bsearch\fP (\fBsc_array_t\fP *array, const void *key, int(*compar)(const void *, const void *))"
.br
.RI "Performs a binary search on an array\&. "
.ti -1c
.RI "void \fBsc_array_split\fP (\fBsc_array_t\fP *array, \fBsc_array_t\fP *offsets, size_t num_types, \fBsc_array_type_t\fP type_fn, void *data)"
.br
.RI "Compute the offsets of groups of enumerable types in an array\&. "
.ti -1c
.RI "int \fBsc_array_is_permutation\fP (\fBsc_array_t\fP *array)"
.br
.RI "Determine whether \fIarray\fP is an array of size_t's whose entries include every integer 0 <= i < array->elem_count\&. "
.ti -1c
.RI "void \fBsc_array_permute\fP (\fBsc_array_t\fP *array, \fBsc_array_t\fP *newindices, int keepperm)"
.br
.RI "Given permutation \fInewindices\fP, permute \fIarray\fP in place\&. "
.ti -1c
.RI "unsigned int \fBsc_array_checksum\fP (\fBsc_array_t\fP *array)"
.br
.RI "Computes the adler32 checksum of array data (see zlib documentation)\&. "
.ti -1c
.RI "size_t \fBsc_array_pqueue_add\fP (\fBsc_array_t\fP *array, void *temp, int(*compar)(const void *, const void *))"
.br
.RI "Adds an element to a priority queue\&. "
.ti -1c
.RI "size_t \fBsc_array_pqueue_pop\fP (\fBsc_array_t\fP *array, void *result, int(*compar)(const void *, const void *))"
.br
.RI "Pops the smallest element from a priority queue\&. "
.ti -1c
.RI "void \fBsc_mstamp_init\fP (\fBsc_mstamp_t\fP *mst, size_t stamp_unit, size_t elem_size)"
.br
.RI "Initialize a memory stamp container\&. "
.ti -1c
.RI "void \fBsc_mstamp_reset\fP (\fBsc_mstamp_t\fP *mst)"
.br
.RI "Free all memory in a stamp structure and all items previously returned\&. "
.ti -1c
.RI "void \fBsc_mstamp_truncate\fP (\fBsc_mstamp_t\fP *mst)"
.br
.RI "Free all memory in a stamp structure and initialize it anew\&. "
.ti -1c
.RI "void * \fBsc_mstamp_alloc\fP (\fBsc_mstamp_t\fP *mst)"
.br
.RI "Return a new item\&. "
.ti -1c
.RI "size_t \fBsc_mstamp_memory_used\fP (\fBsc_mstamp_t\fP *mst)"
.br
.RI "Return memory size in bytes of all data allocated in the container\&. "
.ti -1c
.RI "size_t \fBsc_mempool_memory_used\fP (\fBsc_mempool_t\fP *mempool)"
.br
.RI "Calculate the memory used by a memory pool\&. "
.ti -1c
.RI "\fBsc_mempool_t\fP * \fBsc_mempool_new\fP (size_t elem_size)"
.br
.RI "Creates a new mempool structure with the zero_and_persist option off\&. "
.ti -1c
.RI "\fBsc_mempool_t\fP * \fBsc_mempool_new_zero_and_persist\fP (size_t elem_size)"
.br
.RI "Creates a new mempool structure with the zero_and_persist option on\&. "
.ti -1c
.RI "void \fBsc_mempool_init\fP (\fBsc_mempool_t\fP *mempool, size_t elem_size)"
.br
.RI "Same as sc_mempool_new, but for an already allocated object\&. "
.ti -1c
.RI "void \fBsc_mempool_destroy\fP (\fBsc_mempool_t\fP *mempool)"
.br
.RI "Destroy a mempool structure\&. "
.ti -1c
.RI "void \fBsc_mempool_destroy_null\fP (\fBsc_mempool_t\fP **pmempool)"
.br
.RI "Destroy a mempool structure\&. "
.ti -1c
.RI "void \fBsc_mempool_reset\fP (\fBsc_mempool_t\fP *mempool)"
.br
.RI "Same as sc_mempool_destroy, but does not free the pointer\&. "
.ti -1c
.RI "void \fBsc_mempool_truncate\fP (\fBsc_mempool_t\fP *mempool)"
.br
.RI "Invalidates all previously returned pointers, resets count to 0\&. "
.ti -1c
.RI "size_t \fBsc_list_memory_used\fP (\fBsc_list_t\fP *list, int is_dynamic)"
.br
.RI "Calculate the total memory used by a list\&. "
.ti -1c
.RI "\fBsc_list_t\fP * \fBsc_list_new\fP (\fBsc_mempool_t\fP *allocator)"
.br
.RI "Allocate a new, empty linked list\&. "
.ti -1c
.RI "void \fBsc_list_destroy\fP (\fBsc_list_t\fP *list)"
.br
.RI "Destroy a linked list structure in O(N)\&. "
.ti -1c
.RI "void \fBsc_list_init\fP (\fBsc_list_t\fP *list, \fBsc_mempool_t\fP *allocator)"
.br
.RI "Initialize a list object with an external link allocator\&. "
.ti -1c
.RI "void \fBsc_list_reset\fP (\fBsc_list_t\fP *list)"
.br
.RI "Remove all elements from a list in O(N)\&. "
.ti -1c
.RI "void \fBsc_list_unlink\fP (\fBsc_list_t\fP *list)"
.br
.RI "Unlink all list elements without returning them to the mempool\&. "
.ti -1c
.RI "\fBsc_link_t\fP * \fBsc_list_prepend\fP (\fBsc_list_t\fP *list, void *data)"
.br
.RI "Insert a list element at the beginning of the list\&. "
.ti -1c
.RI "\fBsc_link_t\fP * \fBsc_list_append\fP (\fBsc_list_t\fP *list, void *data)"
.br
.RI "Insert a list element at the end of the list\&. "
.ti -1c
.RI "\fBsc_link_t\fP * \fBsc_list_insert\fP (\fBsc_list_t\fP *list, \fBsc_link_t\fP *pred, void *data)"
.br
.RI "Insert an element after a given list position\&. "
.ti -1c
.RI "void * \fBsc_list_remove\fP (\fBsc_list_t\fP *list, \fBsc_link_t\fP *pred)"
.br
.RI "Remove an element after a given list position\&. "
.ti -1c
.RI "void * \fBsc_list_pop\fP (\fBsc_list_t\fP *list)"
.br
.RI "Remove an element from the front of the list\&. "
.ti -1c
.RI "unsigned int \fBsc_hash_function_string\fP (const void *s, const void *u)"
.br
.RI "Compute a hash value from a null-terminated string\&. "
.ti -1c
.RI "size_t \fBsc_hash_memory_used\fP (\fBsc_hash_t\fP *hash)"
.br
.RI "Calculate the memory used by a hash table\&. "
.ti -1c
.RI "\fBsc_hash_t\fP * \fBsc_hash_new\fP (\fBsc_hash_function_t\fP hash_fn, \fBsc_equal_function_t\fP equal_fn, void *user_data, \fBsc_mempool_t\fP *allocator)"
.br
.RI "Create a new hash table\&. "
.ti -1c
.RI "void \fBsc_hash_destroy\fP (\fBsc_hash_t\fP *hash)"
.br
.RI "Destroy a hash table\&. "
.ti -1c
.RI "void \fBsc_hash_destroy_null\fP (\fBsc_hash_t\fP **phash)"
.br
.RI "Destroy a hash table and set its pointer to NULL\&. "
.ti -1c
.RI "void \fBsc_hash_truncate\fP (\fBsc_hash_t\fP *hash)"
.br
.RI "Remove all entries from a hash table in O(N)\&. "
.ti -1c
.RI "void \fBsc_hash_unlink\fP (\fBsc_hash_t\fP *hash)"
.br
.RI "Unlink all hash elements without returning them to the mempool\&. "
.ti -1c
.RI "void \fBsc_hash_unlink_destroy\fP (\fBsc_hash_t\fP *hash)"
.br
.RI "Same effect as unlink and destroy, but in O(1)\&. "
.ti -1c
.RI "int \fBsc_hash_lookup\fP (\fBsc_hash_t\fP *hash, void *v, void ***found)"
.br
.RI "Check if an object is contained in the hash table\&. "
.ti -1c
.RI "int \fBsc_hash_insert_unique\fP (\fBsc_hash_t\fP *hash, void *v, void ***found)"
.br
.RI "Insert an object into a hash table if it is not contained already\&. "
.ti -1c
.RI "int \fBsc_hash_remove\fP (\fBsc_hash_t\fP *hash, void *v, void **found)"
.br
.RI "Remove an object from a hash table\&. "
.ti -1c
.RI "void \fBsc_hash_foreach\fP (\fBsc_hash_t\fP *hash, \fBsc_hash_foreach_t\fP fn)"
.br
.RI "Invoke a callback for every member of the hash table\&. "
.ti -1c
.RI "void \fBsc_hash_print_statistics\fP (int package_id, int log_priority, \fBsc_hash_t\fP *hash)"
.br
.RI "Compute and print statistical information about the occupancy\&. "
.ti -1c
.RI "size_t \fBsc_hash_array_memory_used\fP (\fBsc_hash_array_t\fP *ha)"
.br
.RI "Calculate the memory used by a hash array\&. "
.ti -1c
.RI "\fBsc_hash_array_t\fP * \fBsc_hash_array_new\fP (size_t elem_size, \fBsc_hash_function_t\fP hash_fn, \fBsc_equal_function_t\fP equal_fn, void *user_data)"
.br
.RI "Create a new hash array\&. "
.ti -1c
.RI "void \fBsc_hash_array_destroy\fP (\fBsc_hash_array_t\fP *hash_array)"
.br
.RI "Destroy a hash array\&. "
.ti -1c
.RI "int \fBsc_hash_array_is_valid\fP (\fBsc_hash_array_t\fP *hash_array)"
.br
.RI "Check the internal consistency of a hash array\&. "
.ti -1c
.RI "void \fBsc_hash_array_truncate\fP (\fBsc_hash_array_t\fP *hash_array)"
.br
.RI "Remove all elements from the hash array\&. "
.ti -1c
.RI "int \fBsc_hash_array_lookup\fP (\fBsc_hash_array_t\fP *hash_array, void *v, size_t *position)"
.br
.RI "Check if an object is contained in a hash array\&. "
.ti -1c
.RI "void * \fBsc_hash_array_insert_unique\fP (\fBsc_hash_array_t\fP *hash_array, void *v, size_t *position)"
.br
.RI "Insert an object into a hash array if it is not contained already\&. "
.ti -1c
.RI "void \fBsc_hash_array_foreach\fP (\fBsc_hash_array_t\fP *hash_array, \fBsc_hash_foreach_t\fP fn)"
.br
.RI "Invoke a callback for every member of the hash array\&. "
.ti -1c
.RI "void \fBsc_hash_array_rip\fP (\fBsc_hash_array_t\fP *hash_array, \fBsc_array_t\fP *rip)"
.br
.RI "Extract the array data from a hash array and destroy everything else\&. "
.ti -1c
.RI "void \fBsc_recycle_array_init\fP (\fBsc_recycle_array_t\fP *rec_array, size_t elem_size)"
.br
.RI "Initialize a recycle array\&. "
.ti -1c
.RI "void \fBsc_recycle_array_reset\fP (\fBsc_recycle_array_t\fP *rec_array)"
.br
.RI "Reset a recycle array\&. "
.ti -1c
.RI "void * \fBsc_recycle_array_insert\fP (\fBsc_recycle_array_t\fP *rec_array, size_t *position)"
.br
.RI "Insert an object into the recycle array\&. "
.ti -1c
.RI "void * \fBsc_recycle_array_remove\fP (\fBsc_recycle_array_t\fP *rec_array, size_t position)"
.br
.RI "Remove an object from the recycle array\&. "
.in -1c
.SH "Detailed Description"
.PP 
Dynamic containers such as lists, arrays, and hash tables\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SC_ARRAY_BYTE_ALLOC(a)"
\fBValue:\fP
.PP
.nf
         ((size_t) \
         (SC_ARRAY_IS_OWNER (a) ? (a)->byte_alloc : -((a)->byte_alloc + 1)))
.fi
.PP
Return the allocated size of the array\&. 
.SS "#define sc_hash_final(a, b, c)"
\fBValue:\fP
.PP
.nf
                              ((void)                            \
                              (c ^= b, c -= sc_hash_rot(b,14),  \
                               a ^= c, a -= sc_hash_rot(c,11),  \
                               b ^= a, b -= sc_hash_rot(a,25),  \
                               c ^= b, c -= sc_hash_rot(b,16),  \
                               a ^= c, a -= sc_hash_rot(c, 4),  \
                               b ^= a, b -= sc_hash_rot(a,14),  \
                               c ^= b, c -= sc_hash_rot(b,24)))
.fi
.PP
Integer bit operations as building block for hash functions\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP First in/out value (32-bit integer)\&. 
.br
\fIb\fP Second in/out value (32-bit integer)\&. 
.br
\fIc\fP Third in/out value (32-bit integer)\&. 
.RE
.PP

.SS "#define sc_hash_mix(a, b, c)"
\fBValue:\fP
.PP
.nf
                            ((void)                                      \
                            (a -= c, a ^= sc_hash_rot(c, 4), c += b,    \
                             b -= a, b ^= sc_hash_rot(a, 6), a += c,    \
                             c -= b, c ^= sc_hash_rot(b, 8), b += a,    \
                             a -= c, a ^= sc_hash_rot(c,16), c += b,    \
                             b -= a, b ^= sc_hash_rot(a,19), a += c,    \
                             c -= b, c ^= sc_hash_rot(b, 4), b += a))
.fi
.PP
Integer bit mixer as building block for hash functions\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP First in/out value (32-bit integer)\&. 
.br
\fIb\fP Second in/out value (32-bit integer)\&. 
.br
\fIc\fP Third in/out value (32-bit integer)\&. 
.RE
.PP

.SS "#define sc_hash_rot(x, k)   (((x) << (k)) | ((x) >> (32 \- (k))))"

.PP
Bijective bit rotation as building block for hash functions\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Input value (32-bit integer)\&. 
.br
\fIk\fP Bit shift amount (<= 32)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Circular shifted integer\&. 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBsc_array\fP \fBsc_array_t\fP"

.PP
The \fBsc_array\fP object provides a dynamic array of equal-size elements\&. Elements are accessed by their 0-based index\&. Their address may change\&. The number of elements (== elem_count) of the array can be changed by \fBsc_array_resize\fP and \fBsc_array_rewind\fP\&. Elements can be sorted with \fBsc_array_sort\fP\&. If the array is sorted, it can be searched with \fBsc_array_bsearch\fP\&. A priority queue is implemented with pqueue_add and pqueue_pop (untested)\&. 
.SS "typedef size_t(* sc_array_type_t) (\fBsc_array_t\fP *array, size_t index, void *data)"

.PP
Function to determine the enumerable type of an object in an array\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array containing the object\&. 
.br
\fIindex\fP The location of the object\&. 
.br
\fIdata\fP Arbitrary user data\&. 
.RE
.PP

.SS "typedef int(* sc_equal_function_t) (const void *v1, const void *v2, const void *u)"

.PP
Function to check equality of two objects\&. 
.PP
\fBParameters\fP
.RS 4
\fIv1\fP Pointer to first object checked for equality\&. 
.br
\fIv2\fP Pointer to second object checked for equality\&. 
.br
\fIu\fP Arbitrary user data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
False if *v1 is unequal *v2 and true otherwise\&. 
.RE
.PP

.SS "typedef struct \fBsc_hash_array\fP \fBsc_hash_array_t\fP"

.PP
The \fBsc_hash_array\fP implements an array backed up by a hash table\&. This enables O(1) access for array elements\&. 
.SS "typedef int(* sc_hash_foreach_t) (void **v, const void *u)"

.PP
Function to call on every data item of a hash table or hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIv\fP The address of the pointer to the current object\&. 
.br
\fIu\fP Arbitrary user data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return true if the traversal should continue, false to stop\&. 
.RE
.PP

.SS "typedef unsigned int(* sc_hash_function_t) (const void *v, const void *u)"

.PP
Function to compute a hash value of an object\&. 
.PP
\fBParameters\fP
.RS 4
\fIv\fP The object to hash\&. 
.br
\fIu\fP Arbitrary user data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns an unsigned integer\&. 
.RE
.PP

.SS "typedef struct \fBsc_hash\fP \fBsc_hash_t\fP"

.PP
The \fBsc_hash\fP implements a hash table\&. It uses an array which has linked lists as elements\&. 
.SS "typedef struct \fBsc_mempool\fP \fBsc_mempool_t\fP"

.PP
The \fBsc_mempool\fP object provides a large pool of equal-size elements\&. The pool grows dynamically for element allocation\&. Elements are referenced by their address which never changes\&. Elements can be freed (that is, returned to the pool) and are transparently reused\&. If the zero_and_persist option is selected, new elements are initialized to all zeros on creation, and the contents of an element are not touched between freeing and re-returning it\&. 
.SS "typedef struct \fBsc_mstamp\fP \fBsc_mstamp_t\fP"

.PP
A data container to create memory items of the same size\&. Allocations are bundled so it's fast for small memory sizes\&. The items created will remain valid until the container is destroyed\&. There is no option to return an item to the container\&. See \fBsc_mempool_t\fP for that purpose\&. 
.SS "typedef struct \fBsc_recycle_array\fP \fBsc_recycle_array_t\fP"

.PP
The \fBsc_recycle_array\fP object provides an array of slots that can be reused\&. It keeps a list of free slots in the array which will be used for insertion while available\&. Otherwise, the array is grown\&. 
.SH "Function Documentation"
.PP 
.SS "ssize_t sc_array_bsearch (\fBsc_array_t\fP * array, const void * key, int(*)(const void *, const void *) compar)"

.PP
Performs a binary search on an array\&. The array must be sorted\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP A sorted array to search in\&. 
.br
\fIkey\fP An element to be searched for\&. 
.br
\fIcompar\fP The comparison function to be used\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the index into array for the item found, or -1\&. 
.RE
.PP

.SS "unsigned int sc_array_checksum (\fBsc_array_t\fP * array)"

.PP
Computes the adler32 checksum of array data (see zlib documentation)\&. This is a faster checksum than crc32, and it works with zeros as data\&. 
.SS "void sc_array_copy (\fBsc_array_t\fP * dest, \fBsc_array_t\fP * src)"

.PP
Copy the contents of one array into another\&. Both arrays must have equal element sizes\&. The source array may be a view\&. We use memcpy (3): If the two arrays overlap, results are undefined\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP Array (not a view) will be resized and get new data\&. 
.br
\fIsrc\fP Array used as source of new data, will not be changed\&. 
.RE
.PP

.SS "void sc_array_copy_into (\fBsc_array_t\fP * dest, size_t dest_offset, \fBsc_array_t\fP * src)"

.PP
Copy the contents of one array into some portion of another\&. Both arrays must have equal element sizes\&. Either array may be a view\&. The destination array must be large enough\&. We use memcpy (3): If the two arrays overlap, results are undefined\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP Array will be written into\&. Its element count must be at least \fBdest_offset\fP + \fBsrc->elem_count\fP\&. 
.br
\fIdest_offset\fP First index in \fBdest\fP array to be overwritten\&. As every index, it refers to elements, not bytes\&. 
.br
\fIsrc\fP Array used as source of new data, will not be changed\&. 
.RE
.PP

.SS "void sc_array_destroy (\fBsc_array_t\fP * array)"

.PP
Destroys an array structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The array to be destroyed\&. 
.RE
.PP

.SS "void sc_array_destroy_null (\fBsc_array_t\fP ** parray)"

.PP
Destroys an array structure and sets the pointer to NULL\&. 
.PP
\fBParameters\fP
.RS 4
\fIparray\fP Pointer to address of array to be destroyed\&. On output, *parray is NULL\&. 
.RE
.PP

.SS "void sc_array_init (\fBsc_array_t\fP * array, size_t elem_size)"

.PP
Initializes an already allocated (or static) array structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array structure to be initialized\&. 
.br
\fIelem_size\fP Size of one array element in bytes\&. 
.RE
.PP

.SS "void sc_array_init_count (\fBsc_array_t\fP * array, size_t elem_size, size_t elem_count)"

.PP
Initializes an already allocated (or static) array structure and allocates a given number of elements\&. This function supersedes \fBsc_array_init_size\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array structure to be initialized\&. 
.br
\fIelem_size\fP Size of one array element in bytes\&. 
.br
\fIelem_count\fP Number of initial array elements\&. 
.RE
.PP

.SS "void sc_array_init_data (\fBsc_array_t\fP * view, void * base, size_t elem_size, size_t elem_count)"

.PP
Initializes an already allocated (or static) view from given plain C data\&. The array view returned does not require sc_array_reset (doesn't hurt though)\&. 
.PP
\fBParameters\fP
.RS 4
\fIview\fP Array structure to be initialized\&. 
.br
\fIbase\fP The data must not be moved while view is alive\&. 
.br
\fIelem_size\fP Size of one array element in bytes\&. 
.br
\fIelem_count\fP The length of the view in element units\&. The view cannot be resized to exceed this length\&. It is not necessary to call sc_array_reset later\&. 
.RE
.PP

.SS "void sc_array_init_reshape (\fBsc_array_t\fP * view, \fBsc_array_t\fP * array, size_t elem_size, size_t elem_count)"

.PP
Initialize an already allocated (or static) view from existing sc_array_t\&. The total data size of the view is the same, but size and count may differ\&. The array view returned does not require sc_array_reset (doesn't hurt though)\&. 
.PP
\fBParameters\fP
.RS 4
\fIview\fP Array structure to be initialized\&. 
.br
\fIarray\fP The array must not be resized while view is alive\&. 
.br
\fIelem_size\fP Size of one array element of the view in bytes\&. The product of size and count of \fIarray\fP must be the same as \fIelem_size\fP * \fIelem_count\fP\&. 
.br
\fIelem_count\fP The length of the view in element units\&. The view cannot be resized to exceed this length\&. It is not necessary to call sc_array_reset later\&. 
.RE
.PP

.SS "void sc_array_init_size (\fBsc_array_t\fP * array, size_t elem_size, size_t elem_count)"

.PP
Initializes an already allocated (or static) array structure and allocates a given number of elements\&. Deprecated: use \fBsc_array_init_count\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array structure to be initialized\&. 
.br
\fIelem_size\fP Size of one array element in bytes\&. 
.br
\fIelem_count\fP Number of initial array elements\&. 
.RE
.PP

.SS "void sc_array_init_view (\fBsc_array_t\fP * view, \fBsc_array_t\fP * array, size_t offset, size_t length)"

.PP
Initializes an already allocated (or static) view from existing sc_array_t\&. The array view returned does not require sc_array_reset (doesn't hurt though)\&. 
.PP
\fBParameters\fP
.RS 4
\fIview\fP Array structure to be initialized\&. 
.br
\fIarray\fP The array must not be resized while view is alive\&. 
.br
\fIoffset\fP The offset of the viewed section in element units\&. This offset cannot be changed until the view is reset\&. 
.br
\fIlength\fP The length of the view in element units\&. The view cannot be resized to exceed this length\&. It is not necessary to call sc_array_reset later\&. 
.RE
.PP

.SS "int sc_array_is_equal (\fBsc_array_t\fP * array, \fBsc_array_t\fP * other)"

.PP
Check whether two arrays have equal size, count, and content\&. Either array may be a view\&. Both arrays will not be changed\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP One array to be compared\&. 
.br
\fIother\fP A second array to be compared\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if array and other are equal, false otherwise\&. 
.RE
.PP

.SS "int sc_array_is_permutation (\fBsc_array_t\fP * array)"

.PP
Determine whether \fIarray\fP is an array of size_t's whose entries include every integer 0 <= i < array->elem_count\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP An array\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns 1 if array contains size_t elements whose entries include every integer 0 <= i < \fIarray->elem_count\fP, 0 otherwise\&. 
.RE
.PP

.SS "int sc_array_is_sorted (\fBsc_array_t\fP * array, int(*)(const void *, const void *) compar)"

.PP
Check whether the array is sorted wrt\&. the comparison function\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The array to check\&. 
.br
\fIcompar\fP The comparison function to be used\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if array is sorted, false otherwise\&. 
.RE
.PP

.SS "size_t sc_array_memory_used (\fBsc_array_t\fP * array, int is_dynamic)"

.PP
Calculate the memory used by an array\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The array\&. 
.br
\fIis_dynamic\fP True if created with sc_array_new, false if initialized with sc_array_init 
.RE
.PP
\fBReturns\fP
.RS 4
Memory used in bytes\&. 
.RE
.PP

.SS "void sc_array_memset (\fBsc_array_t\fP * array, int c)"

.PP
Run memset on the array storage\&. We pass the character to memset unchanged\&. Thus, care must be taken when setting values below -1 or above 127, just as with standard memset (3)\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP This array's storage will be overwritten\&. 
.br
\fIc\fP Character to overwrite every byte with\&. 
.RE
.PP

.SS "void sc_array_move_part (\fBsc_array_t\fP * dest, size_t dest_offset, \fBsc_array_t\fP * src, size_t src_offset, size_t count)"

.PP
Copy part of one array into another using memmove (3)\&. Both arrays must have equal element sizes\&. Either array may be a view\&. The destination array must be large enough\&. We use memmove (3): The two arrays may overlap\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP Array will be written into\&. Its element count must be at least \fBdest_offset\fP + \fBcount\fP\&. 
.br
\fIdest_offset\fP First index in \fBdest\fP array to be overwritten\&. As every index, it refers to elements, not bytes\&. 
.br
\fIsrc\fP Array will be read from\&. Its element count must be at least \fBsrc_offset\fP + \fBcount\fP\&. 
.br
\fIsrc_offset\fP First index in \fBsrc\fP array to be used\&. As every index, it refers to elements, not bytes\&. 
.br
\fIcount\fP Number of entries copied\&. 
.RE
.PP

.SS "\fBsc_array_t\fP* sc_array_new (size_t elem_size)"

.PP
Creates a new array structure with 0 elements\&. 
.PP
\fBParameters\fP
.RS 4
\fIelem_size\fP Size of one array element in bytes\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return an allocated array of zero length\&. 
.RE
.PP

.SS "\fBsc_array_t\fP* sc_array_new_count (size_t elem_size, size_t elem_count)"

.PP
Creates a new array structure with a given length (number of elements)\&. 
.PP
\fBParameters\fP
.RS 4
\fIelem_size\fP Size of one array element in bytes\&. 
.br
\fIelem_count\fP Initial number of array elements\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return an allocated array with allocated but uninitialized elements\&. 
.RE
.PP

.SS "\fBsc_array_t\fP* sc_array_new_data (void * base, size_t elem_size, size_t elem_count)"

.PP
Creates a new view of an existing plain C array\&. 
.PP
\fBParameters\fP
.RS 4
\fIbase\fP The data must not be moved while view is alive\&. 
.br
\fIelem_size\fP Size of one array element in bytes\&. 
.br
\fIelem_count\fP The length of the view in element units\&. The view cannot be resized to exceed this length\&. 
.RE
.PP

.SS "\fBsc_array_t\fP* sc_array_new_view (\fBsc_array_t\fP * array, size_t offset, size_t length)"

.PP
Creates a new view of an existing sc_array_t\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The array must not be resized while view is alive\&. 
.br
\fIoffset\fP The offset of the viewed section in element units\&. This offset cannot be changed until the view is reset\&. 
.br
\fIlength\fP The length of the viewed section in element units\&. The view cannot be resized to exceed this length\&. 
.RE
.PP

.SS "void sc_array_permute (\fBsc_array_t\fP * array, \fBsc_array_t\fP * newindices, int keepperm)"

.PP
Given permutation \fInewindices\fP, permute \fIarray\fP in place\&. The data that on input is contained in \fIarray\fP[i] will be contained in \fIarray\fP[newindices[i]] on output\&. The entries of newindices will be altered unless \fIkeepperm\fP is true\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP An array\&. 
.br
\fInewindices\fP Permutation array (see sc_array_is_permutation)\&. 
.br
\fIkeepperm\fP If true, \fInewindices\fP will be unchanged by the algorithm; if false, \fInewindices\fP will be the identity permutation on output, but the algorithm will only use O(1) space\&. 
.RE
.PP

.SS "size_t sc_array_pqueue_add (\fBsc_array_t\fP * array, void * temp, int(*)(const void *, const void *) compar)"

.PP
Adds an element to a priority queue\&. 
.PP
\fBNote\fP
.RS 4
PQUEUE FUNCTIONS ARE UNTESTED AND CURRENTLY DISABLED\&. This function is not allowed for views\&. The priority queue is implemented as a heap in ascending order\&. A heap is a binary tree where the children are not less than their parent\&. Assumes that elements [0]\&.\&.[elem_count-2] form a valid heap\&. Then propagates [elem_count-1] upward by swapping if necessary\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Valid priority queue object\&. 
.br
\fItemp\fP Pointer to unused allocated memory of elem_size\&. 
.br
\fIcompar\fP The comparison function to be used\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the number of swap operations\&. 
.RE
.PP
\fBNote\fP
.RS 4
If the return value is zero for all elements in an array, the array is sorted linearly and unchanged\&. 
.RE
.PP

.SS "size_t sc_array_pqueue_pop (\fBsc_array_t\fP * array, void * result, int(*)(const void *, const void *) compar)"

.PP
Pops the smallest element from a priority queue\&. 
.PP
\fBNote\fP
.RS 4
PQUEUE FUNCTIONS ARE UNTESTED AND CURRENTLY DISABLED\&. This function is not allowed for views\&. This function assumes that the array forms a valid heap in ascending order\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Valid priority queue object\&. 
.br
\fIresult\fP Pointer to unused allocated memory of elem_size\&. 
.br
\fIcompar\fP The comparison function to be used\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the number of swap operations\&. 
.RE
.PP
\fBNote\fP
.RS 4
This function resizes the array to elem_count-1\&. 
.RE
.PP

.SS "void sc_array_reset (\fBsc_array_t\fP * array)"

.PP
Sets the array count to zero and frees all elements\&. This function turns a view into a newly initialized array\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array structure to be reset\&. 
.RE
.PP
\fBNote\fP
.RS 4
Calling sc_array_init, then any array operations, then sc_array_reset is memory neutral\&. As an exception, the two functions sc_array_init_view and sc_array_init_data do not require a subsequent call to sc_array_reset\&. Regardless, it is legal to call sc_array_reset anyway\&. 
.RE
.PP

.SS "void sc_array_resize (\fBsc_array_t\fP * array, size_t new_count)"

.PP
Sets the element count to new_count\&. If the array is not a view, reallocation takes place occasionally\&. If the array is a view, new_count must not be greater than the element count of the view when it was created\&. The original offset of the view cannot be changed\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The element count and address is modified\&. 
.br
\fInew_count\fP New element count of the array\&. If it is zero and the array is not a view, the effect equals \fBsc_array_reset\fP\&. 
.RE
.PP

.SS "void sc_array_rewind (\fBsc_array_t\fP * array, size_t new_count)"

.PP
Shorten an array without reallocating it\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The element count of this array is modified\&. 
.br
\fInew_count\fP Must be less or equal than the \fBarray's\fP count\&. If it is less, the number of elements in the array is reduced without reallocating memory\&. The exception is a \fBnew_count\fP of zero specified for an array that is not a view: In this case \fBsc_array_reset\fP is equivalent\&. 
.RE
.PP

.SS "void sc_array_sort (\fBsc_array_t\fP * array, int(*)(const void *, const void *) compar)"

.PP
Sorts the array in ascending order wrt\&. the comparison function\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The array to sort\&. 
.br
\fIcompar\fP The comparison function to be used\&. 
.RE
.PP

.SS "void sc_array_split (\fBsc_array_t\fP * array, \fBsc_array_t\fP * offsets, size_t num_types, \fBsc_array_type_t\fP type_fn, void * data)"

.PP
Compute the offsets of groups of enumerable types in an array\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array that is sorted in ascending order by type\&. If k indexes \fIarray\fP, then 0 <= \fItype_fn\fP (\fIarray\fP, k, \fIdata\fP) < \fInum_types\fP\&. 
.br
\fIoffsets\fP An initialized array of type size_t that is resized to \fInum_types\fP + 1 entries\&. The indices j of \fIarray\fP that contain objects of type k are \fIoffsets\fP[k] <= j < \fIoffsets\fP[k + 1]\&. If there are no objects of type k, then \fIoffsets\fP[k] = \fIoffset\fP[k + 1]\&. 
.br
\fInum_types\fP The number of possible types of objects in \fIarray\fP\&. 
.br
\fItype_fn\fP Returns the type of an object in the array\&. 
.br
\fIdata\fP Arbitrary user data passed to \fItype_fn\fP\&. 
.RE
.PP

.SS "void sc_array_truncate (\fBsc_array_t\fP * array)"

.PP
Sets the array count to zero, but does not free elements\&. Not allowed for views\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array structure to be truncated\&. 
.RE
.PP
\fBNote\fP
.RS 4
This is intended to allow an \fBsc_array\fP to be used as a reusable buffer, where the 'high water mark' of the buffer is preserved, so that O(log (max n)) reallocs occur over the life of the buffer\&. 
.RE
.PP

.SS "void sc_array_uniq (\fBsc_array_t\fP * array, int(*)(const void *, const void *) compar)"

.PP
Removed duplicate entries from a sorted array\&. This function is not allowed for views\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP The array size will be reduced as necessary\&. 
.br
\fIcompar\fP The comparison function to be used\&. 
.RE
.PP

.SS "void sc_hash_array_destroy (\fBsc_hash_array_t\fP * hash_array)"

.PP
Destroy a hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash_array\fP Valid hash array is deallocated\&. 
.RE
.PP

.SS "void sc_hash_array_foreach (\fBsc_hash_array_t\fP * hash_array, \fBsc_hash_foreach_t\fP fn)"

.PP
Invoke a callback for every member of the hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash_array\fP Valid hash array\&. 
.br
\fIfn\fP Callback executed on every hash array element\&. 
.RE
.PP

.SS "void* sc_hash_array_insert_unique (\fBsc_hash_array_t\fP * hash_array, void * v, size_t * position)"

.PP
Insert an object into a hash array if it is not contained already\&. The object is not copied into the array\&. Use the return value for that\&. New objects are guaranteed to be added at the end of the array\&.
.PP
\fBParameters\fP
.RS 4
\fIhash_array\fP Valid hash array\&. 
.br
\fIv\fP A pointer to the object\&. Used for search only\&. 
.br
\fIposition\fP If position != NULL, *position is set to the array position of the already contained, or if not present, the new object\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns NULL if the object is already contained\&. Otherwise returns its new address in the array\&. 
.RE
.PP

.SS "int sc_hash_array_is_valid (\fBsc_hash_array_t\fP * hash_array)"

.PP
Check the internal consistency of a hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash_array\fP Hash array structure is checked for validity\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if and only if \fIhash_array\fP is valid\&. 
.RE
.PP

.SS "int sc_hash_array_lookup (\fBsc_hash_array_t\fP * hash_array, void * v, size_t * position)"

.PP
Check if an object is contained in a hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash_array\fP Valid hash array\&. 
.br
\fIv\fP A pointer to the object\&. 
.br
\fIposition\fP If position != NULL, *position is set to the array position of the already contained object if found\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if object is found, false otherwise\&. 
.RE
.PP

.SS "size_t sc_hash_array_memory_used (\fBsc_hash_array_t\fP * ha)"

.PP
Calculate the memory used by a hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIha\fP The hash array\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Memory used in bytes\&. 
.RE
.PP

.SS "\fBsc_hash_array_t\fP* sc_hash_array_new (size_t elem_size, \fBsc_hash_function_t\fP hash_fn, \fBsc_equal_function_t\fP equal_fn, void * user_data)"

.PP
Create a new hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIelem_size\fP Size of one array element in bytes\&. 
.br
\fIhash_fn\fP Function to compute the hash value\&. 
.br
\fIequal_fn\fP Function to test two objects for equality\&. 
.br
\fIuser_data\fP Anonymous context data stored in the hash array\&. 
.RE
.PP

.SS "void sc_hash_array_rip (\fBsc_hash_array_t\fP * hash_array, \fBsc_array_t\fP * rip)"

.PP
Extract the array data from a hash array and destroy everything else\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash_array\fP The hash array is destroyed after extraction\&. 
.br
\fIrip\fP Array structure that will be overwritten\&. All previous array data (if any) will be leaked\&. The filled array can be freed with sc_array_reset\&. 
.RE
.PP

.SS "void sc_hash_array_truncate (\fBsc_hash_array_t\fP * hash_array)"

.PP
Remove all elements from the hash array\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash_array\fP Hash array to truncate\&. 
.RE
.PP

.SS "void sc_hash_destroy (\fBsc_hash_t\fP * hash)"

.PP
Destroy a hash table\&. If the allocator is owned, this runs in O(1), otherwise in O(N)\&. 
.PP
\fBNote\fP
.RS 4
If allocator was provided in sc_hash_new, it will not be destroyed\&. 
.RE
.PP

.SS "void sc_hash_destroy_null (\fBsc_hash_t\fP ** phash)"

.PP
Destroy a hash table and set its pointer to NULL\&. Destruction is done using \fBsc_hash_destroy\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIphash\fP Address of pointer to hash table\&. On output, pointer is NULLed\&. 
.RE
.PP

.SS "void sc_hash_foreach (\fBsc_hash_t\fP * hash, \fBsc_hash_foreach_t\fP fn)"

.PP
Invoke a callback for every member of the hash table\&. The hashing and equality functions are not called from within this function\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP Valid hash table\&. 
.br
\fIfn\fP Callback executed on every hash table element\&. 
.RE
.PP

.SS "unsigned int sc_hash_function_string (const void * s, const void * u)"

.PP
Compute a hash value from a null-terminated string\&. This hash function is NOT cryptographically safe! Use libcrypt then\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP Null-terminated string to be hashed\&. 
.br
\fIu\fP Not used\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The computed hash value as an unsigned integer\&. 
.RE
.PP

.SS "int sc_hash_insert_unique (\fBsc_hash_t\fP * hash, void * v, void *** found)"

.PP
Insert an object into a hash table if it is not contained already\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP Valid hash table\&. 
.br
\fIv\fP The object to be inserted\&. 
.br
\fIfound\fP If found != NULL, *found is set to the address of the pointer to the already contained, or if not present, the new object\&. You can assign to **found to override\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns true if object is added, false if it is already contained\&. 
.RE
.PP

.SS "int sc_hash_lookup (\fBsc_hash_t\fP * hash, void * v, void *** found)"

.PP
Check if an object is contained in the hash table\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP Valid hash table\&. 
.br
\fIv\fP The object to be looked up\&. 
.br
\fIfound\fP If found != NULL, *found is set to the address of the pointer to the already contained object if the object is found\&. You can assign to **found to override\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns true if object is found, false otherwise\&. 
.RE
.PP

.SS "size_t sc_hash_memory_used (\fBsc_hash_t\fP * hash)"

.PP
Calculate the memory used by a hash table\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP The hash table\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Memory used in bytes\&. 
.RE
.PP

.SS "\fBsc_hash_t\fP* sc_hash_new (\fBsc_hash_function_t\fP hash_fn, \fBsc_equal_function_t\fP equal_fn, void * user_data, \fBsc_mempool_t\fP * allocator)"

.PP
Create a new hash table\&. The number of hash slots is chosen dynamically\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash_fn\fP Function to compute the hash value\&. 
.br
\fIequal_fn\fP Function to test two objects for equality\&. 
.br
\fIuser_data\fP User data passed through to the hash function\&. 
.br
\fIallocator\fP Memory allocator for sc_link_t, can be NULL\&. 
.RE
.PP

.SS "void sc_hash_print_statistics (int package_id, int log_priority, \fBsc_hash_t\fP * hash)"

.PP
Compute and print statistical information about the occupancy\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Library package id for logging\&. 
.br
\fIlog_priority\fP Priority for logging; see \fBsc_log\fP\&. 
.br
\fIhash\fP Valid hash table\&. 
.RE
.PP

.SS "int sc_hash_remove (\fBsc_hash_t\fP * hash, void * v, void ** found)"

.PP
Remove an object from a hash table\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP Valid hash table\&. 
.br
\fIv\fP The object to be removed\&. 
.br
\fIfound\fP If found != NULL, *found is set to the object that is removed if that exists\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns true if object is found, false if is not contained\&. 
.RE
.PP

.SS "void sc_hash_truncate (\fBsc_hash_t\fP * hash)"

.PP
Remove all entries from a hash table in O(N)\&. If the allocator is owned, it calls sc_hash_unlink and sc_mempool_truncate\&. Otherwise, it calls sc_list_reset on every hash slot which is slower\&. 
.SS "void sc_hash_unlink (\fBsc_hash_t\fP * hash)"

.PP
Unlink all hash elements without returning them to the mempool\&. If the allocator is not owned, this runs faster than sc_hash_truncate, but is dangerous because of potential memory leaks\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP Hash structure to be unlinked\&. 
.RE
.PP

.SS "void sc_hash_unlink_destroy (\fBsc_hash_t\fP * hash)"

.PP
Same effect as unlink and destroy, but in O(1)\&. This is dangerous because of potential memory leaks\&. 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP Hash structure to be unlinked and destroyed\&. 
.RE
.PP

.SS "\fBsc_link_t\fP* sc_list_append (\fBsc_list_t\fP * list, void * data)"

.PP
Insert a list element at the end of the list\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP Valid list object\&. 
.br
\fIdata\fP A new link is created holding this data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The link that has been created for data\&. 
.RE
.PP

.SS "void sc_list_destroy (\fBsc_list_t\fP * list)"

.PP
Destroy a linked list structure in O(N)\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP All memory allocated for this list is freed\&. 
.RE
.PP
\fBNote\fP
.RS 4
If allocator was provided in sc_list_new, it will not be destroyed\&. 
.RE
.PP

.SS "void sc_list_init (\fBsc_list_t\fP * list, \fBsc_mempool_t\fP * allocator)"

.PP
Initialize a list object with an external link allocator\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP List structure to be initialized\&. 
.br
\fIallocator\fP External memory allocator for sc_link_t, which must exist already\&. 
.RE
.PP

.SS "\fBsc_link_t\fP* sc_list_insert (\fBsc_list_t\fP * list, \fBsc_link_t\fP * pred, void * data)"

.PP
Insert an element after a given list position\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP Valid list object\&. 
.br
\fIpred\fP The predecessor of the element to be inserted\&. 
.br
\fIdata\fP A new link is created holding this data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The link that has been created for data\&. 
.RE
.PP

.SS "size_t sc_list_memory_used (\fBsc_list_t\fP * list, int is_dynamic)"

.PP
Calculate the total memory used by a list\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP The list\&. 
.br
\fIis_dynamic\fP True if created with sc_list_new, false if initialized with sc_list_init 
.RE
.PP
\fBReturns\fP
.RS 4
Memory used in bytes\&. 
.RE
.PP

.SS "\fBsc_list_t\fP* sc_list_new (\fBsc_mempool_t\fP * allocator)"

.PP
Allocate a new, empty linked list\&. 
.PP
\fBParameters\fP
.RS 4
\fIallocator\fP Memory allocator for sc_link_t, can be NULL in which case an internal allocator is created\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to a newly allocated, empty list object\&. 
.RE
.PP

.SS "void* sc_list_pop (\fBsc_list_t\fP * list)"

.PP
Remove an element from the front of the list\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP Valid, non-empty list object\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the data of the removed first list element\&. 
.RE
.PP

.SS "\fBsc_link_t\fP* sc_list_prepend (\fBsc_list_t\fP * list, void * data)"

.PP
Insert a list element at the beginning of the list\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP Valid list object\&. 
.br
\fIdata\fP A new link is created holding this data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The link that has been created for data\&. 
.RE
.PP

.SS "void* sc_list_remove (\fBsc_list_t\fP * list, \fBsc_link_t\fP * pred)"

.PP
Remove an element after a given list position\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP Valid, non-empty list object\&. 
.br
\fIpred\fP The predecessor of the element to be removed\&. If \fIpred\fP == NULL, the first element is removed, which is equivalent to calling sc_list_pop (list)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The data of the removed and freed link\&. 
.RE
.PP

.SS "void sc_list_reset (\fBsc_list_t\fP * list)"

.PP
Remove all elements from a list in O(N)\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP List structure to be emptied\&. 
.RE
.PP
\fBNote\fP
.RS 4
Calling sc_list_init, then any list operations, then sc_list_reset is memory neutral\&. 
.RE
.PP

.SS "void sc_list_unlink (\fBsc_list_t\fP * list)"

.PP
Unlink all list elements without returning them to the mempool\&. This runs in O(1) but is dangerous because the link memory stays alive\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP List structure to be unlinked\&. 
.RE
.PP

.SS "void sc_mempool_destroy (\fBsc_mempool_t\fP * mempool)"

.PP
Destroy a mempool structure\&. All elements that are still in use are invalidated\&. 
.PP
\fBParameters\fP
.RS 4
\fImempool\fP Its memory is freed\&. 
.RE
.PP

.SS "void sc_mempool_destroy_null (\fBsc_mempool_t\fP ** pmempool)"

.PP
Destroy a mempool structure\&. All elements that are still in use are invalidated\&. 
.PP
\fBParameters\fP
.RS 4
\fIpmempool\fP Address of pointer to memory pool\&. Its memory is freed, pointer is NULLed\&. 
.RE
.PP

.SS "void sc_mempool_init (\fBsc_mempool_t\fP * mempool, size_t elem_size)"

.PP
Same as sc_mempool_new, but for an already allocated object\&. 
.PP
\fBParameters\fP
.RS 4
\fImempool\fP Allocated memory is overwritten and initialized\&. 
.br
\fIelem_size\fP Size of one element in bytes\&. 
.RE
.PP

.SS "size_t sc_mempool_memory_used (\fBsc_mempool_t\fP * mempool)"

.PP
Calculate the memory used by a memory pool\&. 
.PP
\fBParameters\fP
.RS 4
\fImempool\fP The memory pool\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Memory used in bytes\&. 
.RE
.PP

.SS "\fBsc_mempool_t\fP* sc_mempool_new (size_t elem_size)"

.PP
Creates a new mempool structure with the zero_and_persist option off\&. The contents of any elements returned by sc_mempool_alloc are undefined\&. 
.PP
\fBParameters\fP
.RS 4
\fIelem_size\fP Size of one element in bytes\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns an allocated and initialized memory pool\&. 
.RE
.PP

.SS "\fBsc_mempool_t\fP* sc_mempool_new_zero_and_persist (size_t elem_size)"

.PP
Creates a new mempool structure with the zero_and_persist option on\&. The memory of newly created elements is zero'd out, and the contents of an element are not touched between freeing and re-returning it\&. 
.PP
\fBParameters\fP
.RS 4
\fIelem_size\fP Size of one element in bytes\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns an allocated and initialized memory pool\&. 
.RE
.PP

.SS "void sc_mempool_reset (\fBsc_mempool_t\fP * mempool)"

.PP
Same as sc_mempool_destroy, but does not free the pointer\&. 
.PP
\fBParameters\fP
.RS 4
\fImempool\fP Valid mempool object is deallocated\&. The structure memory itself stays alive\&. 
.RE
.PP

.SS "void sc_mempool_truncate (\fBsc_mempool_t\fP * mempool)"

.PP
Invalidates all previously returned pointers, resets count to 0\&. 
.PP
\fBParameters\fP
.RS 4
\fImempool\fP Valid mempool is truncated\&. 
.RE
.PP

.SS "void* sc_mstamp_alloc (\fBsc_mstamp_t\fP * mst)"

.PP
Return a new item\&. The memory returned will stay legal until container is destroyed or truncated\&. 
.PP
\fBParameters\fP
.RS 4
\fImst\fP Properly initialized stamp container\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to an item ready to use\&. Legal until \fBsc_mstamp_reset\fP or \fBsc_mstamp_truncate\fP is called on mst\&. 
.RE
.PP

.SS "void sc_mstamp_init (\fBsc_mstamp_t\fP * mst, size_t stamp_unit, size_t elem_size)"

.PP
Initialize a memory stamp container\&. We provide allocation of fixed-size memory items without allocating new memory in every request\&. Instead we block the allocations in what we call a stamp of multiple items\&. Even if no allocations are done, the container's internal memory must be freed eventually by \fBsc_mstamp_reset\fP\&.
.PP
\fBParameters\fP
.RS 4
\fImst\fP Legal pointer to a stamp structure\&. 
.br
\fIstamp_unit\fP Size of each memory block that we allocate\&. If it is larger than the element size, we may place more than one element in it\&. Passing 0 is legal and forces stamps that hold one item each\&. 
.br
\fIelem_size\fP Size of each item\&. Passing 0 is legal\&. In that case, \fBsc_mstamp_alloc\fP returns NULL\&. 
.RE
.PP

.SS "size_t sc_mstamp_memory_used (\fBsc_mstamp_t\fP * mst)"

.PP
Return memory size in bytes of all data allocated in the container\&. 
.PP
\fBParameters\fP
.RS 4
\fImst\fP Properly initialized stamp container\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Total container memory size in bytes\&. 
.RE
.PP

.SS "void sc_mstamp_reset (\fBsc_mstamp_t\fP * mst)"

.PP
Free all memory in a stamp structure and all items previously returned\&. 
.PP
\fBParameters\fP
.RS 4
\fImst\fP Properly initialized stamp container\&. On output, the structure is undefined\&. 
.RE
.PP

.SS "void sc_mstamp_truncate (\fBsc_mstamp_t\fP * mst)"

.PP
Free all memory in a stamp structure and initialize it anew\&. Equivalent to calling \fBsc_mstamp_reset\fP followed by \fBsc_mstamp_init\fP with the same stamp_unit and elem_size\&.
.PP
\fBParameters\fP
.RS 4
\fImst\fP Properly initialized stamp container\&. On output, its elements have been freed and it is ready for further use\&. 
.RE
.PP

.SS "void sc_recycle_array_init (\fBsc_recycle_array_t\fP * rec_array, size_t elem_size)"

.PP
Initialize a recycle array\&. 
.PP
\fBParameters\fP
.RS 4
\fIrec_array\fP Uninitialized turned into a recycle array\&. 
.br
\fIelem_size\fP Size of the objects to be stored in the array\&. 
.RE
.PP

.SS "void* sc_recycle_array_insert (\fBsc_recycle_array_t\fP * rec_array, size_t * position)"

.PP
Insert an object into the recycle array\&. The object is not copied into the array\&. Use the return value for that\&.
.PP
\fBParameters\fP
.RS 4
\fIrec_array\fP Valid recycle array\&. 
.br
\fIposition\fP If position != NULL, *position is set to the array position of the inserted object\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The new address of the object in the array\&. 
.RE
.PP

.SS "void* sc_recycle_array_remove (\fBsc_recycle_array_t\fP * rec_array, size_t position)"

.PP
Remove an object from the recycle array\&. It must be valid\&.
.PP
\fBParameters\fP
.RS 4
\fIrec_array\fP Valid recycle array\&. 
.br
\fIposition\fP Index into the array for the object to remove\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the removed object\&. Will be valid as long as no other function is called on this recycle array\&. 
.RE
.PP

.SS "void sc_recycle_array_reset (\fBsc_recycle_array_t\fP * rec_array)"

.PP
Reset a recycle array\&. As with all _reset functions, calling _init, then any array operations, then _reset is memory neutral\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
