.TH "sc_flopinfo" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_flopinfo
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBseconds\fP"
.br
.ti -1c
.RI "double \fBcwtime\fP"
.br
.ti -1c
.RI "float \fBcrtime\fP"
.br
.ti -1c
.RI "float \fBcptime\fP"
.br
.ti -1c
.RI "long long \fBcflpops\fP"
.br
.ti -1c
.RI "double \fBiwtime\fP"
.br
.ti -1c
.RI "float \fBirtime\fP"
.br
.ti -1c
.RI "float \fBiptime\fP"
.br
.ti -1c
.RI "long long \fBiflpops\fP"
.br
.ti -1c
.RI "float \fBmflops\fP"
.br
.ti -1c
.RI "int \fBuse_papi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
