.TH "sc_function3_meta" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_function3_meta
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_function3_t \fBf1\fP"
.br
.ti -1c
.RI "sc_function3_t \fBf2\fP"
.br
.ti -1c
.RI "double \fBparameter2\fP"
.br
.ti -1c
.RI "sc_function3_t \fBf3\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
