.TH "sc_hash_array" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_hash_array \- The \fBsc_hash_array\fP implements an array backed up by a hash table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_containers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.RI "Context passed by the user\&. "
.ti -1c
.RI "\fBsc_array_t\fP \fBa\fP"
.br
.RI "Array storing the elements\&. "
.ti -1c
.RI "\fBsc_hash_t\fP * \fBh\fP"
.br
.RI "Hash map pointing into element array\&. "
.ti -1c
.RI "\fBsc_hash_array_data_t\fP * \fBinternal_data\fP"
.br
.RI "Private context data\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBsc_hash_array\fP implements an array backed up by a hash table\&. 

This enables O(1) access for array elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
