.TH "src/sc_keyvalue.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_keyvalue.h \- This file provides a lookup structure for key-value pairs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc_containers\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct sc_keyvalue \fBsc_keyvalue_t\fP"
.br
.RI "The key-value container is an opaque structure\&. "
.ti -1c
.RI "typedef int(* \fBsc_keyvalue_foreach_t\fP) (const char *key, const \fBsc_keyvalue_entry_type_t\fP type, void *entry, const void *u)"
.br
.RI "Function to call on every key value pair\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsc_keyvalue_entry_type_t\fP { \fBSC_KEYVALUE_ENTRY_NONE\fP = 0, \fBSC_KEYVALUE_ENTRY_INT\fP, \fBSC_KEYVALUE_ENTRY_DOUBLE\fP, \fBSC_KEYVALUE_ENTRY_STRING\fP, \fBSC_KEYVALUE_ENTRY_POINTER\fP }"
.br
.RI "The values can have different types\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsc_keyvalue_t\fP * \fBsc_keyvalue_new\fP ()"
.br
.RI "Create a new key-value container\&. "
.ti -1c
.RI "\fBsc_keyvalue_t\fP * \fBsc_keyvalue_newf\fP (int dummy,\&.\&.\&.)"
.br
.RI "Create a container and set one or more key-value pairs\&. "
.ti -1c
.RI "\fBsc_keyvalue_t\fP * \fBsc_keyvalue_newv\fP (va_list ap)"
.br
.RI "Create a container and set one or more key-value pairs\&. "
.ti -1c
.RI "void \fBsc_keyvalue_destroy\fP (\fBsc_keyvalue_t\fP *kv)"
.br
.RI "Free a key-value container and all internal memory for key storage\&. "
.ti -1c
.RI "\fBsc_keyvalue_entry_type_t\fP \fBsc_keyvalue_exists\fP (\fBsc_keyvalue_t\fP *kv, const char *key)"
.br
.RI "Routine to check existence of an entry\&. "
.ti -1c
.RI "\fBsc_keyvalue_entry_type_t\fP \fBsc_keyvalue_unset\fP (\fBsc_keyvalue_t\fP *kv, const char *key)"
.br
.RI "Routine to remove an entry\&. "
.ti -1c
.RI "int \fBsc_keyvalue_get_int\fP (\fBsc_keyvalue_t\fP *kv, const char *key, int dvalue)"
.br
.RI "Routines to retrieve an integer value by its key\&. "
.ti -1c
.RI "double \fBsc_keyvalue_get_double\fP (\fBsc_keyvalue_t\fP *kv, const char *key, double dvalue)"
.br
.RI "Retrieve a double value by its key\&. "
.ti -1c
.RI "const char * \fBsc_keyvalue_get_string\fP (\fBsc_keyvalue_t\fP *kv, const char *key, const char *dvalue)"
.br
.RI "Retrieve a string value by its key\&. "
.ti -1c
.RI "void * \fBsc_keyvalue_get_pointer\fP (\fBsc_keyvalue_t\fP *kv, const char *key, void *dvalue)"
.br
.RI "Retrieve a pointer value by its key\&. "
.ti -1c
.RI "int \fBsc_keyvalue_get_int_check\fP (\fBsc_keyvalue_t\fP *kv, const char *key, int *status)"
.br
.RI "Query an integer key with error checking\&. "
.ti -1c
.RI "void \fBsc_keyvalue_set_int\fP (\fBsc_keyvalue_t\fP *kv, const char *key, int newvalue)"
.br
.RI "Routine to set an integer value for a given key\&. "
.ti -1c
.RI "void \fBsc_keyvalue_set_double\fP (\fBsc_keyvalue_t\fP *kv, const char *key, double newvalue)"
.br
.RI "Routine to set a double value for a given key\&. "
.ti -1c
.RI "void \fBsc_keyvalue_set_string\fP (\fBsc_keyvalue_t\fP *kv, const char *key, const char *newvalue)"
.br
.RI "Routine to set a string value for a given key\&. "
.ti -1c
.RI "void \fBsc_keyvalue_set_pointer\fP (\fBsc_keyvalue_t\fP *kv, const char *key, void *newvalue)"
.br
.RI "Routine to set a pointer value for a given key\&. "
.ti -1c
.RI "void \fBsc_keyvalue_foreach\fP (\fBsc_keyvalue_t\fP *kv, \fBsc_keyvalue_foreach_t\fP fn, void *user_data)"
.br
.RI "Iterate through all stored key-value pairs\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file provides a lookup structure for key-value pairs\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef int(* sc_keyvalue_foreach_t) (const char *key, const \fBsc_keyvalue_entry_type_t\fP type, void *entry, const void *u)"

.PP
Function to call on every key value pair\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key for this pair 
.br
\fItype\fP The type of entry 
.br
\fIentry\fP Pointer to the entry 
.br
\fIu\fP Arbitrary user data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return true if the traversal should continue, false to stop\&. 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBsc_keyvalue_entry_type_t\fP"

.PP
The values can have different types\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC_KEYVALUE_ENTRY_NONE \fP\fP
Designate an invalid situation\&. 
.TP
\fB\fISC_KEYVALUE_ENTRY_INT \fP\fP
Used for values of type int\&. 
.TP
\fB\fISC_KEYVALUE_ENTRY_DOUBLE \fP\fP
Used for values of type double\&. 
.TP
\fB\fISC_KEYVALUE_ENTRY_STRING \fP\fP
Used for values of type const char *\&. 
.TP
\fB\fISC_KEYVALUE_ENTRY_POINTER \fP\fP
Used for values of anonymous pointer type\&. 
.SH "Function Documentation"
.PP 
.SS "void sc_keyvalue_destroy (\fBsc_keyvalue_t\fP * kv)"

.PP
Free a key-value container and all internal memory for key storage\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP The key-value container is invalidated by this call\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBoptions\&.c\fP\&.
.SS "\fBsc_keyvalue_entry_type_t\fP sc_keyvalue_exists (\fBsc_keyvalue_t\fP * kv, const char * key)"

.PP
Routine to check existence of an entry\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value container\&. 
.br
\fIkey\fP Lookup key to query\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The entry's type if found and SC_KEYVALUE_ENTRY_NONE otherwise\&. 
.RE
.PP

.SS "void sc_keyvalue_foreach (\fBsc_keyvalue_t\fP * kv, \fBsc_keyvalue_foreach_t\fP fn, void * user_data)"

.PP
Iterate through all stored key-value pairs\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value container\&. 
.br
\fIfn\fP Function to call on each key-value pair\&. 
.br
\fIuser_data\fP This pointer is passed through to \fBfn\fP\&. 
.RE
.PP

.SS "double sc_keyvalue_get_double (\fBsc_keyvalue_t\fP * kv, const char * key, double dvalue)"

.PP
Retrieve a double value by its key\&. This function asserts that the key, if existing, points to the correct type\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value container\&. 
.br
\fIkey\fP Lookup key, may or may not exist\&. 
.br
\fIdvalue\fP Default value returned if key is not found\&. 
.RE
.PP
\fBReturns\fP
.RS 4
If key is not present then \fBdvalue\fP is returned, otherwise the value stored under \fBkey\fP\&. 
.RE
.PP

.SS "int sc_keyvalue_get_int (\fBsc_keyvalue_t\fP * kv, const char * key, int dvalue)"

.PP
Routines to retrieve an integer value by its key\&. This function asserts that the key, if existing, points to the correct type\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value container\&. 
.br
\fIkey\fP Lookup key, may or may not exist\&. 
.br
\fIdvalue\fP Default value returned if key is not found\&. 
.RE
.PP
\fBReturns\fP
.RS 4
If key is not present then \fBdvalue\fP is returned, otherwise the value stored under \fBkey\fP\&. 
.RE
.PP

.SS "int sc_keyvalue_get_int_check (\fBsc_keyvalue_t\fP * kv, const char * key, int * status)"

.PP
Query an integer key with error checking\&. We check whether the key is not found or it is of the wrong type\&. A default value to be returned on error can be passed in as *status\&. If status is NULL, then the result on error is undefined\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value table\&. 
.br
\fIkey\fP Non-NULL key string\&. 
.br
\fIstatus\fP If not NULL, set to 0 if there is no error, 1 if the key is not found, 2 if a value is found but its type is not integer, and return the input value *status on error\&. 
.RE
.PP
\fBReturns\fP
.RS 4
On error we return *status if status is not NULL, and else an undefined value backed by an assertion\&. Without error, return the result of the lookup\&. 
.RE
.PP

.SS "void* sc_keyvalue_get_pointer (\fBsc_keyvalue_t\fP * kv, const char * key, void * dvalue)"

.PP
Retrieve a pointer value by its key\&. This function asserts that the key, if existing, points to the correct type\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value container\&. 
.br
\fIkey\fP Lookup key, may or may not exist\&. 
.br
\fIdvalue\fP Default value returned if key is not found\&. 
.RE
.PP
\fBReturns\fP
.RS 4
If key is not present then \fBdvalue\fP is returned, otherwise the value stored under \fBkey\fP\&. 
.RE
.PP

.SS "const char* sc_keyvalue_get_string (\fBsc_keyvalue_t\fP * kv, const char * key, const char * dvalue)"

.PP
Retrieve a string value by its key\&. This function asserts that the key, if existing, points to the correct type\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value container\&. 
.br
\fIkey\fP Lookup key, may or may not exist\&. 
.br
\fIdvalue\fP Default value returned if key is not found\&. 
.RE
.PP
\fBReturns\fP
.RS 4
If key is not present then \fBdvalue\fP is returned, otherwise the value stored under \fBkey\fP\&. 
.RE
.PP

.SS "\fBsc_keyvalue_t\fP* sc_keyvalue_new ()"

.PP
Create a new key-value container\&. 
.PP
\fBReturns\fP
.RS 4
The container is ready to use\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBoptions\&.c\fP\&.
.SS "\fBsc_keyvalue_t\fP* sc_keyvalue_newf (int dummy,  \&.\&.\&.)"

.PP
Create a container and set one or more key-value pairs\&. Arguments come in pairs of 2: a static string 'type:key' and a value\&. The type is the letter i, g, s, p for int, double, const char *, and void *, respectively\&. 
.PP
\fBParameters\fP
.RS 4
\fIdummy\fP Not touched, just to use the varargs feature\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A key-value container initialized with the given entries\&. 
.RE
.PP

.SS "\fBsc_keyvalue_t\fP* sc_keyvalue_newv (va_list ap)"

.PP
Create a container and set one or more key-value pairs\&. This function works analogously to \fBsc_keyvalue_newf\fP\&. Arguments come in pairs of 2: a static string 'type:key' and a value\&. The type is the letter i, g, s, p for int, double, const char *, and void *, respectively\&. 
.PP
\fBParameters\fP
.RS 4
\fIap\fP Varargs pointer; see stdarg\&.h for the syntax\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A key-value container initialized with the given entries\&. 
.RE
.PP

.SS "void sc_keyvalue_set_double (\fBsc_keyvalue_t\fP * kv, const char * key, double newvalue)"

.PP
Routine to set a double value for a given key\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value table\&. 
.br
\fIkey\fP Non-NULL key to insert or replace\&. If it already exists, it must be of type double\&. 
.br
\fInewvalue\fP New value will be stored under key\&. 
.RE
.PP

.SS "void sc_keyvalue_set_int (\fBsc_keyvalue_t\fP * kv, const char * key, int newvalue)"

.PP
Routine to set an integer value for a given key\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value table\&. 
.br
\fIkey\fP Non-NULL key to insert or replace\&. If it already exists, it must be of type integer\&. 
.br
\fInewvalue\fP New value will be stored under key\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBoptions\&.c\fP\&.
.SS "void sc_keyvalue_set_pointer (\fBsc_keyvalue_t\fP * kv, const char * key, void * newvalue)"

.PP
Routine to set a pointer value for a given key\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value table\&. 
.br
\fIkey\fP Non-NULL key to insert or replace\&. If it already exists, it must be of type pointer\&. 
.br
\fInewvalue\fP New value will be stored under key\&. 
.RE
.PP

.SS "void sc_keyvalue_set_string (\fBsc_keyvalue_t\fP * kv, const char * key, const char * newvalue)"

.PP
Routine to set a string value for a given key\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value table\&. 
.br
\fIkey\fP Non-NULL key to insert or replace\&. If it already exists, it must be of type string\&. 
.br
\fInewvalue\fP New value will be stored under key\&. 
.RE
.PP

.SS "\fBsc_keyvalue_entry_type_t\fP sc_keyvalue_unset (\fBsc_keyvalue_t\fP * kv, const char * key)"

.PP
Routine to remove an entry\&. 
.PP
\fBParameters\fP
.RS 4
\fIkv\fP Valid key-value container\&. 
.br
\fIkey\fP Lookup key to remove if it exists\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The entry's type if found and removed, SC_KEYVALUE_ENTRY_NONE otherwise\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
