.TH "sc_link" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_link \- The \fBsc_link\fP structure is one link of a linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_containers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.RI "Arbitrary payload\&. "
.ti -1c
.RI "struct \fBsc_link\fP * \fBnext\fP"
.br
.RI "Pointer to list successor element\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBsc_link\fP structure is one link of a linked list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
