.TH "sc_logprios" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_logprios \- Log Priorities
.PP
 \- The log level is a number designating the priority of a log action\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSC_LP_DEFAULT\fP   (\-1)"
.br
.RI "Selects the SC default threshold\&. "
.ti -1c
.RI "#define \fBSC_LP_ALWAYS\fP   0"
.br
.RI "Log absolutely everything\&. "
.ti -1c
.RI "#define \fBSC_LP_TRACE\fP   1"
.br
.RI "Prefix file and line number\&. "
.ti -1c
.RI "#define \fBSC_LP_DEBUG\fP   2"
.br
.RI "Any information on the internal state\&. "
.ti -1c
.RI "#define \fBSC_LP_VERBOSE\fP   3"
.br
.RI "Information on conditions, decisions\&. "
.ti -1c
.RI "#define \fBSC_LP_INFO\fP   4"
.br
.RI "Most relevant things a function is doing\&. "
.ti -1c
.RI "#define \fBSC_LP_STATISTICS\fP   5"
.br
.RI "Important for consistency/performance\&. "
.ti -1c
.RI "#define \fBSC_LP_PRODUCTION\fP   6"
.br
.RI "A few lines at most for a major api function\&. "
.ti -1c
.RI "#define \fBSC_LP_ESSENTIAL\fP   7"
.br
.RI "Log a few lines max (version info) per program\&. "
.ti -1c
.RI "#define \fBSC_LP_ERROR\fP   8"
.br
.RI "Log errors only\&. "
.ti -1c
.RI "#define \fBSC_LP_SILENT\fP   9"
.br
.RI "Never log anything\&. "
.in -1c
.SH "Detailed Description"
.PP 
The log level is a number designating the priority of a log action\&. 

Log levels serve both to indicate the priority of a message and as a filter passed to functions to determine which priorities to log\&.
.PP
The priorities \fBSC_LP_TRACE\fP to \fBSC_LP_VERBOSE\fP may be used profusely and are appropriate when all parallel processes contribute low-priority, informative log messages\&.
.PP
\fBSC_LP_INFO\fP and above should not clutter the output of large parallel runs\&. \fBSC_LP_STATISTICS\fP is suggested for important measurements\&. \fBSC_LP_PRODUCTION\fP is meant for rudimentary information on the program flow\&.
.PP
\fBSC_LP_ESSENTIAL\fP can be used for one-time messages, say at program startup to communicate program version or licence information\&.
.PP
\fBSC_LP_ERROR\fP shall never be used during clean operation\&. Thus, it can be used to indicate abnormal behavior of the program and will not disturb the silent appearance of a clean run\&. Recommended for those who generally prefer to see absolutely no output from the libraries they use\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define SC_LP_ERROR   8"

.PP
Log errors only\&. This is suggested over \fBSC_LP_SILENT\fP\&. 
.SS "#define SC_LP_SILENT   9"

.PP
Never log anything\&. Instead suggesting \fBSC_LP_ERROR\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
