.TH "sc_MPI_Status" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_MPI_Status \- Replacement of \fCMPI_Status\fP for non-MPI configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_mpi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.RI "Bytes sent/received\&. "
.ti -1c
.RI "int \fBcancelled\fP"
.br
.RI "Cancellation occurred\&. "
.ti -1c
.RI "int \fBMPI_SOURCE\fP"
.br
.RI "Rank of the source\&. "
.ti -1c
.RI "int \fBMPI_TAG\fP"
.br
.RI "Tag of the message\&. "
.ti -1c
.RI "int \fBMPI_ERROR\fP"
.br
.RI "Error occurred\&. "
.in -1c
.SH "Detailed Description"
.PP 
Replacement of \fCMPI_Status\fP for non-MPI configuration\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
