.TH "sc_options" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_options \- Option Parser
.PP
 \- The option parser reads the command line as well as configuration files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsc_options\&.h\fP"
.br
.RI "Register and parse command line options and read/write configuration files\&. "
.in -1c
.SH "Detailed Description"
.PP 
The option parser reads the command line as well as configuration files\&. 

The library provides a rather flexible and powerful means for configuring a program at runtime\&. Configuration can be effected by parsing command line options or by reading \fC\&.ini\fP or JSON files, or a combination thereof\&.
.PP
The first thing to do is to allocate an empty \fBsc_options_t\fP object\&. Then one or more options can be added to it\&. Such an addition provides details on the option name and type, a help string, and a pointer to an existing variable in user memory that shall be updated when options are parsed or loaded\&. This variable must not go out of scope while the options object it has been added to is in use\&.
.PP
Once the desired variables have been added to the options object variables can be loaded from configuration files by calling the loader function explicitly, for example \fBsc_options_load_json\fP\&. Every variable that is found in the file is parsed and updated\&. Similarly, a command line can be queried by \fBsc_options_parse\fP\&. The options in an object can be saved to a file as well\&.
.PP
The suboptions feature allows options to be nested\&. To this end, any options object can be passed as suboptions to \fBsc_options_add_suboptions\fP, which duplicates its variable entries to the options object under construction below an option name prefix\&. This copies meta-data of the option but passes the same user variable, which can thus be modified by parsing either with the original suboptions or the new, hierarchical options object, or both\&. Suboptions are loaded from and saved to files hierarchically\&.
.PP
Please see the example \fBoptions\&.c\fP for a demonstration\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
