.TH "sc_parallelism" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_parallelism \- Parallelism
.PP
 \- The sc library provides several mechanisms to work with MPI\&.  

.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsc3_mpi_types\&.h\fP"
.br
.RI "We provide MPI replacement data types for configuring without MPI\&. "
.ti -1c
.RI "file \fBsc_allgather\&.h\fP"
.br
.RI "Self-contained implementation of MPI_Allgather\&. "
.ti -1c
.RI "file \fBsc_mpi\&.h\fP"
.br
.RI "Provide a consistent MPI interface with and without MPI configured\&. "
.ti -1c
.RI "file \fBsc_notify\&.h\fP"
.br
.RI "We provide various algorithms to invert the communication pattern\&. "
.ti -1c
.RI "file \fBsc_reduce\&.h\fP"
.br
.RI "Self-contained implementations of MPI_Reduce and MPI_Allreduce\&. "
.in -1c
.SH "Detailed Description"
.PP 
The sc library provides several mechanisms to work with MPI\&. 

The most important one is a wrapper that looks the same to the user whether MPI has been configured or not\&. This allows to use MPI commands in code without protecting #defines\&.
.PP
In addition, we provide MPI reduce, allreduce replacements with reproducible associativity as well as an allgather replacement\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
