.TH "src/sc_private.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_private.h \- Support for calls between different parts of the sc library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsc_package_rc_count_add\fP (int package_id, int toadd)"
.br
.RI "Add to the per-package variable about active reference counters\&. "
.in -1c
.SH "Detailed Description"
.PP 
Support for calls between different parts of the sc library\&. 

This is not meant for use from other packages or applications\&. 
.SH "Function Documentation"
.PP 
.SS "void sc_package_rc_count_add (int package_id, int toadd)"

.PP
Add to the per-package variable about active reference counters\&. This function is thread safe; it uses per-package locking internally 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP The id of a registered package or -1\&. 
.br
\fItoadd\fP This is added to the package's internal variable that counts active rcs\&. We assert that the new count does not drop below zero\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
