.TH "sc_refcount" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_refcount \- The refcount structure is declared in public so its size is known\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_refcount\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpackage_id\fP"
.br
.RI "The sc package that uses this reference counter\&. "
.ti -1c
.RI "int \fBrefcount\fP"
.br
.RI "The reference count is always positive for a valid counter\&. "
.in -1c
.SH "Detailed Description"
.PP 
The refcount structure is declared in public so its size is known\&. 

Its members should really never be accessed directly\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
