.TH "src/sc_random.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_random.h \- Provide pseudo-random generator and Poisson sampling\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint64_t \fBsc_rand_state_t\fP"
.br
.RI "The internal state of sc_rand and derived functions\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBsc_rand\fP (\fBsc_rand_state_t\fP *state)"
.br
.RI "Draw a (pseudo-)random variable uniformly distributed in [0, 1)\&. "
.ti -1c
.RI "double \fBsc_rand_normal\fP (\fBsc_rand_state_t\fP *state, double *second_result)"
.br
.RI "Sample the Gauss standard normal distribution\&. "
.ti -1c
.RI "int \fBsc_rand_small\fP (\fBsc_rand_state_t\fP *state, double d)"
.br
.RI "Randomly draw either 0 or 1 where the probability for 1 is small\&. "
.ti -1c
.RI "int \fBsc_rand_poisson\fP (\fBsc_rand_state_t\fP *state, double mean)"
.br
.RI "Draw from a random variable following the Poisson distribution\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provide pseudo-random generator and Poisson sampling\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef uint64_t \fBsc_rand_state_t\fP"

.PP
The internal state of sc_rand and derived functions\&. Can be set arbitrarily to obtain reproducible pseudo random numbers\&. 
.SH "Function Documentation"
.PP 
.SS "double sc_rand (\fBsc_rand_state_t\fP * state)"

.PP
Draw a (pseudo-)random variable uniformly distributed in [0, 1)\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP Internal state of random number generator\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Number in [0, 1)\&. 
.RE
.PP

.SS "double sc_rand_normal (\fBsc_rand_state_t\fP * state, double * second_result)"

.PP
Sample the Gauss standard normal distribution\&. Implements polar form of the Box Muller transform based on \fBsc_rand\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP Internal state of random number generator\&. 
.br
\fIsecond_result\fP We compute two independent samples\&. The first is the return value\&. The second is placed in *second_result unless second_result == NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Random sample from the standard normal distribution\&. 
.RE
.PP

.SS "int sc_rand_poisson (\fBsc_rand_state_t\fP * state, double mean)"

.PP
Draw from a random variable following the Poisson distribution\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP Internal state of random number generator\&. 
.br
\fImean\fP Mean value of Poisson distribution\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Non-negative integer\&. 
.RE
.PP

.SS "int sc_rand_small (\fBsc_rand_state_t\fP * state, double d)"

.PP
Randomly draw either 0 or 1 where the probability for 1 is small\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP Internal state of random number generator\&. 
.br
\fId\fP Probability of drawing ones\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 or 1\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
