.TH "sc_scda_ferror" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_scda_ferror \- Error values for the scda functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_scda\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmpiret\fP"
.br
.RI "MPI function return value; without MPI this variable can get filled by other I/O operation error codes, which are still interpretable by the error \fBscda\fP examination functions\&. "
.ti -1c
.RI "\fBsc_scda_ret_t\fP \fBscdaret\fP"
.br
.RI "scda file format related return value "
.in -1c
.SH "Detailed Description"
.PP 
Error values for the scda functions\&. 

An error value is a struct since the error can be related to the scda file format or to (MPI) I/O operations\&. The error code can be converted to a string by \fBsc_scda_ferror_string\fP, mapped to an error class by \fBsc_scda_ferror_class\fP and checked for success by \fBsc_scda_ferror_is_success\fP\&. The user can rely on these functions to parse \fBsc_scda_ferror\fP and does not need to access the members of this structure\&.
.PP
The parsing logic of \fBsc_scda_ferror_t\fP is that first \fBscdaret\fP is examined and if \fBscdaret\fP != \fBSC_SCDA_FERR_MPI\fP, we know that \fBmpiret\fP = 0\&. If \fBscdaret\fP = \fBSC_SCDA_FERR_MPI\fP, we know that an MPI error occurred and we can examine \fBmpiret\fP for more informartion\&.
.PP
Moreover, a valid \fBsc_scda_ferror\fP always satisfy that if \fBscdaret\fP = 0 then \fBmpiret\fP = 0 and if \fBscdaret\fP = \fBSC_SCDA_FERR_MPI\fP then \fBmpiret\fP !=0\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
