.TH "sc_statinfo" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_statinfo \- Store information of one random variable\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_statistics\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdirty\fP"
.br
.RI "Only update stats if this is true\&. "
.ti -1c
.RI "long \fBcount\fP"
.br
.RI "Inout; global count is 52 bit accurate\&. "
.ti -1c
.RI "double \fBsum_values\fP"
.br
.RI "Inout; global sum of values\&. "
.ti -1c
.RI "double \fBsum_squares\fP"
.br
.RI "Inout; global sum of squares\&. "
.ti -1c
.RI "double \fBmin\fP"
.br
.RI "Inout; minimum over values\&. "
.ti -1c
.RI "double \fBmax\fP"
.br
.RI "Inout; maximum over values\&. "
.ti -1c
.RI "int \fBmin_at_rank\fP"
.br
.ti -1c
.RI "int \fBmax_at_rank\fP"
.br
.ti -1c
.RI "double \fBaverage\fP"
.br
.ti -1c
.RI "double \fBvariance\fP"
.br
.ti -1c
.RI "double \fBstandev\fP"
.br
.ti -1c
.RI "double \fBvariance_mean\fP"
.br
.ti -1c
.RI "double \fBstandev_mean\fP"
.br
.ti -1c
.RI "const char * \fBvariable\fP"
.br
.RI "Name of the variable for output\&. "
.ti -1c
.RI "char * \fBvariable_owned\fP"
.br
.RI "NULL or deep copy of variable\&. "
.ti -1c
.RI "int \fBgroup\fP"
.br
.RI "Grouping identifier\&. "
.ti -1c
.RI "int \fBprio\fP"
.br
.RI "Priority identifier\&. "
.in -1c
.SH "Detailed Description"
.PP 
Store information of one random variable\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
