.TH "sc_scda_fopen_options" 3 "Mon Mar 10 2025" "Version 2.8.6.343-44bc2-dirty" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_scda_fopen_options \- An options struct for the functions \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_scda\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsc_MPI_Info\fP \fBinfo\fP"
.br
.RI "info that is passed to MPI_File_open "
.ti -1c
.RI "unsigned \fBfuzzy_everyn\fP"
.br
.RI "In average every n-th possible error origin returns a fuzzy error\&. "
.ti -1c
.RI "\fBsc_rand_state_t\fP \fBfuzzy_seed\fP"
.br
.RI "The seed for the fuzzy error return\&. "
.in -1c
.SH "Detailed Description"
.PP 
An options struct for the functions \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP\&. 

The struct may be extended in the future\&.
.PP
The option struct is a collective structure\&. If the options structure that is passed to a function is not the same on all processes, the whole following scda workflow has undefined behavior\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned sc_scda_fopen_options::fuzzy_everyn"

.PP
In average every n-th possible error origin returns a fuzzy error\&. There may be multiple possible error origins in one top-level scda function\&. We return for each possible error origin a random error with the empirical probability of 1 / fuzzy_everyn but only if the respective possible error origin did not already cause an error without the fuzzy error return\&. In such a case, the actual error is returned\&. 0 means that there are no fuzzy error returns\&. 
.SS "\fBsc_rand_state_t\fP sc_scda_fopen_options::fuzzy_seed"

.PP
The seed for the fuzzy error return\&. This value is ignored if fuzzy_everyn == 0\&. When in doubt use fuzzy_seed = 0\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
