.TH "src/sc_statistics.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_statistics.h \- Computation of average and mean values etc\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc_keyvalue\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsc_statinfo\fP"
.br
.RI "Store information of one random variable\&. "
.ti -1c
.RI "struct \fBsc_stats\fP"
.br
.RI "The statistics container allows dynamically adding random variables\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsc_statinfo\fP \fBsc_statinfo_t\fP"
.br
.RI "Store information of one random variable\&. "
.ti -1c
.RI "typedef struct \fBsc_stats\fP \fBsc_statistics_t\fP"
.br
.RI "The statistics container allows dynamically adding random variables\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsc_stats_set1\fP (\fBsc_statinfo_t\fP *stats, double value, const char *variable)"
.br
.RI "Populate a sc_statinfo_t structure assuming count=1 and mark it dirty\&. "
.ti -1c
.RI "void \fBsc_stats_set1_ext\fP (\fBsc_statinfo_t\fP *stats, double value, const char *variable, int copy_variable, int stats_group, int stats_prio)"
.br
.RI "Populate a sc_statinfo_t structure assuming count=1 and mark it dirty\&. "
.ti -1c
.RI "void \fBsc_stats_init\fP (\fBsc_statinfo_t\fP *stats, const char *variable)"
.br
.RI "Initialize a sc_statinfo_t structure assuming count=0 and mark it dirty\&. "
.ti -1c
.RI "void \fBsc_stats_init_ext\fP (\fBsc_statinfo_t\fP *stats, const char *variable, int copy_variable, int stats_group, int stats_prio)"
.br
.RI "Initialize a sc_statinfo_t structure assuming count=0 and mark it dirty\&. "
.ti -1c
.RI "void \fBsc_stats_reset\fP (\fBsc_statinfo_t\fP *stats, int reset_vgp)"
.br
.RI "Reset all values to zero, optionally unassign name, group, and priority\&. "
.ti -1c
.RI "void \fBsc_stats_set_group_prio\fP (\fBsc_statinfo_t\fP *stats, int stats_group, int stats_prio)"
.br
.RI "Set/update the group and priority information for a stats item\&. "
.ti -1c
.RI "void \fBsc_stats_accumulate\fP (\fBsc_statinfo_t\fP *stats, double value)"
.br
.RI "Add an instance of the random variable\&. "
.ti -1c
.RI "void \fBsc_stats_compute\fP (\fBsc_MPI_Comm\fP mpicomm, int nvars, \fBsc_statinfo_t\fP *stats)"
.br
.RI "Compute global average and standard deviation\&. "
.ti -1c
.RI "void \fBsc_stats_compute1\fP (\fBsc_MPI_Comm\fP mpicomm, int nvars, \fBsc_statinfo_t\fP *stats)"
.br
.RI "Version of sc_statistics_statistics that assumes count=1\&. "
.ti -1c
.RI "void \fBsc_stats_print\fP (int package_id, int log_priority, int nvars, \fBsc_statinfo_t\fP *stats, int full, int summary)"
.br
.RI "Print measured statistics\&. "
.ti -1c
.RI "void \fBsc_stats_print_ext\fP (int package_id, int log_priority, int nvars, \fBsc_statinfo_t\fP *stats, int stats_group, int stats_prio, int full, int summary)"
.br
.RI "Print measured statistics, filter by group and/or priority\&. "
.ti -1c
.RI "\fBsc_statistics_t\fP * \fBsc_statistics_new\fP (\fBsc_MPI_Comm\fP mpicomm)"
.br
.RI "Create a new statistics structure that can grow dynamically\&. "
.ti -1c
.RI "void \fBsc_statistics_destroy\fP (\fBsc_statistics_t\fP *stats)"
.br
.RI "Destroy a statistics structure\&. "
.ti -1c
.RI "void \fBsc_statistics_add\fP (\fBsc_statistics_t\fP *stats, const char *name)"
.br
.RI "Register a statistics variable by name and set its value to 0\&. "
.ti -1c
.RI "void \fBsc_statistics_add_empty\fP (\fBsc_statistics_t\fP *stats, const char *name)"
.br
.RI "Register a statistics variable by name and set its count to 0\&. "
.ti -1c
.RI "int \fBsc_statistics_has\fP (\fBsc_statistics_t\fP *stats, const char *name)"
.br
.RI "Returns true if the stats include a variable with the given name\&. "
.ti -1c
.RI "void \fBsc_statistics_set\fP (\fBsc_statistics_t\fP *stats, const char *name, double value)"
.br
.RI "Set the value of a statistics variable, see sc_stats_set1\&. "
.ti -1c
.RI "void \fBsc_statistics_accumulate\fP (\fBsc_statistics_t\fP *stats, const char *name, double value)"
.br
.RI "Add an instance of a statistics variable, see sc_stats_accumulate The variable must previously be added with sc_statistics_add_empty\&. "
.ti -1c
.RI "void \fBsc_statistics_compute\fP (\fBsc_statistics_t\fP *stats)"
.br
.RI "Compute statistics for all variables, see sc_stats_compute\&. "
.ti -1c
.RI "void \fBsc_statistics_print\fP (\fBsc_statistics_t\fP *stats, int package_id, int log_priority, int full, int summary)"
.br
.RI "Print all statistics variables, see sc_stats_print\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBsc_stats_group_all\fP"
.br
.RI "This special group number (negative) will refer to any group\&. "
.ti -1c
.RI "const int \fBsc_stats_prio_all\fP"
.br
.RI "This special group number (negative) will refer to any priority\&. "
.in -1c
.SH "Detailed Description"
.PP 
Computation of average and mean values etc\&. 

between parallel processes\&. 
.SH "Function Documentation"
.PP 
.SS "void sc_statistics_add (\fBsc_statistics_t\fP * stats, const char * name)"

.PP
Register a statistics variable by name and set its value to 0\&. This variable must not exist already\&. 
.SS "void sc_statistics_add_empty (\fBsc_statistics_t\fP * stats, const char * name)"

.PP
Register a statistics variable by name and set its count to 0\&. This variable must not exist already\&. 
.SS "void sc_statistics_destroy (\fBsc_statistics_t\fP * stats)"

.PP
Destroy a statistics structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Valid object is invalidated\&. 
.RE
.PP

.SS "void sc_statistics_set (\fBsc_statistics_t\fP * stats, const char * name, double value)"

.PP
Set the value of a statistics variable, see sc_stats_set1\&. The variable must previously be added with sc_statistics_add\&. This assumes count=1 as in the sc_stats_set1 function above\&. 
.SS "void sc_stats_accumulate (\fBsc_statinfo_t\fP * stats, double value)"

.PP
Add an instance of the random variable\&. The counter of the variable is increased by one\&. The value is added into the present values of the variable\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Must be dirty\&. We bump count and values\&. 
.br
\fIvalue\fP Value used to update statistics information\&. 
.RE
.PP

.SS "void sc_stats_compute (\fBsc_MPI_Comm\fP mpicomm, int nvars, \fBsc_statinfo_t\fP * stats)"

.PP
Compute global average and standard deviation\&. Only updates dirty variables\&. Then removes the dirty flag\&. 
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP MPI communicator to use\&. 
.br
\fInvars\fP Number of variables to be examined\&. 
.br
\fIstats\fP Set of statisics items for each variable\&. On input, set the following fields for each variable separately\&. count Number of values for each process\&. sum_values Sum of values for each process\&. sum_squares Sum of squares for each process\&. min, max Minimum and maximum of values for each process\&. variable String describing the variable, or NULL\&. On output, the fields have the following meaning\&. count Global number of values\&. sum_values Global sum of values\&. sum_squares Global sum of squares\&. min, max Global minimum and maximum values\&. min_at_rank, max_at_rank The ranks that attain min and max\&. average, variance, standev Global statistical measures\&. variance_mean, standev_mean Statistical measures of the mean\&. 
.RE
.PP

.SS "void sc_stats_compute1 (\fBsc_MPI_Comm\fP mpicomm, int nvars, \fBsc_statinfo_t\fP * stats)"

.PP
Version of sc_statistics_statistics that assumes count=1\&. On input, the field sum_values needs to be set to the value and the field variable must contain a valid string or NULL\&. Only updates dirty variables\&. Then removes the dirty flag\&. 
.SS "void sc_stats_init (\fBsc_statinfo_t\fP * stats, const char * variable)"

.PP
Initialize a sc_statinfo_t structure assuming count=0 and mark it dirty\&. This is useful if \fIstats\fP will be used to \fBsc_stats_accumulate\fP instances locally before global statistics are computed\&. We set \fBsc_stats_group_all\fP and \fBsc_stats_prio_all\fP internally\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Will be filled with count 0 and values of 0\&. 
.br
\fIvariable\fP String to be reported by \fBsc_stats_print\fP\&. This string is assigned by pointer, not copied\&. Thus, it must stay alive while stats is in use\&. 
.RE
.PP

.SS "void sc_stats_init_ext (\fBsc_statinfo_t\fP * stats, const char * variable, int copy_variable, int stats_group, int stats_prio)"

.PP
Initialize a sc_statinfo_t structure assuming count=0 and mark it dirty\&. This is useful if \fIstats\fP will be used to \fBsc_stats_accumulate\fP instances locally before global statistics are computed\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Will be filled with count 0 and values of 0\&. 
.br
\fIvariable\fP String to be reported by \fBsc_stats_print\fP\&. 
.br
\fIcopy_variable\fP If true, make internal copy of variable\&. Otherwise just assign the pointer\&. 
.br
\fIstats_group\fP Non-negative number or \fBsc_stats_group_all\fP\&. 
.br
\fIstats_prio\fP Non-negative number or \fBsc_stats_prio_all\fP\&. Values increase by importance\&. 
.RE
.PP

.SS "void sc_stats_print (int package_id, int log_priority, int nvars, \fBsc_statinfo_t\fP * stats, int full, int summary)"

.PP
Print measured statistics\&. This function uses the SC_LC_GLOBAL log category\&. That means the default action is to print only on rank 0\&. Applications can change that by providing a user-defined log handler\&. All groups and priorities are printed\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Registered package id or -1\&. 
.br
\fIlog_priority\fP Log priority for output according to \fBsc\&.h\fP\&. 
.br
\fInvars\fP Number of stats items in input array\&. 
.br
\fIstats\fP Input array of stats variable items\&. 
.br
\fIfull\fP Print full information for every variable\&. 
.br
\fIsummary\fP Print summary information all on 1 line\&. 
.RE
.PP

.SS "void sc_stats_print_ext (int package_id, int log_priority, int nvars, \fBsc_statinfo_t\fP * stats, int stats_group, int stats_prio, int full, int summary)"

.PP
Print measured statistics, filter by group and/or priority\&. This function uses the SC_LC_GLOBAL log category\&. That means the default action is to print only on rank 0\&. Applications can change that by providing a user-defined log handler\&. 
.PP
\fBParameters\fP
.RS 4
\fIpackage_id\fP Registered package id or -1\&. 
.br
\fIlog_priority\fP Log priority for output according to \fBsc\&.h\fP\&. 
.br
\fInvars\fP Number of stats items in input array\&. 
.br
\fIstats\fP Input array of stats variable items\&. 
.br
\fIstats_group\fP Print only this group\&. Non-negative or \fBsc_stats_group_all\fP\&. We skip printing a variable if neither this parameter nor the item's group is all and if the item's group does not match this\&. 
.br
\fIstats_prio\fP Print this and higher priorities\&. Non-negative or \fBsc_stats_prio_all\fP\&. We skip printing a variable if neither this parameter nor the item's prio is all and if the item's prio is less than this\&. 
.br
\fIfull\fP Print full information for every variable\&. This produces multiple lines including minimum, maximum, and standard deviation\&. If this is false, print one line per variable\&. 
.br
\fIsummary\fP Print summary information all on 1 line\&. This always contains all variables\&. Not affected by stats_group and stats_prio\&. 
.RE
.PP

.SS "void sc_stats_reset (\fBsc_statinfo_t\fP * stats, int reset_vgp)"

.PP
Reset all values to zero, optionally unassign name, group, and priority\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Variables are zeroed\&. They can be set again by set1 or accumulate\&. 
.br
\fIreset_vgp\fP If true, the variable name string is zeroed and if we did a copy, the copy is freed\&. If true, group and priority are set to all\&. If false, we don't touch any of the above\&. 
.RE
.PP

.SS "void sc_stats_set1 (\fBsc_statinfo_t\fP * stats, double value, const char * variable)"

.PP
Populate a sc_statinfo_t structure assuming count=1 and mark it dirty\&. We set \fBsc_stats_group_all\fP and \fBsc_stats_prio_all\fP internally\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Will be filled with count=1 and the value\&. 
.br
\fIvalue\fP Value used to fill statistics information\&. 
.br
\fIvariable\fP String to be reported by \fBsc_stats_print\fP\&. This string is assigned by pointer, not copied\&. Thus, it must stay alive while stats is in use\&. 
.RE
.PP

.SS "void sc_stats_set1_ext (\fBsc_statinfo_t\fP * stats, double value, const char * variable, int copy_variable, int stats_group, int stats_prio)"

.PP
Populate a sc_statinfo_t structure assuming count=1 and mark it dirty\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Will be filled with count=1 and the value\&. 
.br
\fIvalue\fP Value used to fill statistics information\&. 
.br
\fIvariable\fP String to be reported by \fBsc_stats_print\fP\&. 
.br
\fIcopy_variable\fP If true, make internal copy of variable\&. Otherwise just assign the pointer\&. 
.br
\fIstats_group\fP Non-negative number or \fBsc_stats_group_all\fP\&. 
.br
\fIstats_prio\fP Non-negative number or \fBsc_stats_prio_all\fP\&. 
.RE
.PP

.SS "void sc_stats_set_group_prio (\fBsc_statinfo_t\fP * stats, int stats_group, int stats_prio)"

.PP
Set/update the group and priority information for a stats item\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP Only group and stats entries are updated\&. 
.br
\fIstats_group\fP Non-negative number or \fBsc_stats_group_all\fP\&. 
.br
\fIstats_prio\fP Non-negative number or \fBsc_stats_prio_all\fP\&. Values increase by importance\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
