.TH "src/sc_string.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_string.h \- This file declares a simple string object that can be appended to\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsc_string\fP"
.br
.RI "This is a simple type for growing a string by printf-like commands\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSC_STRING_SIZE\fP   4088"
.br
.RI "This defines the maximum string storage including the trailing '\\0'\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsc_string\fP \fBsc_string_t\fP"
.br
.RI "This is a simple type for growing a string by printf-like commands\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsc_string_init\fP (\fBsc_string_t\fP *scs)"
.br
.RI "Initialize to an empty string\&. "
.ti -1c
.RI "int \fBsc_string_putc\fP (\fBsc_string_t\fP *scs, int c)"
.br
.RI "Append a single character to the string buffer object\&. "
.ti -1c
.RI "int \fBsc_string_puts\fP (\fBsc_string_t\fP *scs, const char *s)"
.br
.RI "Append a string to the string buffer object\&. "
.ti -1c
.RI "int \fBsc_string_putf\fP (\fBsc_string_t\fP *scs, const char *fmt,\&.\&.\&.)"
.br
.RI "Append to the string object using a format string and arguments\&. "
.ti -1c
.RI "int \fBsc_string_putv\fP (\fBsc_string_t\fP *scs, const char *fmt, va_list ap)"
.br
.RI "Append to the string object using a format string and a vararg pointer\&. "
.ti -1c
.RI "const char * \fBsc_string_get_content\fP (\fBsc_string_t\fP *scs, int *length)"
.br
.RI "Access content of the string buffer\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file declares a simple string object that can be appended to\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBsc_string\fP \fBsc_string_t\fP"

.PP
This is a simple type for growing a string by printf-like commands\&. It is public so it can be declared on the stack to avoid malloc and free\&. This means that the length of the string is limited to \fBSC_STRING_SIZE\fP - 1\&. The current string can be accessed by \fBsc_string_get_content\fP\&. This is really an opaque object: its members shall not be accessed directly\&. 
.SH "Function Documentation"
.PP 
.SS "const char* sc_string_get_content (\fBsc_string_t\fP * scs, int * length)"

.PP
Access content of the string buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fIscs\fP Valid \fBsc_string\fP object\&. 
.br
\fIlength\fP If not NULL, assign length without trailing '\\0'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to an internally allocated string, may not be used after \fBscs\fP goes out of scope\&. 
.RE
.PP

.SS "void sc_string_init (\fBsc_string_t\fP * scs)"

.PP
Initialize to an empty string\&. This function can be used to reset a non-empty string to be empty again\&. 
.PP
\fBParameters\fP
.RS 4
\fIscs\fP After returning, a valid object containing the empty string\&. 
.RE
.PP

.SS "int sc_string_putc (\fBsc_string_t\fP * scs, int c)"

.PP
Append a single character to the string buffer object\&. 
.PP
\fBParameters\fP
.RS 4
\fIscs\fP A valid string buffer object\&. 
.br
\fIc\fP Converted to an unsigned char and appended\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Zero if the character has been appended and a negative value when the input was truncated\&. 
.RE
.PP

.SS "int sc_string_putf (\fBsc_string_t\fP * scs, const char * fmt,  \&.\&.\&.)"

.PP
Append to the string object using a format string and arguments\&. The maximum length will not be exceeded\&. The string object will remain valid even on truncated input\&. 
.PP
\fBParameters\fP
.RS 4
\fIscs\fP Valid string object that is appended to\&. 
.br
\fIfmt\fP Format string as used with printf and friends\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Zero if everything has been appended and a negative value when the input was truncated\&. 
.RE
.PP

.SS "int sc_string_puts (\fBsc_string_t\fP * scs, const char * s)"

.PP
Append a string to the string buffer object\&. 
.PP
\fBParameters\fP
.RS 4
\fIscs\fP A valid string buffer object\&. 
.br
\fIs\fP This string is appended to the string buffer\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Zero if the string has been appended and a negative value when the input was truncated\&. 
.RE
.PP

.SS "int sc_string_putv (\fBsc_string_t\fP * scs, const char * fmt, va_list ap)"

.PP
Append to the string object using a format string and a vararg pointer\&. The maximum length will not be exceeded\&. The string object will remain valid even on truncated input\&. 
.PP
\fBParameters\fP
.RS 4
\fIscs\fP Valid string object that is appended to\&. 
.br
\fIfmt\fP Format string as used with printf and friends\&. 
.br
\fIap\fP Argument list pointer as defined in stdarg\&.h\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Zero if everything has been appended and a negative value when the input was truncated\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
