.TH "sc_stats" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_stats \- The statistics container allows dynamically adding random variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_statistics\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsc_MPI_Comm\fP \fBmpicomm\fP"
.br
.ti -1c
.RI "\fBsc_keyvalue_t\fP * \fBkv\fP"
.br
.ti -1c
.RI "\fBsc_array_t\fP * \fBsarray\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The statistics container allows dynamically adding random variables\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
