.TH "src/sc_scda.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_scda.h \- Routines for parallel I/O with the \fBscda\fP format\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc_containers\&.h>\fP
.br
\fC#include <sc_random\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsc_scda_ferror\fP"
.br
.RI "Error values for the scda functions\&. "
.ti -1c
.RI "struct \fBsc_scda_params\fP"
.br
.RI "A parameter struct for the functions \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSC_SCDA_HEADER_BYTES\fP   128"
.br
.RI "number of file header bytes "
.ti -1c
.RI "#define \fBSC_SCDA_USER_STRING_BYTES\fP   58"
.br
.RI "number of user string bytes "
.ti -1c
.RI "#define \fBSC_SCDA_INLINE_FIELD\fP   32"
.br
.RI "byte count of inline data "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct sc_scda_fcontext \fBsc_scda_fcontext_t\fP"
.br
.RI "Opaque context for writing and reading a libsc data file, i\&.e\&. "
.ti -1c
.RI "typedef uint64_t \fBsc_scda_ulong\fP"
.br
.RI "Type for element counts and sizes\&. "
.ti -1c
.RI "typedef enum \fBsc_scda_ret\fP \fBsc_scda_ret_t\fP"
.br
.RI "Error values for scda-related errors\&. "
.ti -1c
.RI "typedef struct \fBsc_scda_ferror\fP \fBsc_scda_ferror_t\fP"
.br
.RI "Error values for the scda functions\&. "
.ti -1c
.RI "typedef struct \fBsc_scda_params\fP \fBsc_scda_params_t\fP"
.br
.RI "A parameter struct for the functions \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsc_scda_ret\fP { \fBSC_SCDA_FERR_SUCCESS\fP = 0, \fBSC_SCDA_FERR_FORMAT\fP = 15000, \fBSC_SCDA_FERR_USAGE\fP, \fBSC_SCDA_FERR_DECODE\fP, \fBSC_SCDA_FERR_ARG\fP, \fBSC_SCDA_FERR_COUNT\fP, \fBSC_SCDA_FERR_MPI\fP, \fBSC_SCDA_FERR_LASTCODE\fP }"
.br
.RI "Error values for scda-related errors\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsc_scda_params_init\fP (\fBsc_scda_params_t\fP *params)"
.br
.RI "Initialize a scda parameter structure to the defaults\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fopen_write\fP (\fBsc_MPI_Comm\fP mpicomm, const char *filename, const char *user_string, size_t *len, \fBsc_scda_params_t\fP *params, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Open a file for writing and write the file header to the file\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fwrite_inline\fP (\fBsc_scda_fcontext_t\fP *fc, const char *user_string, size_t *len, \fBsc_array_t\fP *inline_data, int root, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Write an inline data section\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fwrite_block\fP (\fBsc_scda_fcontext_t\fP *fc, const char *user_string, size_t *len, \fBsc_array_t\fP *block_data, size_t block_size, int root, int encode, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Write a fixed-size block file section\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fwrite_array\fP (\fBsc_scda_fcontext_t\fP *fc, const char *user_string, size_t *len, \fBsc_array_t\fP *array_data, \fBsc_array_t\fP *elem_counts, size_t elem_size, int indirect, int encode, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Write a fixed-size array file section\&. "
.ti -1c
.RI "int \fBsc_scda_proc_sizes\fP (\fBsc_array_t\fP *elem_sizes, \fBsc_array_t\fP *elem_counts, \fBsc_array_t\fP *proc_sizes, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "This is a collective function to determine the processor sizes\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fwrite_varray\fP (\fBsc_scda_fcontext_t\fP *fc, const char *user_string, size_t *len, \fBsc_array_t\fP *array_data, \fBsc_array_t\fP *elem_counts, \fBsc_array_t\fP *elem_sizes, \fBsc_array_t\fP *proc_sizes, int indirect, int encode, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Write a variable-size array file section\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fopen_read\fP (\fBsc_MPI_Comm\fP mpicomm, const char *filename, char *user_string, size_t *len, \fBsc_scda_params_t\fP *params, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Open a file for reading and read the file header from the file\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fread_section_header\fP (\fBsc_scda_fcontext_t\fP *fc, char *user_string, size_t *len, char *type, size_t *elem_count, size_t *elem_size, int *decode, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Read the next file section header\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fread_inline_data\fP (\fBsc_scda_fcontext_t\fP *fc, \fBsc_array_t\fP *data, int root, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Read the data of an inline data section\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fread_block_data\fP (\fBsc_scda_fcontext_t\fP *fc, \fBsc_array_t\fP *block_data, size_t block_size, int root, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Read the data of a block of given size\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fread_array_data\fP (\fBsc_scda_fcontext_t\fP *fc, \fBsc_array_t\fP *array_data, \fBsc_array_t\fP *elem_counts, size_t elem_size, int indirect, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Read the data of a fixed-size array\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fread_varray_sizes\fP (\fBsc_scda_fcontext_t\fP *fc, \fBsc_array_t\fP *elem_sizes, \fBsc_array_t\fP *elem_counts, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Read the element sizes of a variable-size array\&. "
.ti -1c
.RI "\fBsc_scda_fcontext_t\fP * \fBsc_scda_fread_varray_data\fP (\fBsc_scda_fcontext_t\fP *fc, \fBsc_array_t\fP *array_data, \fBsc_array_t\fP *elem_counts, \fBsc_array_t\fP *elem_sizes, \fBsc_array_t\fP *proc_sizes, int indirect, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Read the data of a variable-size array\&. "
.ti -1c
.RI "int \fBsc_scda_ferror_class\fP (\fBsc_scda_ferror_t\fP errcode, \fBsc_scda_ferror_t\fP *errclass)"
.br
.RI "Translate a sc_scda error code to an error class\&. "
.ti -1c
.RI "int \fBsc_scda_ferror_is_success\fP (\fBsc_scda_ferror_t\fP errorcode)"
.br
.RI "Check if a scda_errorcode_t encodes success\&. "
.ti -1c
.RI "int \fBsc_scda_ferror_string\fP (\fBsc_scda_ferror_t\fP errcode, char *str, int *len)"
.br
.RI "Translate a sc_scda error code/class to an error string\&. "
.ti -1c
.RI "int \fBsc_scda_fclose\fP (\fBsc_scda_fcontext_t\fP *fc, \fBsc_scda_ferror_t\fP *errcode)"
.br
.RI "Close a file opened for parallel write/read and the free the file context\&. "
.in -1c
.SH "Detailed Description"
.PP 
Routines for parallel I/O with the \fBscda\fP format\&. 


.PP
\fBWarning\fP
.RS 4
This API will change in the next libsc version!
.RE
.PP
Functionality to write and read in parallel using a prescribed serial-equivalent file format called \fBscda\fP\&.
.SS "General"
The \fBscda\fP format is as in this \fCpreprint\fP\&.
.PP
However, in contrast to the preprint the API in this file provides the two functions \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP instead of providing one opening function with a mode parameter to decide and writing and reading\&.
.PP
In addition, we add in this file the options structure \fBsc_scda_params\fP as parameter for opening files\&.
.PP
The file format includes metadata in ASCII and therefore enables the human eye to parse the file structure using a standard text editor\&.
.PP
The file format \fBscda\fP is in particular suitable for parallel I/O and is accompanied by a convention for element-wise compression\&.
.PP
The format is designed such that the the parallel partition and in particular the process count can differ between writing and reading\&.
.PP
The main purpose of \fBscda\fP is to enable the user to implement parallel I/O for numerical appliations, e\&.g\&. simulation checkpoint/restart\&.
.PP
We elaborate further on the workflow in \fBParallel I/O workflow\fP\&.
.PP
The \fBscda\fP functions do not support the deprecated configuration case of MPI being enabled but MPI I/O being disabled\&. The functions \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP abort in this case\&. All other valid configurations are supported\&.
.SS "User Strings"
The functions
.PP
.IP "\(bu" 2
\fBsc_scda_fopen_write\fP,
.IP "\(bu" 2
\fBsc_scda_fwrite_inline\fP,
.IP "\(bu" 2
\fBsc_scda_fwrite_block\fP,
.IP "\(bu" 2
\fBsc_scda_fwrite_array\fP,
.IP "\(bu" 2
\fBsc_scda_fwrite_varray\fP,
.IP "\(bu" 2
\fBsc_scda_fopen_read\fP and
.IP "\(bu" 2
\fBsc_scda_fread_section_header\fP
.PP
.PP
have \fBuser_string\fP and \fBlen\fP as an argument\&.
.PP
The user string consisting of the two parameters \fBuser_string\fP and \fBlen\fP is always a collective parameter\&.
.PP
In the case of writing these arguments have the purpose to pass the user string that is written to the file\&.
.PP
There are two options writing the user string to the file\&.
.PP
.IP "1." 4
A nul-terminated string \fBuser_string\fP, i\&.e\&. a standard C string\&. In this case \fBlen\fP is set to NULL since the length of \fBuser_string\fP is implicitly given by the nul-termination\&.
.IP "2." 4
Arbitrary data for the user string including possible '\\0' in non-terminating positions\&. We still require nul-termination for safety\&. One needs to explicitly pass the length, i\&.e\&. the number of bytes excluding the nul-termination\&.
.PP
.PP
For both options it must be respected that the number of maximal \fBuser_string\fP bytes is \fBSC_SCDA_USER_STRING_BYTES\fP + 1 including the nul-termination\&.
.PP
In case of reading \fBuser_string\fP must be at least \fBSC_SCDA_USER_STRING_BYTES\fP + 1 bytes\&. On output \fBlen\fP is set to the number of bytes actually written to \fBuser_string\fP excluding the nul-termination\&.
.PP
If it is desired to write arbitrary data without the nul-termination, which is required for the user string, one can write a block data section using the function \fBsc_scda_fwrite_block\fP\&.
.SS "Encoding"
\fBscda\fP provides optional transparent, element-wise compression of data of file sections\&. The compression for writing can be enabled by passing true for \fBencode\fP to one of the functions
.PP
.IP "\(bu" 2
\fBsc_scda_fwrite_inline\fP,
.IP "\(bu" 2
\fBsc_scda_fwrite_block\fP,
.IP "\(bu" 2
\fBsc_scda_fwrite_array\fP and
.IP "\(bu" 2
\fBsc_scda_fwrite_varray\fP\&.
.PP
.PP
The compression on writing can be decided by the user for each file section separately\&. All parameters on the size of the data written to the file refer to the uncompressed data\&.
.PP
On reading it sufficies to pass \fBdecode\fP true to the function \fBsc_scda_fread_section_header\fP\&. Then the file section data is decompressed if it was compressed and otherwise the file section data is read raw\&. Again all data sizes in reading functions refer to the uncompressed data\&.
.PP
If \fBdecode\fP is false, the data is read raw even if it was written according to the compression convention\&.
.SS "Error management"
All \fBscda\fP functions that receive a file context have an output parameter called \fBerrcode\fP\&. In case of an unsuccessful function call, the respective function returns NULL instead of the file context and sets the output parameter \fBerrcode\fP to the respective error code\&. If such a case occurs, the file that is associated to the used file context is closed and the file context is deallocated\&.
.PP
The error code can be examined by the user using the two functions
.IP "\(bu" 2
\fBsc_scda_ferror_class\fP and
.IP "\(bu" 2
\fBsc_scda_ferror_string\fP\&.
.PP
.PP
If MPI is available \fBerrcode\fP may encode an MPI error code\&. In this case the two error examination functions output the error class and error string as it would be output by the corresponding MPI functions, respectively\&. Without MPI it is still possible that \fBerrcode\fP encodes an I/O operation related error code\&. This case does not differ concerning the error code examiniation\&. Moreover, \fBerrcode\fP can encode an error code related to \fBscda\fP, i\&.e\&. the I/O operations were successful but there is some violation of the \fBscda\fP format, workflow or API\&.
.PP
For more technical details on \fBerrcode\fP see the documentation of \fBsc_scda_ferror_t\fP\&. Furthermore, the \fBscda\fP format, workflow or API errors description can be found in the documentation of \fBsc_scda_ret\fP\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef struct sc_scda_fcontext \fBsc_scda_fcontext_t\fP"

.PP
Opaque context for writing and reading a libsc data file, i\&.e\&. a scda file\&. 
.SS "typedef struct \fBsc_scda_ferror\fP \fBsc_scda_ferror_t\fP"

.PP
Error values for the scda functions\&. An error value is a struct since the error can be related to the scda file format or to (MPI) I/O operations\&. The error code can be converted to a string by \fBsc_scda_ferror_string\fP, mapped to an error class by \fBsc_scda_ferror_class\fP and checked for success by \fBsc_scda_ferror_is_success\fP\&. The user can rely on these functions to parse \fBsc_scda_ferror\fP and does not need to access the members of this structure\&.
.PP
The parsing logic of \fBsc_scda_ferror_t\fP is that first \fBscdaret\fP is examined and if \fBscdaret\fP != \fBSC_SCDA_FERR_MPI\fP, we know that \fBmpiret\fP = 0\&. If \fBscdaret\fP = \fBSC_SCDA_FERR_MPI\fP, we know that an MPI error occurred and we can examine \fBmpiret\fP for more informartion\&.
.PP
Moreover, a valid \fBsc_scda_ferror\fP always satisfy that if \fBscdaret\fP = 0 then \fBmpiret\fP = 0 and if \fBscdaret\fP = \fBSC_SCDA_FERR_MPI\fP then \fBmpiret\fP !=0\&. 
.SS "typedef struct \fBsc_scda_params\fP \fBsc_scda_params_t\fP"

.PP
A parameter struct for the functions \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP\&. The struct may be extended in the future\&.
.PP
The option struct is a collective structure\&. If the options structure that is passed to a function is not the same on all processes, the whole following scda workflow has undefined behavior\&. type for \fBsc_scda_params\fP 
.SS "typedef enum \fBsc_scda_ret\fP \fBsc_scda_ret_t\fP"

.PP
Error values for scda-related errors\&. The error codes are part of the struct \fBsc_scda_ferror_t\fP and can be examined as part of this struct\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBsc_scda_ret\fP"

.PP
Error values for scda-related errors\&. The error codes are part of the struct \fBsc_scda_ferror_t\fP and can be examined as part of this struct\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISC_SCDA_FERR_SUCCESS \fP\fP
successful function call 
.TP
\fB\fISC_SCDA_FERR_FORMAT \fP\fP
File not conforming to the \fBscda\fP format\&. 
.TP
\fB\fISC_SCDA_FERR_USAGE \fP\fP
Incorrect workflow of an \fBscda\fP reading function\&. For example, the user might have identified a certain file section type using \fBsc_scda_fread_section_header\fP but then calls a function to read the section data for a different type\&. Another example is to try reading the data of a 'V' section before reading its element sizes\&. This error also occurs when the user tries to read section data before reading the section header\&. 
.TP
\fB\fISC_SCDA_FERR_DECODE \fP\fP
The decode parameter to \fBsc_scda_fread_section_header\fP is true but the file section header(s) encountered does not conform to the \fBscda\fP encoding convention\&. 
.TP
\fB\fISC_SCDA_FERR_ARG \fP\fP
An argument to a \fBscda\fP file function is invalid\&. This occurs for example when an essential pointer argument is NULL or a user string for writing is too long\&. 
.TP
\fB\fISC_SCDA_FERR_COUNT \fP\fP
A byte count error that may occur transiently on writing or the file is short on reading\&. 
.TP
\fB\fISC_SCDA_FERR_MPI \fP\fP
An MPI error occurred; see \fBmpiret\fP in the corresponding \fBsc_scda_ferror_t\fP\&. 
.TP
\fB\fISC_SCDA_FERR_LASTCODE \fP\fP
to define own error codes for a higher level application that is using sc_scda functions 
.SH "Function Documentation"
.PP 
.SS "int sc_scda_fclose (\fBsc_scda_fcontext_t\fP * fc, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Close a file opened for parallel write/read and the free the file context\&. This is a collective function\&. Every call of \fBsc_scda_fopen_write\fP and \fBsc_scda_fopen_read\fP must be matched by a corresponding call of \fBsc_scda_fclose\fP on the created file context\&. 
.PP
\fBNote\fP
.RS 4
All parameters are collective\&.
.RE
.PP
This function returns -1 on I/O errors\&. This function always frees the file context -- also in case of an error\&. 
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously created by \fBsc_scda_fopen_write\fP or \fBsc_scda_fopen_read\fP\&. This file context is freed after a call of this function\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function returns return 0\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBSC_SCDA_FERR_SUCCESS\fP for a successful call and -1 in case a of an error\&. See also \fBerrcode\fP argument\&. 
.RE
.PP

.SS "int sc_scda_ferror_class (\fBsc_scda_ferror_t\fP errcode, \fBsc_scda_ferror_t\fP * errclass)"

.PP
Translate a sc_scda error code to an error class\&. The semantic of error class and error code is the same as in the MPI standard, i\&.e\&. all error classes are error codes but potentially there are more error codes than error classes\&.
.PP
If \fBerrcode\fP is already an error class, \fBerrclass\fP if filled with \fBerrcode\fP\&.
.PP
This is a non-collective function\&.
.PP
\fBParameters\fP
.RS 4
\fIerrcode\fP An errcode that is output by a sc_scda function\&. 
.br
\fIerrclass\fP On output filled with the error class that corresponds to the given \fBerrcode\fP\&. See the function description above for more information on error classes and error codes in scda\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBSC_SCDA_FERR_SUCCESS\fP on success or something else on invalid arguments\&. 
.RE
.PP

.SS "int sc_scda_ferror_is_success (\fBsc_scda_ferror_t\fP errorcode)"

.PP
Check if a scda_errorcode_t encodes success\&. 
.PP
\fBParameters\fP
.RS 4
\fIerrorcode\fP An errcode that is output by a sc_scda function\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if \fBerrcode\fP encodes success and false otherwise\&. 
.RE
.PP

.SS "int sc_scda_ferror_string (\fBsc_scda_ferror_t\fP errcode, char * str, int * len)"

.PP
Translate a sc_scda error code/class to an error string\&. This is a non-collective function\&.
.PP
\fBParameters\fP
.RS 4
\fIerrcode\fP An errcode that is output by a sc_scda function\&. 
.br
\fIstr\fP At least sc_MPI_MAX_ERROR_STRING bytes\&. 
.br
\fIlen\fP On output the length of string on return\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBSC_SCDA_FERR_SUCCESS\fP on success or something else on invalid arguments\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fopen_read (\fBsc_MPI_Comm\fP mpicomm, const char * filename, char * user_string, size_t * len, \fBsc_scda_params_t\fP * params, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Open a file for reading and read the file header from the file\&. The file must exist and be at least of the size of the file header, i\&.e\&. \fBSC_SCDA_HEADER_BYTES\fP bytes\&. If the file has a file header that does not satisfy the sc_scda file header format, the function reports the error using SC_LERRORF, collectively close the file and deallocate the file context\&. In this case the function returns NULL on all ranks\&. A wrong file header format causes \fBSC_SCDA_FERR_FORMAT\fP as \fBerrcode\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters are collective\&.
.RE
.PP
This function aborts on the deprecated configuration of enabled MPI and disabled MPI I/O\&. All other valid configurations are supported\&.
.PP
This function differs from the one opening function for writing and reading introduced in this \fBscda\fP \fCpreprint\fP\&.
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP The MPI communicator that is used to open the parallel file\&. 
.br
\fIfilename\fP Path to parallel file that is to be created or to be opened\&. 
.br
\fIuser_string\fP At least \fBSC_SCDA_USER_STRING_BYTES\fP + 1 bytes\&. \fBuser_string\fP is filled with the read user string from file and is nul-terminated\&. 
.br
\fIlen\fP On output \fBlen\fP is set to the number of bytes written to \fBuser_string\fP excluding the terminating nul\&. 
.br
\fIparams\fP A parameter structure that provides the possibility to pass further options\&. See \fBsc_scda_params\fP for more details\&. It is valid to pass NULL for \fBparams\fP\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Newly allocated context to continue reading and eventually closing the file\&. NULL in case of error, i\&.e\&. errcode != \fBSC_SCDA_FERR_SUCCESS\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fopen_write (\fBsc_MPI_Comm\fP mpicomm, const char * filename, const char * user_string, size_t * len, \fBsc_scda_params_t\fP * params, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Open a file for writing and write the file header to the file\&. This function creates a new file or overwrites an existing one\&. It is collective and creates the file on a parallel file system\&. 
.PP
\fBNote\fP
.RS 4
All parameters are collective\&. This function leaves the file open if MPI is available\&. Independent of the availability of MPI the user can write one or more file sections before closing the file (context) using \fBsc_scda_fclose\fP\&.
.RE
.PP
It is the user's responsibility to write any further metadata of the file that is required by the application\&. This can be done by writing file sections\&. However, the user can use \fBsc_scda_fopen_read\fP to open a not already opened file and then use \fBsc_scda_fread_section_header\fP and skipping the respective data bytes using the respective read functions sc_scda_fread_*_data to parse the structure of a given file and some metadata that is written by sc_scda\&.
.PP
This function aborts on the deprecated configuration of enabled MPI and disabled MPI I/O\&. All other valid configurations are supported\&.
.PP
This function differs from the one opening function for writing and reading introduced in this \fBscda\fP \fCpreprint\fP\&.
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP The MPI communicator that is used to open the parallel file\&. 
.br
\fIfilename\fP Path to parallel file that is to be created or to be opened\&. 
.br
\fIuser_string\fP At most \fBSC_SCDA_USER_STRING_BYTES\fP + 1 bytes in a nul-terminated string\&. See the 'User Strings' section in the detailed description of this file for more information\&. 
.br
\fIlen\fP The number of bytes in \fBuser_string\fP excluding the terminating nul\&. On NULL as input \fBuser_string\fP is expected to be a nul-terminated C string\&. 
.br
\fIparams\fP A parameter structure that provides the possibility to pass further options\&. See \fBsc_scda_params\fP for more details\&. It is valid to pass NULL for \fBparams\fP\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Newly allocated context to continue writing and eventually closing the file\&. NULL in case of error, i\&.e\&. errcode != \fBSC_SCDA_FERR_SUCCESS\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fread_array_data (\fBsc_scda_fcontext_t\fP * fc, \fBsc_array_t\fP * array_data, \fBsc_array_t\fP * elem_counts, size_t elem_size, int indirect, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Read the data of a fixed-size array\&. This is a collective function\&. This function is only valid to call directly after a successful call of \fBsc_scda_fread_section_header\fP\&. This preceding call gives also the required \fBelem_size\fP and the global number of array elements\&. The user must pass a parallel partition of the array elements by \fBelem_counts\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBarray_data\fP are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_read\fP\&. 
.br
\fIarray_data\fP If \fBindirect\fP is false, a \fBsc_array\fP with element count equals to the p-th entry of \fBelem_counts\fP for p being the calling rank\&. The element size must be equal to \fBelem_size\fP\&. If \fBindirect\fP is true, a \fBsc_array\fP with the same element count as for \fBindirect\fP false but with sizeof (sc_array_t) as element size\&. Each array element is then again a \fBsc_array\fP but with element count 1 and element size \fBelem_size\fP\&. The data can be skipped on each process by locally passing NULL\&. 
.br
\fIelem_counts\fP An \fBsc_array\fP that must be equal on all ranks\&. The element count of \fBelem_counts\fP must be the mpisize of the MPI communicator that was used to create \fBfc\fP\&. The element size of the \fBsc_array\fP must be equal to sizeof (\fBsc_scda_ulong\fP)\&. The \fBsc_array\fP must contain the local array elements counts\&. That is why it induces the partition that is used to read the array data in parallel\&. The sum of all array elements must be equal to elem_count as retrieved from \fBsc_scda_fread_section_header\fP\&. 
.br
\fIelem_size\fP The element size of one array element on number of bytes\&. Must be the same on all ranks and as retrieved from \fBsc_scda_fread_section_header\fP\&. 
.br
\fIindirect\fP A Boolean to determine whether \fBarray_data\fP must be a \fBsc_array\fP of sc_arrays to read indirectly and in particular to potentially non-contigous memory\&. See the documentation of the parameter \fBarray_data\fP for more information\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue reading and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fread_block_data (\fBsc_scda_fcontext_t\fP * fc, \fBsc_array_t\fP * block_data, size_t block_size, int root, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Read the data of a block of given size\&. This is a collective function\&. This function is only valid to call directly after a successful call of \fBsc_scda_fread_section_header\fP\&. This preceding call gives also the required \fBblock_size\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBblock_data\fP are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_read\fP\&. 
.br
\fIblock_data\fP A \fBsc_array\fP with element count 1 and element size \fBblock_size\fP\&. On output the \fBsc_array\fP is filled with the block data of the read block data section\&. 
.br
\fIblock_size\fP The number of bytes of the block as retrieved from the preceding call of \fBsc_scda_fread_section_header\fP\&. 
.br
\fIroot\fP An integer between 0 and mpisize exclusive of the MPI communicator that was used to create \fBfc\fP\&. \fBroot\fP indicates the MPI rank on that \fBblock_data\fP is read from the file\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue reading and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fread_inline_data (\fBsc_scda_fcontext_t\fP * fc, \fBsc_array_t\fP * data, int root, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Read the data of an inline data section\&. This is a collective function\&. This function is only valid to call directly after a successful call of \fBsc_scda_fread_section_header\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBdata\fP are collective\&.
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_read\fP\&. 
.br
\fIdata\fP Exactly 32 bytes on the rank \fBroot\fP or NULL on \fBroot\fP to not read the bytes\&. In the first case the \fBsc_array\fP must have an element count of 1 and an element size 32\&. The parameter is ignored on all ranks unequal to \fBroot\fP\&. 
.br
\fIroot\fP An integer between 0 and mpisize exclusive of the MPI communicator that was used to create \fBfc\fP\&. \fBroot\fP indicates the MPI rank on that \fBdata\fP is read from the file\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue reading and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fread_section_header (\fBsc_scda_fcontext_t\fP * fc, char * user_string, size_t * len, char * type, size_t * elem_count, size_t * elem_size, int * decode, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Read the next file section header\&. This is a collective function\&. This functions reads the next file section header and provides the user information on the subsequent file section that can be used to read the actual data in a next calling depending on the file section type one (or for a variable-size array two) functions out of \fBsc_scda_fread_block_data\fP, \fBsc_scda_fread_array_data\fP, \fBsc_scda_fread_varray_sizes\fP and \fBsc_scda_fread_varray_data\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters are collective\&.
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_read\fP\&. 
.br
\fIuser_string\fP At least \fBSC_SCDA_USER_STRING_BYTES\fP +1 bytes\&. \fBuser_string\fP is filled with the read user string from file and is nul-terminated\&. 
.br
\fIlen\fP On output \fBlen\fP is set to the number of bytes written to \fBuser_string\fP excluding the terminating nul\&. 
.br
\fItype\fP On output this char is set to 'I' (inline data), 'B' (block of given size), 'A' (fixed-size array) or 'V' (variable-size array) depending on the file section type\&. 
.br
\fIelem_count\fP On output set to the global number of array elements if \fBtype\fP equals 'A' or 'V'\&. For 'I' and 'B' as \fBtype\fP, \fBelem_count\fP is set 0\&. 
.br
\fIelem_size\fP On output set to the byte count of the array elements if \fBtype\fP is 'A' and for the \fBtype\fP 'B' the number of bytes\&. Otherwise set to 0\&. 
.br
\fIdecode\fP On input a Boolean to decide whether the file section shall possibly be interpreted as a compressed section, i\&.e\&. they were written by a sc_scda_fwrite_* function with encode set to true\&. For \fBdecode\fP true as input the file section is interpreted as a compressed file section if the type and user string of the first raw file section satisfiy the compression convention\&. If the compression convention is not satisfied the data is read raw\&. For false as input the data will be read raw by the subsequent sc_scda_fread_* calls\&. The output value is always false if the input was set to false\&. Otherwise, the output is a Boolean that indicates if the nex file section contains a file section type and user string matching the compression convention\&. The subsequent sc_scda_fread_* calls do not require any adjustment dependent on \fBdecode\fP\&. See also the 'Encoding' section in the detailed description in this file\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue reading and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fread_varray_data (\fBsc_scda_fcontext_t\fP * fc, \fBsc_array_t\fP * array_data, \fBsc_array_t\fP * elem_counts, \fBsc_array_t\fP * elem_sizes, \fBsc_array_t\fP * proc_sizes, int indirect, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Read the data of a variable-size array\&. This is a collective function\&. This function is only valid to call directly after a successful call of \fBsc_scda_fread_varray_sizes\fP\&. This preceding call gives also the required \fBelem_sizes\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBarray_data\fP and \fBelem_sizes\fP are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_read\fP\&. 
.br
\fIarray_data\fP Let p be the calling rank\&. If \fBindirect\fP is false, \fBarray_data\fP must have element count 1 and as element size the p-th entry of \fBproc_sizes\fP\&. On output the data of the array is set to the local array elements conforming with \fBelem_counts\fP, \fBproc_sizes\fP and \fBelem_sizes\fP\&. If \fBindirect\fP is true, \fBarray_data\fP must be a \fBsc_array\fP with element count equal to the p-th array entry of \fBelem_counts\fP and element size equal to sizeof (sc_array_t)\&. Each array element is again a \fBsc_array\fP\&. Now, with element count 1 and element size equals to the actual array element size as passed in \fBelem_sizes\fP\&. On output these arrays are filled with the actual elements of the read variable-size array\&. The data can be skipped on each process by locally passing NULL\&. 
.br
\fIelem_counts\fP An \fBsc_array\fP that must be equal on all ranks\&. The element count of \fBelem_counts\fP must be the mpisize of the MPI communicator that was used to create \fBfc\fP\&. The element size of the \fBsc_array\fP must be equal to sizeof (\fBsc_scda_ulong\fP)\&. The \fBsc_array\fP must contain the local array elements counts\&. That is why it induces the partition that is used to read the array data in parallel\&. The sum of all array elements must be equal to elem_count as retrieved from \fBsc_scda_fread_section_header\fP\&. 
.br
\fIelem_sizes\fP The local element sizes conforming to the array element partition \fBelem_counts\fP as retrieved from \fBsc_scda_fread_varray_sizes\fP\&. This parameter is ignored for ranks to which NULL for \fBarray_data\fP was passed\&. 
.br
\fIproc_sizes\fP An \fBsc_array\fP that must be equal on all ranks\&. The element count and element size must be the same as for \fBelem_counts\fP\&. The array must contain the overall byte count per rank conforming with the passed array element partition \fBelem_counts\fP and the local array element sizes in \fBelem_sizes\fP\&. This parameter can be computed using \fBsc_scda_proc_sizes\fP\&. 
.br
\fIindirect\fP A Boolean to determine whether \fBarray_data\fP must be a \fBsc_array\fP of sc_arrays to read indirectly and in particular to potentially non-contigous memory\&. See the documentation of the parameter \fBarray_data\fP for more information\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue reading and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fread_varray_sizes (\fBsc_scda_fcontext_t\fP * fc, \fBsc_array_t\fP * elem_sizes, \fBsc_array_t\fP * elem_counts, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Read the element sizes of a variable-size array\&. This is a collective function\&. This function is only valid to call directly after a successful call of \fBsc_scda_fread_section_header\fP\&. This preceding call gives also the for \fBelem_counts\fP required global number of array elements\&. The user must pass a parallel partition of the array elements by \fBelem_counts\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBelem_sizes\fP are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_read\fP\&. 
.br
\fIelem_sizes\fP A \fBsc_array\fP with element count equals to p-th entry of \fBelem_counts\fP for p being the calling rank\&. The element size must be sizeof (\fBsc_scda_ulong\fP)\&. On output the array is filled with the local array element byte counts, where locality is determined by \fBelem_counts\fP\&. The element sizes can be skipped on each process by locally passing NULL\&. 
.br
\fIelem_counts\fP An \fBsc_array\fP that must be equal on all ranks\&. The element count of \fBelem_counts\fP must be the mpisize of the MPI communicator that was used to create \fBfc\fP\&. The element size of the \fBsc_array\fP must be equal to sizeof (\fBsc_scda_ulong\fP)\&. The \fBsc_array\fP must contain the local array elements counts\&. That is why it induces the partition that is used to read the array data in parallel\&. The sum of all array elements must be equal to elem_count as retrieved from \fBsc_scda_fread_section_header\fP\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue reading and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fwrite_array (\fBsc_scda_fcontext_t\fP * fc, const char * user_string, size_t * len, \fBsc_array_t\fP * array_data, \fBsc_array_t\fP * elem_counts, size_t elem_size, int indirect, int encode, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Write a fixed-size array file section\&. This is a collective function\&. The fixed-size array is the simplest file section that enables the user to write and read data in parallel\&. This function writes an array of a given element global count and a fixed element size\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBarray_data\fP are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_write\fP\&. 
.br
\fIuser_string\fP At most \fBSC_SCDA_USER_STRING_BYTES\fP + 1 bytes in a nul-terminated string\&. See the 'User Strings' section in the detailed description of this file for more information\&. 
.br
\fIlen\fP The number of bytes in \fBuser_string\fP excluding the terminating nul\&. On NULL as input \fBuser_string\fP is expected to be a nul-terminated C string\&. 
.br
\fIarray_data\fP On rank p the p-th entry of \fBelem_counts\fP must be the element count of \fBarray_data\fP\&. The element size of the \fBsc_array\fP must be equal to \fBelem_size\fP if \fBindirect\fP is false\&. Otherwise, \fBarray_data\fP must be a \fBsc_array\fP of sc_arrays, i\&.e\&. a \fBsc_array\fP with element size sizeof (sc_array_t)\&. Each of the elements of \fBarray_data\fP is then a \fBsc_array\fP with element count 1 and element size \fBelem_size\fP\&. See also the documentation of the parameter \fBindirect\fP\&. 
.br
\fIelem_counts\fP An \fBsc_array\fP that must be equal on all ranks\&. The element count of \fBelem_counts\fP must be the mpisize of the MPI communicator that was used to create \fBfc\fP\&. The element size of the \fBsc_array\fP must be equal to sizeof (\fBsc_scda_ulong\fP)\&. The \fBsc_array\fP must contain the local array elements counts (\fBsc_scda_ulong\fP)\&. That is why it induces the partition that is used to write the array data in parallel\&. 
.br
\fIelem_size\fP The element size of one array element on number of bytes\&. Must be the same on all ranks\&. 
.br
\fIindirect\fP A Boolean to determine whether \fBarray_data\fP must be a \fBsc_array\fP of sc_arrays to write indirectly and in particular from potentially non-contigous memory\&. In the remaining case of \fBindirect\fP being false \fBarray_data\fP must be a \fBsc_array\fP with element size equals to \fBelem_size\fP that contains the actual array elements\&. 
.br
\fIencode\fP A Boolean to decide whether the file section is written compressed\&. This results in two written file sections that can be read without the encoding interpretation by using \fBsc_scda_fread_section_header\fP with decode set to false followed by the usual sc_scda_fread functions\&. The data can be read as passed to this function by using decode true in \fBsc_scda_fread_section_header\fP and calling the usual sc_scda_fread function\&. See also the 'Encoding' section in the detailed description in this file\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue writing and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fwrite_block (\fBsc_scda_fcontext_t\fP * fc, const char * user_string, size_t * len, \fBsc_array_t\fP * block_data, size_t block_size, int root, int encode, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Write a fixed-size block file section\&. This is a collective function\&. This function writes a data block of fixed size to the file\&. The \fBblock_data\fP is written on the MPI rank \fBroot\fP\&. The number of block bytes must be less or equal 10^{26} - 1\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBblock_data\fP are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_write\fP\&. 
.br
\fIuser_string\fP At most \fBSC_SCDA_USER_STRING_BYTES\fP + 1 bytes in a nul-terminated string\&. See the 'User Strings' section in the detailed description of this file for more information\&. 
.br
\fIlen\fP The number of bytes in \fBuser_string\fP excluding the terminating nul\&. On NULL as input \fBuser_string\fP is expected to be a nul-terminated C string\&. 
.br
\fIblock_data\fP On rank \fBroot\fP a \fBsc_array\fP with one element and element size equals to \fBblock_size\fP\&. On all other ranks the parameter is ignored\&. Since \fBsc_array_init\fP and the other \fBsc_array_t\fP initialization functions do not allow an element size of 0, block sections can not be empty\&. 
.br
\fIblock_size\fP The size of the data block in bytes\&. Must be less or equal than 10^{26} - 1\&. 
.br
\fIroot\fP An integer between 0 and mpisize of the MPI communicator that was used to create \fBfc\fP\&. \fBroot\fP indicates the MPI rank on that \fBblock_data\fP is written to the file\&. 
.br
\fIencode\fP A Boolean to decide whether the file section is written compressed\&. This results in two written file sections that can be read without the encoding interpretation by using \fBsc_scda_fread_section_header\fP with decode set to false followed by the usual sc_scda_fread functions\&. The data can be read as passed to this function by using decode true in \fBsc_scda_fread_section_header\fP and calling the usual sc_scda_fread function\&. See also the 'Encoding' section in the detailed description in this file\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue writing and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fwrite_inline (\fBsc_scda_fcontext_t\fP * fc, const char * user_string, size_t * len, \fBsc_array_t\fP * inline_data, int root, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Write an inline data section\&. This is a collective function\&. This function writes 32 bytes of user-defined data preceded by a file section header containing a user string\&. In contrast to other file sections the inline data section does not end with padded data bytes and therefore require exactly 32 bytes data from the user\&. This enables the user to implement custom file structuring or padding\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBdata\fP are collective\&.
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_write\fP\&. 
.br
\fIuser_string\fP At most \fBSC_SCDA_USER_STRING_BYTES\fP + 1 bytes in a nul-terminated string\&. See the 'User Strings' section in the detailed description of this file for more information\&. 
.br
\fIlen\fP The number of bytes in \fBuser_string\fP excluding the terminating nul\&. On NULL as input \fBuser_string\fP is expected to be a nul-terminated C string\&. 
.br
\fIinline_data\fP On the rank \fBroot\fP a \fBsc_array\fP with element count 1 and element size 32\&. On all other ranks this parameter is ignored\&. 
.br
\fIroot\fP An integer between 0 and mpisize exclusive of the MPI communicator that was used to create \fBfc\fP\&. \fBroot\fP indicates the MPI rank on that \fBinline_data\fP is written to the file\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue writing and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "\fBsc_scda_fcontext_t\fP* sc_scda_fwrite_varray (\fBsc_scda_fcontext_t\fP * fc, const char * user_string, size_t * len, \fBsc_array_t\fP * array_data, \fBsc_array_t\fP * elem_counts, \fBsc_array_t\fP * elem_sizes, \fBsc_array_t\fP * proc_sizes, int indirect, int encode, \fBsc_scda_ferror_t\fP * errcode)"

.PP
Write a variable-size array file section\&. This is a collective function\&. This function can be used instead of \fBsc_scda_fwrite_array\fP if the array elements do not have a constant element size in bytes\&. 
.PP
\fBNote\fP
.RS 4
All parameters except of \fBarray_data\fP and \fBelem_sizes\fP are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
This function returns NULL on I/O errors\&.
.PP
\fBParameters\fP
.RS 4
\fIfc\fP File context previously opened by \fBsc_scda_fopen_write\fP\&. 
.br
\fIuser_string\fP At most \fBSC_SCDA_USER_STRING_BYTES\fP + 1 bytes in a nul-terminated string\&. See the 'User Strings' section in the detailed description of this file for more information\&. 
.br
\fIlen\fP The number of bytes in \fBuser_string\fP excluding the terminating nul\&. On NULL as input \fBuser_string\fP is expected to be a nul-terminated C string\&. 
.br
\fIarray_data\fP Let p be the calling rank\&. If \fBindirect\fP is false, \fBarray_data\fP must have element count 1 and as element size the p-th entry of \fBproc_sizes\fP\&. The data of the array must be the local array elements conforming with \fBelem_counts\fP, \fBproc_sizes\fP and \fBelem_sizes\fP\&. If \fBindirect\fP is true, \fBarray_data\fP must be a \fBsc_array\fP with element count equal to the p-th array entry of \fBelem_counts\fP and element size equal to sizeof (sc_array_t)\&. Each array element is again a \fBsc_array\fP\&. Now, with element count 1 and element size equals to the actual array element size as passed in \fBelem_sizes\fP\&. 
.br
\fIelem_counts\fP An \fBsc_array\fP that must be equal on all ranks\&. The element count of \fBelem_counts\fP must be the mpisize of the MPI communicator that was used to create \fBfc\fP\&. The element size of the \fBsc_array\fP must be equal to sizeof (unint8_t)\&. The \fBsc_array\fP must contain the local array elements counts\&. That is why it induces the partition that is used to write the array data in parallel\&. 
.br
\fIelem_sizes\fP A \fBsc_array\fP with the element sizes for the local array elements\&. The \fBsc_array\fP has an element count of p-th entry of \fBelem_counts\fP for p being the calling rank\&. The element size is sizeof (\fBsc_scda_ulong\fP)\&. 
.br
\fIproc_sizes\fP An \fBsc_array\fP that must be equal on all ranks\&. The element count and element size must be the same as for \fBelem_counts\fP\&. The array must contain the overall byte count per rank conforming with the passed array element partition \fBelem_counts\fP and the local array element sizes in \fBelem_sizes\fP\&. This parameter can be computed using \fBsc_scda_proc_sizes\fP\&. 
.br
\fIindirect\fP A Boolean to determine whether \fBarray_data\fP must be a \fBsc_array\fP of sc_arrays to write indirectly and in particular from potentially non-contigous memory\&. In the remaining case of \fBindirect\fP being false \fBarray_data\fP must be a \fBsc_array\fP with the actual array elements as data as further explained in the documentation of \fBarray_data\fP\&. 
.br
\fIencode\fP A Boolean to decide whether the file section is written compressed\&. This results in two written file sections that can be read without the encoding interpretation by using \fBsc_scda_fread_section_header\fP with decode set to false followed by the usual sc_scda_fread functions\&. The data can be read as passed to this function by using decode true in \fBsc_scda_fread_section_header\fP and calling the usual sc_scda_fread function\&. See also the 'Encoding' section in the detailed description in this file\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to the input context \fBfc\fP on success\&. The context is used to continue writing and eventually closing the file\&. In case of any error, attempt to close the file and deallocate the context \fBfc\fP\&. 
.RE
.PP

.SS "void sc_scda_params_init (\fBsc_scda_params_t\fP * params)"

.PP
Initialize a scda parameter structure to the defaults\&. 
.PP
\fBParameters\fP
.RS 4
\fIparams\fP \fBsc_scda_params\fP structure that is filled with the default parameters\&. 
.RE
.PP

.SS "int sc_scda_proc_sizes (\fBsc_array_t\fP * elem_sizes, \fBsc_array_t\fP * elem_counts, \fBsc_array_t\fP * proc_sizes, \fBsc_scda_ferror_t\fP * errcode)"

.PP
This is a collective function to determine the processor sizes\&. The purpose of this function is determine the \fBproc_sizes\fP argument as required by \fBsc_scda_fread_varray_data\fP given the data that can be retrieved by calling \fBsc_scda_fread_varray_sizes\fP or as required by \fBsc_scda_fwrite_varray\fP given \fBelem_sizes\fP and \fBelem_counts\fP as passed to \fBsc_scda_fwrite_varray\fP\&. 
.PP
\fBNote\fP
.RS 4
All parameters are collective\&.
.RE
.PP
\fBWarning\fP
.RS 4
The API of this function will change in the next libsc version!
.RE
.PP
\fBParameters\fP
.RS 4
\fIelem_sizes\fP The \fBelem_sizes\fP array as retrieved by \fBsc_scda_fread_varray_sizes\fP or passed to \fBsc_scda_fwrite_varray\fP\&. 
.br
\fIelem_counts\fP The \fBelem_counts\fP array as retrieved by \fBsc_scda_fread_varray_sizes\fP or passed to \fBsc_scda_fwrite_varray\fP\&. 
.br
\fIproc_sizes\fP A \fBsc_array\fP with element size \fBsc_scda_ulong\fP that is resized on output to the length of \fBelem_sizes\fP and \fBelem_counts\fP\&. The array is filled with the number bytes per process\&. 
.br
\fIerrcode\fP An errcode that can be interpreted by \fBsc_scda_ferror_string\fP or mapped to an error class by \fBsc_scda_ferror_class\fP\&. \fBerrcode\fP encodes success if and only if the function does not return NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 in case of success and -1 otherwise\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
