.TH "src/sc_sort.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_sort.h \- Provide a parallel sort algorithm\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsc_psort\fP (\fBsc_MPI_Comm\fP mpicomm, void *base, size_t *nmemb, size_t size, int(*compar)(const void *, const void *))"
.br
.RI "Sort a distributed set of fixed-size data items in parallel\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provide a parallel sort algorithm\&. 

We use a variant of the bitonic sort algorithm\&. Within each process we rely on the system quick sort function\&. The partition of data on input is arbitrary and remains invariant\&. 
.SH "Function Documentation"
.PP 
.SS "void sc_psort (\fBsc_MPI_Comm\fP mpicomm, void * base, size_t * nmemb, size_t size, int(*)(const void *, const void *) compar)"

.PP
Sort a distributed set of fixed-size data items in parallel\&. This algorithm uses bitonic sort between processors and qsort locally\&.
.PP
This function is thread-safe if src/sc_config\&.h #defines SC_HAVE_QSORT_R\&. Otherwise, it uses a static read-only variable for the comparison function, and calling \fBsc_psort\fP concurrently is likely to fail\&.
.PP
The partition of the data can be arbitrary and is not changed\&.
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP Communicator to use\&. 
.br
\fIbase\fP Pointer to the process-local data items\&. 
.br
\fInmemb\fP Array of mpisize counts of data items\&. For each process, the number of its local items\&. This array must be identical on all processes\&. 
.br
\fIsize\fP Size in bytes of one data item\&. 
.br
\fIcompar\fP Comparison function to use; see man (3) qsort\&. Shall return < 0 if the first argument is less than the second, 0 if both are equal, and > 0 if the first is greater than the second\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
