.TH "sc_unique_counter" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_unique_counter
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstart_value\fP"
.br
.ti -1c
.RI "\fBsc_mempool_t\fP * \fBmempool\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
