.TH "sc_uint128" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_uint128 \- An unsigned 128 bit integer represented as two uint64_t\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_uint128\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBhigh_bits\fP"
.br
.RI "The more significant 64 bits\&. "
.ti -1c
.RI "uint64_t \fBlow_bits\fP"
.br
.RI "The less significant 64 bits\&. "
.in -1c
.SH "Detailed Description"
.PP 
An unsigned 128 bit integer represented as two uint64_t\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
