.TH "src/sc_uint128.h" 3 "Thu Mar 13 2025" "Version 2.8.6.361-d917" "libsc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sc_uint128.h \- Routines for managing unsigned 128 bit integers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsc_uint128\fP"
.br
.RI "An unsigned 128 bit integer represented as two uint64_t\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsc_uint128\fP \fBsc_uint128_t\fP"
.br
.RI "An unsigned 128 bit integer represented as two uint64_t\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsc_uint128_compare\fP (const void *a, const void *b)"
.br
.RI "Compare the sc_uint128_t \fIa\fP and the sc_uint128_t \fIb\fP\&. "
.ti -1c
.RI "int \fBsc_uint128_is_equal\fP (const \fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b)"
.br
.RI "Checks if the sc_uint128_t \fIa\fP and the sc_uint128_t \fIb\fP are equal\&. "
.ti -1c
.RI "void \fBsc_uint128_init\fP (\fBsc_uint128_t\fP *a, uint64_t high, uint64_t low)"
.br
.RI "Initializes an unsigned 128 bit integer to a given value\&. "
.ti -1c
.RI "int \fBsc_uint128_chk_bit\fP (const \fBsc_uint128_t\fP *input, int exponent)"
.br
.RI "Returns the bit_number-th bit of \fIinput\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_set_bit\fP (\fBsc_uint128_t\fP *a, int exponent)"
.br
.RI "Sets the exponent-th bit of \fIa\fP to one and keep all other bits\&. "
.ti -1c
.RI "void \fBsc_uint128_copy\fP (const \fBsc_uint128_t\fP *input, \fBsc_uint128_t\fP *output)"
.br
.RI "Copies an initialized sc_uint128_t to a sc_uint128_t\&. "
.ti -1c
.RI "void \fBsc_uint128_add\fP (const \fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b, \fBsc_uint128_t\fP *result)"
.br
.RI "Adds the uint128_t \fIb\fP to the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_sub\fP (const \fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b, \fBsc_uint128_t\fP *result)"
.br
.RI "Subtracts the uint128_t \fIb\fP from the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_bitwise_neg\fP (const \fBsc_uint128_t\fP *a, \fBsc_uint128_t\fP *result)"
.br
.RI "Calculates the bitwise negation of the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_bitwise_or\fP (const \fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b, \fBsc_uint128_t\fP *result)"
.br
.RI "Calculates the bitwise or of the uint128_t \fIa\fP and \fIb\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_bitwise_and\fP (const \fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b, \fBsc_uint128_t\fP *result)"
.br
.RI "Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_shift_right\fP (const \fBsc_uint128_t\fP *input, int shift_count, \fBsc_uint128_t\fP *result)"
.br
.RI "Calculates the bit right shift of uint128_t \fIinput\fP by shift_count bits\&. "
.ti -1c
.RI "void \fBsc_uint128_shift_left\fP (const \fBsc_uint128_t\fP *input, int shift_count, \fBsc_uint128_t\fP *result)"
.br
.RI "Calculates the bit left shift of uint128_t \fIinput\fP by shift_count bits\&. "
.ti -1c
.RI "void \fBsc_uint128_add_inplace\fP (\fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b)"
.br
.RI "Adds the uint128 \fIb\fP to the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_sub_inplace\fP (\fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b)"
.br
.RI "Subtracts the uint128_t \fIb\fP from the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_bitwise_or_inplace\fP (\fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b)"
.br
.RI "Calculates the bitwise or of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. "
.ti -1c
.RI "void \fBsc_uint128_bitwise_and_inplace\fP (\fBsc_uint128_t\fP *a, const \fBsc_uint128_t\fP *b)"
.br
.RI "Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Routines for managing unsigned 128 bit integers\&. 

We do this to have a portable way on systems that have no native support\&. 
.SH "Function Documentation"
.PP 
.SS "void sc_uint128_add (const \fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b, \fBsc_uint128_t\fP * result)"

.PP
Adds the uint128_t \fIb\fP to the uint128_t \fIa\fP\&. \fIresult\fP == \fIa\fP or \fIresult\fP == \fIb\fP is not allowed\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.br
\fIresult\fP A pointer to a sc_uint128_t\&. The sum \fIa\fP + \fIb\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void sc_uint128_add_inplace (\fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b)"

.PP
Adds the uint128 \fIb\fP to the uint128_t \fIa\fP\&. The result is saved in \fIa\fP\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. \fIa\fP will be overwritten by \fIa\fP + \fIb\fP\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.RE
.PP

.SS "void sc_uint128_bitwise_and (const \fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b, \fBsc_uint128_t\fP * result)"

.PP
Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. \fIa\fP == \fIresult\fP is allowed\&. Furthermore, \fIa\fP == \fIresult\fP and/or \fIb\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.br
\fIresult\fP A pointer to a sc_uint128_t\&. The bitwise and of \fIa\fP and \fIb\fP will be saved\&. in \fIresult\fP\&. 
.RE
.PP

.SS "void sc_uint128_bitwise_and_inplace (\fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b)"

.PP
Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. The bitwise and will be saved in \fIa\fP\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.RE
.PP

.SS "void sc_uint128_bitwise_neg (const \fBsc_uint128_t\fP * a, \fBsc_uint128_t\fP * result)"

.PP
Calculates the bitwise negation of the uint128_t \fIa\fP\&. \fIa\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIresult\fP A pointer to a sc_uint128_t\&. The bitwise negation of \fIa\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void sc_uint128_bitwise_or (const \fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b, \fBsc_uint128_t\fP * result)"

.PP
Calculates the bitwise or of the uint128_t \fIa\fP and \fIb\fP\&. \fIa\fP == \fIresult\fP is allowed\&. Furthermore, \fIa\fP == \fIresult\fP and/or \fIb\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.br
\fIresult\fP A pointer to a sc_uint128_t\&. The bitwise or of \fIa\fP and \fIb\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void sc_uint128_bitwise_or_inplace (\fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b)"

.PP
Calculates the bitwise or of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. The bitwise or will be saved in \fIa\fP\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.RE
.PP

.SS "int sc_uint128_chk_bit (const \fBsc_uint128_t\fP * input, int exponent)"

.PP
Returns the bit_number-th bit of \fIinput\fP\&. This function checks a bit of an existing, initialized value\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a sc_uint128_t\&. 
.br
\fIexponent\fP The bit (counted from the right hand side) that is checked by logical and\&. Require 0 <= \fIbit_number\fP < 128\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if the checked bit is set, false if not\&. 
.RE
.PP

.SS "int sc_uint128_compare (const void * a, const void * b)"

.PP
Compare the sc_uint128_t \fIa\fP and the sc_uint128_t \fIb\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns -1 if a < b, 1 if a > b and 0 if a == b\&. 
.RE
.PP

.SS "void sc_uint128_copy (const \fBsc_uint128_t\fP * input, \fBsc_uint128_t\fP * output)"

.PP
Copies an initialized sc_uint128_t to a sc_uint128_t\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to the \fBsc_uint128\fP that is copied\&. 
.br
\fIoutput\fP A pointer to a sc_uint128_t\&. The high and low bits of \fIoutput\fP will be set to the high and low bits of \fIinput\fP, respectively\&. 
.RE
.PP

.SS "void sc_uint128_init (\fBsc_uint128_t\fP * a, uint64_t high, uint64_t low)"

.PP
Initializes an unsigned 128 bit integer to a given value\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to the sc_uint128_t that will be initialized\&. 
.br
\fIhigh\fP The given high bits to initialize \fIa\fP\&. 
.br
\fIlow\fP The given low bits to initialize \fIa\fP\&. 
.RE
.PP

.SS "int sc_uint128_is_equal (const \fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b)"

.PP
Checks if the sc_uint128_t \fIa\fP and the sc_uint128_t \fIb\fP are equal\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a true value if \fIa\fP and \fIb\fP are equal, false otherwise\&. 
.RE
.PP

.SS "void sc_uint128_set_bit (\fBsc_uint128_t\fP * a, int exponent)"

.PP
Sets the exponent-th bit of \fIa\fP to one and keep all other bits\&. This function modifies an existing, initialized value\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIexponent\fP The bit (0-based from the rightmost bit) that is set to one by logical or\&. 0 <= \fIexponent\fP < 128\&. 
.RE
.PP

.SS "void sc_uint128_shift_left (const \fBsc_uint128_t\fP * input, int shift_count, \fBsc_uint128_t\fP * result)"

.PP
Calculates the bit left shift of uint128_t \fIinput\fP by shift_count bits\&. We shift in zeros from the right\&. If \fIshift_count\fP >= 128, \fIresult\fP is 0\&. All bits left from the 127th bit (counted zero based from the right hand side) drop out\&. \fIinput\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a sc_uint128_t\&. 
.br
\fIshift_count\fP Bits to shift\&. \fIshift_count\fP >= 0\&. 
.br
\fIresult\fP A pointer to a sc_uint128_t\&. The left shifted number will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void sc_uint128_shift_right (const \fBsc_uint128_t\fP * input, int shift_count, \fBsc_uint128_t\fP * result)"

.PP
Calculates the bit right shift of uint128_t \fIinput\fP by shift_count bits\&. We shift in zeros from the left\&. If \fIshift_count\fP >= 128, \fIresult\fP is 0\&. All bits right from the zeroth bit (counted from the right hand side) drop out\&. \fIinput\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a sc_uint128_t\&. 
.br
\fIshift_count\fP Bits to shift\&. \fIshift_count\fP >= 0\&. 
.br
\fIresult\fP A pointer to a sc_uint128_t\&. The right shifted number will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void sc_uint128_sub (const \fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b, \fBsc_uint128_t\fP * result)"

.PP
Subtracts the uint128_t \fIb\fP from the uint128_t \fIa\fP\&. This function assumes that the result is >= 0\&. \fIresult\fP == \fIa\fP or \fIresult\fP == \fIb\fP is not allowed\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.br
\fIresult\fP A pointer to a sc_uint128_t\&. The difference \fIa\fP - \fIb\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void sc_uint128_sub_inplace (\fBsc_uint128_t\fP * a, const \fBsc_uint128_t\fP * b)"

.PP
Subtracts the uint128_t \fIb\fP from the uint128_t \fIa\fP\&. The result is saved in \fIa\fP\&. \fIa\fP == \fIb\fP is allowed\&. This function assumes that the result is >= 0\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a sc_uint128_t\&. \fIa\fP will be overwritten by \fIa\fP - \fIb\fP\&. 
.br
\fIb\fP A pointer to a sc_uint128_t\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libsc from the source code\&.
