.TH "forest" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
forest \- The forest workflow 
An overview of the forest of octrees creation and manipulation\&.
.SS "Introduction"
The forest data structure (cf\&. \fBp4est_t\fP (2D), \fBp8est_t\fP (3D)) encodes the mesh topology as a forest of quadtrees (2D) or octrees (3D)\&. The forest can be created given a connectivity (cf\&. the \fBconnectivity page\fP)\&. In contrast to the connectivity data structure, the forest data structure is distributed in memory when MPI is activated, i\&.e\&. the forest data structure only stores leaves that are processor-local according to the parallel mesh partition\&. This page provides an overview of the typical workflow in \fBp4est\fP to create and manipulate such a forest to represent the desired mesh topology\&.
.SS "Forest creation"
A fundamental step in a typical workflow with \fBp4est\fP is to create a forest of quadtrees or octrees\&. The \fBp4est\fP library offers the functions \fBp4est_new\fP (2D), \fBp8est_new\fP (3D) and \fBp4est_new_ext\fP (2D), \fBp8est_new_ext\fP (3D) (versions with additional parameters) to create such a forest\&.
.PP
Creating a forest that encodes a partition-independent 2D mesh: 
.PP
.nf
/* user data structure for the data inside each forest leaf */
typedef struct my_user_data {
 int foo;
}
my_user_data_t;

/* callback function to initialize the data in each forest leaf */
static void
my_quadrant_init (p4est, which_tree, quadrant) {
 ((my_user_data_t *) quadrant->p\&.user_data)->foo = *(int *) p4est->user_pointer;
}

static int foo = 17489;
void *user_pointer = &foo;

forest = p4est_new_ext (mpicomm, connectivity, 0, level, 1,
                        sizeof (my_user_data_t), my_quadrant_init, user_pointer);

.fi
.PP
.PP
\fBmpicomm\fP is an MPI communicator (cf\&. \fBsimple/simple2\&.c\fP for a usage example)\&.
.PP
The highest occurring level of refinement is specified by the \fBlevel\fP parameter\&. If it is zero or negative, there will be no refinement beyond the coarse mesh connectivity at this point\&.
.PP
We provide an optional callback mechanism (cf\&. \fBmy_quadrant_init\fP above) to initialize the user data that we allocate inside each forest leaf\&.
.PP
The \fBuser_pointer\fP is assigned to the member of the same name in the created \fBforest\fP (before the init callback function is called the first time)\&. This is a way to keep the application state referenced in a forest object\&.
.PP
The resulting \fBforest\fP object in the above example represents a uniform mesh (with the coarse mesh topolgy as encoded in the passed \fBconnectivity\fP) refined to the specified level\&. It is also possible to create a partition-dependent mesh by changing the two parameters set to 0 and 1 in the example above\&. However, for maximal reproducibility, we recommend to create a partition-independent mesh\&.
.PP
For more details on the function parameters see \fBp4est\&.h\fP and \fBp4est_extended\&.h\fP -- as always, the 3D equivalents are prefixed with \fBp8est\fP\&.
.SS "Manipulate the forest's refinement structure and partition"
There are two types of forest manipulation\&. The first is to manipulate the mesh that the forest represents and the second is to the manipulate the parallel partition of the forest, i\&.e\&. the parallel distribution of the leaves\&. All forest manipulation functions in \fBp4est\fP manipulate either the mesh or the partition but not both\&. This means that the functions for changing the refinement structure do not involve MPI communication\&.
.PP
All forest manipulation functions are collective over the MPI communicator passed during the forest creation\&.
.SS "Functions to manipulate forest's refinement structure"
.IP "\(bu" 2
\fBp4est_refine\fP Refinement of specific hypercubes given a refinement criterion, i\&.e\&. a user-defined callback function\&. While it is possible to enable recursive refinement, in practice we set it to non-recursive and loop around the function\&. This has the advantage that we can repartition in parallel after every iteration\&.
.IP "\(bu" 2
\fBp4est_coarsen\fP Coarsen a family of hypercubes given a coarsening criterion, i\&.e\&. a user-defined callback function\&. This function is partition-dependent if families of leaves are split across processes\&. Partition-independent forests created using \fBp4est_new\fP or \fBp4est_new_ext\fP as described above do not split families among proccesses\&. In the case that the forest's partition is adjusted, the last call of \fBp4est_partition\fP or \fBp4est_partition_ext\fP must be with allow_for_coarsening activated (cf\&. the next section) to ensure partition-independent coarsening results\&.
.IP "\(bu" 2
\fBp4est_balance\fP Ensure a 2:1 balance of the size differences of neighboring elements in a forest by refining mesh elements\&. This is accomplished by adding some more refinement where needed\&.
.PP
.PP
For all three ways of manipulating the forest's refinement structure the user may pass a \fBcallback\fP to initialize the user data of the newly created leaves\&.
.PP
Except of the mentioned special requirements for \fBp4est_coarsen\fP all refinement structure manipulating functions are independent of the forest's partition\&.
.PP
All of the listed functions have a version with extended options declared in \fBp4est_extended\&.h\fP (2D) and \fBp8est_extended\&.h\fP (3D)\&.
.SS "Function to manipulate the forest's partition"
The forest's partition is a parallel, disjoint and linear subdivision of the forest's leaves among the MPI processes\&. The partition is computed using the Morton curve as space-filling curve\&.
.PP
The functions \fBp4est_new\fP and \fBp4est_new_ext\fP create a uniformly partitioned forest with respect to the leaf count\&. However, after manipulating the forest's refinement structure, the partition may no longer be uniform\&. Another reason for manipulating the partition is that the application may desire to partition the leaves according to the work associated with them instead of the leaf count\&. Manipulating the partition incurs MPI communication since the leaves and their data are shipped\&.
.PP
.IP "\(bu" 2
\fBp4est_partition\fP Partition the forest in parallel, equally with respect to the leaf count or according to a given user-defined weight per leaf\&. The parameter \fBallow_for_coarsening\fP can be used to ensure that families of leaves are assigned to the same process -- cf\&. \fBp4est_coarsen\fP\&.
.PP
.SS "Examples of forest workflows"
Simple examples of typical forest workflows can be found in \fBsimple/simple2\&.c\fP (2D) and \fBsimple/simple3\&.c\fP (3D)\&. A more application-oriented example can be found in \fBsteps/p4est_step3\&.c\fP (2D) and \fBsteps/p8est_step3\&.c\fP (3D)\&. This example shows in particular the handling of leaf data for a simple advection solver\&. 
