.TH "ghost" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghost \- The ghost layer 
An overview of the ghost layer functionalities\&.
.SS "The basic idea and definition"
Mesh-based computations may require access to neighboring elements\&. An example of such a computation using a ghost layer can be found in \fBsteps/p4est_step3\&.c\fP (2D) and \fBsteps/p8est_step3\&.c\fP (3D) -- a simple parallel advection solver\&. For parallel computations, we we need to ensure that neighboring mesh elements, which are not local to the current process, become accessible locally\&. The need of process-neighboring mesh elements leads to the definition of the ghost (a\&.k\&.a\&. halo) layer: The ghost layer is the set of all remote, i\&.e\&. non-local, mesh elements that are adjacent to the process-local mesh elements\&. This data structure is ideally suited to establish the communication pattern between mesh-adjacent parallel processes\&. The ghost layer contains all information required to determine all sender-receiver pairs without additional MPI communication\&. The pattern is necessarily symmetric: Each sender of a pair is also a receiver and vice versa\&.
.SS "Constructing the ghost layer"
\fB\fBp4est\fP\fP provides the functions \fBp4est_ghost_new\fP (2D), \fBp8est_ghost_new\fP (3D) to construct a ghost layer\&. A ghost layer can be constructed from a valid \fBinput_p4est\fP (cf\&. \fBp4est_t\fP (2D), \fBp8est_t\fP (3D) and \fBp4est_is_valid\fP (2D), \fBp8est_is_valid\fP (3D))\&. The forest does not need to be 2:1 balanced\&.
.PP
The second and last required parameter to construct a ghost layer is a \fBbtype\fP (cf\&. \fBp4est_connect_type_t\fP (2D), \fBp8est_connect_type_t\fP (3D)) that specifies if the ghost layer should collect face adjacency, face and edge adjacency in 3D, or full adjacency including corner neighbors\&.
.PP
Ghost layer construction in 2D: 
.PP
.RS 4
\fCghost = p4est_ghost_new (input_p4est, btype)\fP 
.RE
.PP
The returned ghost layer object is explained in the following section\&.
.SS "The ghost data structure"
The ghost layer object (cf\&. \fBp4est_ghost_t\fP (2D), \fBp8est_ghost_t\fP (3D)) can be queried and searched without accessing the original \fBinput_p4est\fP\&. It is read-only immutable and must be destroyed when no longer needed (cf\&. \fBp4est_ghost_destroy\fP (2D), \fBp8est_ghost_destroy\fP (3D))\&.
.SS "Elements of the ghost layer"
The ghost layer is a public struct with documented entries, most of them arrays\&. The \fB2D\fP and \fB3D\fP declarations are structurally identical: Linear tree storage is dimension independent, and ghost elements are ordered ascending just as mesh elements\&. We may index into the element storage by window start and offset indices\&. We may also use binary search in the linear order to find ghost elements\&.
.PP
The elements of the ghost layer start with the \fBmpisize\fP and \fBnum_trees\fP\&. They store the number of MPI ranks and the number of trees of the ghost layer\&. Both elements are as in the \fBp4est\fP that was used to construct the ghost layer\&.
.PP
The array \fBghosts\fP stores the ghost elements that form the ghost layer of the process-local elements\&. The \fBquadrants\fP in the \fBghosts\fP array store their tree index and the local number in the owner's numbering in \fBpiggy3\fP\&. The \fBghosts\fP array is windowed by the two arrays \fBtree_offsets\fP and \fBproc_offsets\fP\&. Therefore, the MPI rank and the tree number of each element in \fBghosts\fP can be deduced\&. Naturally, some trees or processes may have zero ghost elements for a given process, in which case the window has length zero\&.
.PP
The \fBmirrors\fP array stores all local quadrants that are ghosts to remote processes, sometimes called the (inside) parallel boundary elements\&. \fBghosts\fP can be considered as the outside parallel boundary elements\&. One mirror quadrant may be ghost to more than one remote process\&. Thus, the indexing structure is slightly less direct than for \fBghosts\fP: We have an array \fBmirror_proc_mirrors\fP that contains one set of indices into the \fBmirrors\fP for each remote process\&. The array \fBmirror_proc_offsets\fP indexes into these sets, which vary in length by the remote process\&. As for \fBghosts\fP, we have for \fBmirrors\fP also an array with tree offsets, namely the array \fBmirror_tree_offsets\fP\&.
.SS "Find more information"
For further elements of the ghost data structure see also \fBp4est_ghost_t\fP and \fBp8est_ghost_t\fP and for parallel ghost data exchange functions see the respective functions in \fBp4est_ghost\&.h\fP (2D) and \fBp8est_ghost\&.h\fP (3D)\&.
.SS "Example of ghost usage"
Besides the already mentioned parallel advection solver in \fB2D\fP and \fB3D\fP, one can also find a simple synthetic usage examples of ghost in \fBtimings/timings2\&.c\fP (2D) and \fBtimings/timings3\&.c\fP (3D)\&. 
