.TH "p4est_ghost" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_ghost \- Quadrants that neighbor the local domain\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_ghost\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmpisize\fP"
.br
.RI "MPI size of the ghost\&. "
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBnum_trees\fP"
.br
.RI "number of trees of the ghost "
.ti -1c
.RI "\fBp4est_connect_type_t\fP \fBbtype\fP"
.br
.RI "which neighbors are in the ghost layer "
.ti -1c
.RI "sc_array_t \fBghosts\fP"
.br
.RI "An array of \fBp4est_quadrant_t\fP quadrants which make up the ghost layer around \fB\fBp4est\fP\fP\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBtree_offsets\fP"
.br
.RI "num_trees + 1 ghost indices "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBproc_offsets\fP"
.br
.RI "mpisize + 1 ghost indices "
.ti -1c
.RI "sc_array_t \fBmirrors\fP"
.br
.RI "An array of local quadrants that touch the parallel boundary from the inside, i\&.e\&., that are ghosts in the perspective of at least one other processor\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBmirror_tree_offsets\fP"
.br
.RI "num_trees + 1 mirror indices "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBmirror_proc_mirrors\fP"
.br
.RI "indices into mirrors grouped by outside processor rank and ascending within each rank "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBmirror_proc_offsets\fP"
.br
.RI "mpisize + 1 indices into mirror_proc_mirrors "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBmirror_proc_fronts\fP"
.br
.RI "like mirror_proc_mirrors, but limited to the outermost octants\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBmirror_proc_front_offsets\fP"
.br
.RI "NULL until p4est_ghost_expand is called\&. "
.in -1c
.SH "Detailed Description"
.PP 
Quadrants that neighbor the local domain\&. 

See also the page \fBThe ghost layer\fP for general information\&. 
.PP
\fBExamples\fP
.in +1c
\fBsteps/p4est_step3\&.c\fP, and \fBtimings/timings2\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "sc_array_t p4est_ghost::ghosts"

.PP
An array of \fBp4est_quadrant_t\fP quadrants which make up the ghost layer around \fB\fBp4est\fP\fP\&. Their piggy3 (cf\&. \fBp4est_quadrant::p4est_quadrant_data\fP) data member is filled with their owner's tree and local number (cumulative over trees)\&. Quadrants are ordered in \fBp4est_quadrant_compare_piggy\fP order\&. These are quadrants inside the neighboring tree, i\&.e\&., \fCp4est_quadrant_is_inside\fP is true for the quadrant and the neighboring tree\&. 
.SS "\fBp4est_locidx_t\fP* p4est_ghost::mirror_proc_fronts"

.PP
like mirror_proc_mirrors, but limited to the outermost octants\&. This is NULL until p4est_ghost_expand is called 
.SS "sc_array_t p4est_ghost::mirrors"

.PP
An array of local quadrants that touch the parallel boundary from the inside, i\&.e\&., that are ghosts in the perspective of at least one other processor\&. The storage convention is the same as for \fCghosts\fP above\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
