.TH "src/p4est_communication.h" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/p4est_communication.h \- Parallel messaging and support code\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <p4est\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBp4est_transfer_context\fP"
.br
.RI "Context data to allow for split begin/end data transfer\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBp4est_transfer_context\fP \fBp4est_transfer_context_t\fP"
.br
.RI "Context data to allow for split begin/end data transfer\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBp4est_bsearch_partition\fP (\fBp4est_gloidx_t\fP target, const \fBp4est_gloidx_t\fP *gfq, int nmemb)"
.br
.RI "Given target, find index p such that \fCgfq[p] <= target < gfq[p + 1]\fP\&. "
.ti -1c
.RI "void \fBp4est_comm_parallel_env_assign\fP (\fBp4est_t\fP *\fBp4est\fP, sc_MPI_Comm mpicomm)"
.br
.RI "Assign an MPI communicator to \fBp4est\fP; retrieve parallel environment\&. "
.ti -1c
.RI "void \fBp4est_comm_parallel_env_duplicate\fP (\fBp4est_t\fP *\fBp4est\fP)"
.br
.RI "Duplicate MPI communicator and replace the current one by the duplicate\&. "
.ti -1c
.RI "void \fBp4est_comm_parallel_env_release\fP (\fBp4est_t\fP *\fBp4est\fP)"
.br
.RI "Release MPI communicator if it is owned by \fBp4est\fP\&. "
.ti -1c
.RI "void \fBp4est_comm_parallel_env_replace\fP (\fBp4est_t\fP *\fBp4est\fP, sc_MPI_Comm mpicomm)"
.br
.RI "Replace the current MPI communicator by the one provided as input\&. "
.ti -1c
.RI "void \fBp4est_comm_parallel_env_get_info\fP (\fBp4est_t\fP *\fBp4est\fP)"
.br
.RI "Retrieve parallel environment information\&. "
.ti -1c
.RI "int \fBp4est_comm_parallel_env_is_null\fP (\fBp4est_t\fP *\fBp4est\fP)"
.br
.RI "Check if the MPI communicator is valid\&. "
.ti -1c
.RI "int \fBp4est_comm_parallel_env_reduce\fP (\fBp4est_t\fP **p4est_supercomm)"
.br
.RI "Reduce MPI communicator to non-empty ranks (i\&.e\&., nonzero quadrant counts)\&. "
.ti -1c
.RI "int \fBp4est_comm_parallel_env_reduce_ext\fP (\fBp4est_t\fP **p4est_supercomm, sc_MPI_Group group_add, int add_to_beginning, int **ranks_subcomm)"
.br
.RI "Reduce MPI communicator to non-empty ranks and add a group of ranks that will remain in the reduced communicator regardless whether they are empty or not\&. "
.ti -1c
.RI "void \fBp4est_comm_count_quadrants\fP (\fBp4est_t\fP *\fBp4est\fP)"
.br
.RI "Calculate the number and partition of quadrants\&. "
.ti -1c
.RI "void \fBp4est_comm_global_partition\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_quadrant_t\fP *first_quad)"
.br
.RI "Distribute the global partition boundaries\&. "
.ti -1c
.RI "void \fBp4est_comm_global_first_quadrant\fP (\fBp4est_gloidx_t\fP global_num_quadrants, int mpisize, \fBp4est_gloidx_t\fP *gfq)"
.br
.RI "Calculate the global fist quadrant array for a uniform partition\&. "
.ti -1c
.RI "void \fBp4est_comm_count_pertree\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_gloidx_t\fP *pertree)"
.br
.RI "Compute and distribute the cumulative number of quadrants per tree\&. "
.ti -1c
.RI "int \fBp4est_comm_is_empty\fP (\fBp4est_t\fP *\fBp4est\fP, int p)"
.br
.RI "Query whether a processor has no quadrants\&. "
.ti -1c
.RI "int \fBp4est_comm_is_empty_gfq\fP (const \fBp4est_gloidx_t\fP *gfq, int num_procs, int p)"
.br
.RI "Query whether a processor has no quadrants\&. "
.ti -1c
.RI "int \fBp4est_comm_is_empty_gfp\fP (const \fBp4est_quadrant_t\fP *gfp, int num_procs, int p)"
.br
.RI "Query whether a processor has no quadrants\&. "
.ti -1c
.RI "int \fBp4est_comm_is_contained\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP *q, int rank)"
.br
.RI "Test whether a quadrant is fully contained in a rank's owned region\&. "
.ti -1c
.RI "int \fBp4est_comm_is_owner\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP *q, int rank)"
.br
.RI "Test ownership of a quadrant via p4est->global_first_position\&. "
.ti -1c
.RI "int \fBp4est_comm_is_owner_gfp\fP (const \fBp4est_quadrant_t\fP *gfp, int num_procs, \fBp4est_topidx_t\fP num_trees, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP *q, int rank)"
.br
.RI "Test ownership of a quadrant via a global_first_position array\&. "
.ti -1c
.RI "int \fBp4est_comm_find_owner\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP *q, int guess)"
.br
.RI "Searches the owner of a quadrant via p4est->global_first_position\&. "
.ti -1c
.RI "void \fBp4est_comm_tree_info\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_locidx_t\fP which_tree, int full_tree[], int tree_contact[], const \fBp4est_quadrant_t\fP **firstq, const \fBp4est_quadrant_t\fP **nextq)"
.br
.RI "Computes information about a tree being fully owned\&. "
.ti -1c
.RI "int \fBp4est_comm_neighborhood_owned\fP (\fBp4est_t\fP *\fBp4est\fP, \fBp4est_locidx_t\fP which_tree, int full_tree[], int tree_contact[], \fBp4est_quadrant_t\fP *q)"
.br
.RI "Test if the 3x3 neighborhood of a quadrant is owned by this processor\&. "
.ti -1c
.RI "int \fBp4est_comm_sync_flag\fP (\fBp4est_t\fP *\fBp4est\fP, int flag, sc_MPI_Op operation)"
.br
.RI "Evaluates true/false of a flag among processors\&. "
.ti -1c
.RI "unsigned \fBp4est_comm_checksum\fP (\fBp4est_t\fP *\fBp4est\fP, unsigned local_crc, size_t local_bytes)"
.br
.RI "Compute a parallel partition-independent checksum out of local checksums\&. "
.ti -1c
.RI "void \fBp4est_transfer_fixed\fP (const \fBp4est_gloidx_t\fP *dest_gfq, const \fBp4est_gloidx_t\fP *src_gfq, sc_MPI_Comm mpicomm, int tag, void *dest_data, const void *src_data, size_t data_size)"
.br
.RI "Transfer data associated with one forest partition to another\&. "
.ti -1c
.RI "\fBp4est_transfer_context_t\fP * \fBp4est_transfer_fixed_begin\fP (const \fBp4est_gloidx_t\fP *dest_gfq, const \fBp4est_gloidx_t\fP *src_gfq, sc_MPI_Comm mpicomm, int tag, void *dest_data, const void *src_data, size_t data_size)"
.br
.RI "Initiate a fixed-size data transfer between partitions\&. "
.ti -1c
.RI "void \fBp4est_transfer_fixed_end\fP (\fBp4est_transfer_context_t\fP *tc)"
.br
.RI "Complete a fixed-size data transfer between partitions\&. "
.ti -1c
.RI "void \fBp4est_transfer_custom\fP (const \fBp4est_gloidx_t\fP *dest_gfq, const \fBp4est_gloidx_t\fP *src_gfq, sc_MPI_Comm mpicomm, int tag, void *dest_data, const int *dest_sizes, const void *src_data, const int *src_sizes)"
.br
.RI "Transfer variable-size quadrant data between partitions\&. "
.ti -1c
.RI "\fBp4est_transfer_context_t\fP * \fBp4est_transfer_custom_begin\fP (const \fBp4est_gloidx_t\fP *dest_gfq, const \fBp4est_gloidx_t\fP *src_gfq, sc_MPI_Comm mpicomm, int tag, void *dest_data, const int *dest_sizes, const void *src_data, const int *src_sizes)"
.br
.RI "Initiate a variable-size data transfer between partitions\&. "
.ti -1c
.RI "void \fBp4est_transfer_custom_end\fP (\fBp4est_transfer_context_t\fP *tc)"
.br
.RI "Complete a variable-size data transfer between partitions\&. "
.ti -1c
.RI "void \fBp4est_transfer_items\fP (const \fBp4est_gloidx_t\fP *dest_gfq, const \fBp4est_gloidx_t\fP *src_gfq, sc_MPI_Comm mpicomm, int tag, void *dest_data, const int *dest_counts, const void *src_data, const int *src_counts, size_t item_size)"
.br
.RI "Transfer variable-count item data between partitions\&. "
.ti -1c
.RI "\fBp4est_transfer_context_t\fP * \fBp4est_transfer_items_begin\fP (const \fBp4est_gloidx_t\fP *dest_gfq, const \fBp4est_gloidx_t\fP *src_gfq, sc_MPI_Comm mpicomm, int tag, void *dest_data, const int *dest_counts, const void *src_data, const int *src_counts, size_t item_size)"
.br
.RI "Initiate a variable-count item transfer between partitions\&. "
.ti -1c
.RI "void \fBp4est_transfer_items_end\fP (\fBp4est_transfer_context_t\fP *tc)"
.br
.RI "Complete a variable-count item transfer between partitions\&. "
.ti -1c
.RI "void \fBp4est_transfer_end\fP (\fBp4est_transfer_context_t\fP *tc)"
.br
.RI "Complete any of the transfer_begin functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Parallel messaging and support code\&. 


.SH "Function Documentation"
.PP 
.SS "int p4est_bsearch_partition (\fBp4est_gloidx_t\fP target, const \fBp4est_gloidx_t\fP * gfq, int nmemb)"

.PP
Given target, find index p such that \fCgfq[p] <= target < gfq[p + 1]\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP The value that is searched in \fIgfq\fP\&. \fItarget\fP has to satisfy \fCgfq[0] <= target < gfq[nmemb]\fP\&. 
.br
\fIgfq\fP The sorted array (ascending) in that the function will search\&. 
.br
\fInmemb\fP Number of entries in array MINUS ONE\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Index p such that \fCgfq[p] <= target < gfq[p + 1]\fP\&. 
.RE
.PP
\fBNote\fP
.RS 4
This function differs from \fBp4est_find_partition\fP since \fBp4est_find_partition\fP searches for two targets using binary search in an optimized way but \fBp4est_bsearch_partition\fP only performs a single binary search\&. 
.RE
.PP

.SS "unsigned p4est_comm_checksum (\fBp4est_t\fP * p4est, unsigned local_crc, size_t local_bytes)"

.PP
Compute a parallel partition-independent checksum out of local checksums\&. This checksum depends on the global refinement topology\&. It does not depend on how the mesh is partitioned\&. The result is available on all processors\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The MPI information of this \fBp4est\fP will be used\&. 
.br
\fIlocal_crc\fP Locally computed adler32 checksum\&. 
.br
\fIlocal_bytes\fP Number of bytes used for local checksum\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Parallel checksum on all processors\&. 
.RE
.PP

.SS "void p4est_comm_count_pertree (\fBp4est_t\fP * p4est, \fBp4est_gloidx_t\fP * pertree)"

.PP
Compute and distribute the cumulative number of quadrants per tree\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP This \fBp4est\fP needs to have correct values for global_first_quadrant and global_first_position\&. 
.br
\fIpertree\fP On input, memory for num_trees + 1 numbers\&. On output, the cumulative quadrant counts\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBparticles/particles2\&.c\fP\&.
.SS "void p4est_comm_count_quadrants (\fBp4est_t\fP * p4est)"

.PP
Calculate the number and partition of quadrants\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP Adds all \fCp4est->local_num_quadrant\fP counters and puts cumulative sums in p4est->global_first_quadrant\&. 
.RE
.PP

.SS "int p4est_comm_find_owner (\fBp4est_t\fP * p4est, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP * q, int guess)"

.PP
Searches the owner of a quadrant via p4est->global_first_position\&. Assumes a tree with no overlaps\&. 
.PP
\fBParameters\fP
.RS 4
\fIguess\fP Initial guess for the search\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the processor id of the owner\&. 
.RE
.PP

.SS "void p4est_comm_global_first_quadrant (\fBp4est_gloidx_t\fP global_num_quadrants, int mpisize, \fBp4est_gloidx_t\fP * gfq)"

.PP
Calculate the global fist quadrant array for a uniform partition\&. 
.PP
\fBParameters\fP
.RS 4
\fIglobal_num_quadrants\fP The global number of quadrants\&. 
.br
\fImpisize\fP The number of MPI ranks\&. 
.br
\fIgfq\fP At least allocated mpisize + 1 p4est_gloidx_t\&. This array is filled with the global first quadrant array assuming a uniform partition\&. 
.RE
.PP

.SS "void p4est_comm_global_partition (\fBp4est_t\fP * p4est, \fBp4est_quadrant_t\fP * first_quad)"

.PP
Distribute the global partition boundaries\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP Fills \fCp4est->global_first_position\fP\&. p4est->first_local_tree must be set correctly\&. If this processor is not empty and first_quad is NULL, the first quadrant of the first local tree must be set correctly\&. 
.br
\fIfirst_quad\fP If not NULL will be used as first quadrant\&. 
.RE
.PP

.SS "int p4est_comm_is_contained (\fBp4est_t\fP * p4est, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP * q, int rank)"

.PP
Test whether a quadrant is fully contained in a rank's owned region\&. This function may return false when \fBp4est_comm_is_owner\fP returns true\&. 
.PP
\fBParameters\fP
.RS 4
\fIrank\fP Rank whose ownership is tested\&. Assumes a forest with no overlaps\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if rank is the owner of the whole area of the quadrant\&. 
.RE
.PP

.SS "int p4est_comm_is_empty (\fBp4est_t\fP * p4est, int p)"

.PP
Query whether a processor has no quadrants\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP This forests' global_first_position array must be valid\&. 
.br
\fIp\fP Valid processor id\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if and only if processor \fCis\fP empty\&. 
.RE
.PP

.SS "int p4est_comm_is_empty_gfp (const \fBp4est_quadrant_t\fP * gfp, int num_procs, int p)"

.PP
Query whether a processor has no quadrants\&. 
.PP
\fBParameters\fP
.RS 4
\fIgfp\fP An array encoding the partition shape\&. Non-decreasing; length \fInum_procs\fP + 1\&. 
.br
\fInum_procs\fP Number of processes in the partition\&. 
.br
\fIp\fP Valid 0 <= \fIp\fP < \fInum_procs\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if and only if processor \fIp\fP is empty\&. 
.RE
.PP

.SS "int p4est_comm_is_empty_gfq (const \fBp4est_gloidx_t\fP * gfq, int num_procs, int p)"

.PP
Query whether a processor has no quadrants\&. 
.PP
\fBParameters\fP
.RS 4
\fIgfq\fP An array encoding the partition offsets in the global quadrant array; length \fInum_procs\fP + 1\&. 
.br
\fInum_procs\fP Number of processes in the partition\&. 
.br
\fIp\fP Valid 0 <= \fIp\fP < \fInum_procs\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if and only if processor \fIp\fP is empty\&. 
.RE
.PP

.SS "int p4est_comm_is_owner (\fBp4est_t\fP * p4est, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP * q, int rank)"

.PP
Test ownership of a quadrant via p4est->global_first_position\&. The quadrant is considered owned if its first descendant is owned\&. Thus, a positive result occurs even if its last descendant overlaps a higher process\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP Valid forest\&. 
.br
\fIwhich_tree\fP Valid tree number wrt\&. the forest\&. 
.br
\fIq\fP Valid quadrant wrt\&. the forest\&. 
.br
\fIrank\fP Rank whose ownership is tested\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if rank is the owner of the first descendant\&. 
.RE
.PP

.SS "int p4est_comm_is_owner_gfp (const \fBp4est_quadrant_t\fP * gfp, int num_procs, \fBp4est_topidx_t\fP num_trees, \fBp4est_locidx_t\fP which_tree, const \fBp4est_quadrant_t\fP * q, int rank)"

.PP
Test ownership of a quadrant via a global_first_position array\&. This array encodes part of the partition of a valid forest object\&. The quadrant is considered owned if its first descendant is owned\&. Thus, a positive result occurs even if its last descendant overlaps a higher process\&. 
.PP
\fBParameters\fP
.RS 4
\fIgfp\fP Position array of length \fInum_procs\fP + 1\&. 
.br
\fInum_procs\fP Number of processes in this context\&. 
.br
\fInum_trees\fP Number of trees in this context\&. 
.br
\fIwhich_tree\fP Valid tree number wrt\&. the forest\&. 
.br
\fIq\fP Valid quadrant wrt\&. the forest\&. 
.br
\fIrank\fP Rank whose ownership is tested\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if rank is the owner of the first descendant\&. 
.RE
.PP

.SS "int p4est_comm_neighborhood_owned (\fBp4est_t\fP * p4est, \fBp4est_locidx_t\fP which_tree, int full_tree[], int tree_contact[], \fBp4est_quadrant_t\fP * q)"

.PP
Test if the 3x3 neighborhood of a quadrant is owned by this processor\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The \fBp4est\fP to work on\&. 
.br
\fIwhich_tree\fP The tree index to work on\&. 
.br
\fIfull_tree\fP Flags as computed by p4est_comm_tree_info\&. 
.br
\fItree_contact\fP Flags as computed by p4est_comm_tree_info\&. 
.br
\fIq\fP The quadrant to be checked\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns true iff this quadrant's 3x3 neighborhood is owned\&. 
.RE
.PP

.SS "void p4est_comm_parallel_env_assign (\fBp4est_t\fP * p4est, sc_MPI_Comm mpicomm)"

.PP
Assign an MPI communicator to \fBp4est\fP; retrieve parallel environment\&. 
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP A valid MPI communicator\&.
.RE
.PP
\fBNote\fP
.RS 4
The provided MPI communicator is not owned by \fBp4est\fP\&. 
.RE
.PP

.SS "void p4est_comm_parallel_env_duplicate (\fBp4est_t\fP * p4est)"

.PP
Duplicate MPI communicator and replace the current one by the duplicate\&. 
.PP
\fBNote\fP
.RS 4
The duplicated MPI communicator is owned by \fBp4est\fP\&. 
.RE
.PP

.SS "int p4est_comm_parallel_env_is_null (\fBp4est_t\fP * p4est)"

.PP
Check if the MPI communicator is valid\&. 
.PP
\fBReturns\fP
.RS 4
True if communicator is not NULL communicator, false otherwise\&. 
.RE
.PP

.SS "int p4est_comm_parallel_env_reduce (\fBp4est_t\fP ** p4est_supercomm)"

.PP
Reduce MPI communicator to non-empty ranks (i\&.e\&., nonzero quadrant counts)\&. 
.PP
\fBParameters\fP
.RS 4
\fIp4est_supercomm\fP Object which communicator is reduced\&. Points to NULL if this \fBp4est\fP does not exists\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if \fBp4est\fP exists on this MPI rank after reduction\&. 
.RE
.PP

.SS "int p4est_comm_parallel_env_reduce_ext (\fBp4est_t\fP ** p4est_supercomm, sc_MPI_Group group_add, int add_to_beginning, int ** ranks_subcomm)"

.PP
Reduce MPI communicator to non-empty ranks and add a group of ranks that will remain in the reduced communicator regardless whether they are empty or not\&. 
.PP
\fBParameters\fP
.RS 4
\fIp4est_supercomm\fP Object which communicator is reduced\&. Points to NULL if this \fBp4est\fP does not exists\&. 
.br
\fIgroup_add\fP Group of ranks that will remain in communicator\&. 
.br
\fIadd_to_beginning\fP If true, ranks will be added to the beginning of the reduced communicator, otherwise to the end\&. 
.br
\fIranks_subcomm\fP If not null, array of size 'subcommsize' with subcommrank->supercommrank map\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if \fBp4est\fP exists on this MPI rank after reduction\&. 
.RE
.PP

.SS "void p4est_comm_parallel_env_replace (\fBp4est_t\fP * p4est, sc_MPI_Comm mpicomm)"

.PP
Replace the current MPI communicator by the one provided as input\&. 
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP A valid MPI communicator\&.
.RE
.PP
\fBNote\fP
.RS 4
The provided MPI communicator is not owned by \fBp4est\fP\&. 
.RE
.PP

.SS "int p4est_comm_sync_flag (\fBp4est_t\fP * p4est, int flag, sc_MPI_Op operation)"

.PP
Evaluates true/false of a flag among processors\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The MPI communicator of this \fBp4est\fP will be used\&. 
.br
\fIflag\fP The variable to communicate\&. 
.br
\fIoperation\fP Either sc_MPI_BAND or sc_MPI_BOR (not used bitwise)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the logical AND resp\&. OR of all processors' flags\&. 
.RE
.PP

.SS "void p4est_comm_tree_info (\fBp4est_t\fP * p4est, \fBp4est_locidx_t\fP which_tree, int full_tree[], int tree_contact[], const \fBp4est_quadrant_t\fP ** firstq, const \fBp4est_quadrant_t\fP ** nextq)"

.PP
Computes information about a tree being fully owned\&. This is determined separately for the beginning and end of the tree\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp4est\fP\fP The \fBp4est\fP to work on\&. 
.br
\fIwhich_tree\fP The tree in question must be partially owned\&. 
.br
\fIfull_tree\fP Full ownership of beginning and end of tree\&. 
.br
\fItree_contact\fP True if there are neighbors across the face\&. 
.br
\fIfirstq\fP Smallest possible first quadrant on this core\&. 
.br
\fInextq\fP Smallest possible first quadrant on next core\&. Any of tree_contact, firstq and nextq may be NULL\&. 
.RE
.PP

.SS "void p4est_transfer_custom (const \fBp4est_gloidx_t\fP * dest_gfq, const \fBp4est_gloidx_t\fP * src_gfq, sc_MPI_Comm mpicomm, int tag, void * dest_data, const int * dest_sizes, const void * src_data, const int * src_sizes)"

.PP
Transfer variable-size quadrant data between partitions\&. (See \fBp4est_transfer_fixed\fP that is optimized for fixed-size data\&.) The destination process may not know the data size for the elements it receives\&. In this case the sizes need to be obtained separately in advance, for example by calling \fBp4est_transfer_fixed\fP with \fBsrc_sizes\fP as payload data, or alternatively its split begin/end versions\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest_gfq\fP The target partition encoded as a \fBp4est->global_first_quadrant\fP array\&. Has \fBmpisize\fP 
.IP "\(bu" 2
1 members, must be non-decreasing and satisfy gfq[0] == 0, gfq[mpisize] == global_num_quadrants\&. 
.PP
.br
\fIsrc_gfq\fP The original partition, analogous to \fBdest_gfq\fP\&. 
.br
\fImpicomm\fP The communicator to use\&. Its mpisize must match \fBdest_gfq\fP and \fBsrc_gfq\fP\&. 
.br
\fItag\fP This tag is used in all messages\&. The user must guarantee that \fBmpicomm\fP and \fBtag\fP do not conflict with other messages in transit\&. 
.br
\fIdest_data\fP User-allocated memory of sum_{i in \fBdest->local_num_quadrants}\fP \fBdest_sizes\fP [i] many bytes is received into\&. See below about how to choose its size\&. If dest has data to transfer, must be non-NULL\&. 
.br
\fIdest_sizes\fP User-allocated memory of one integer for each quadrant, storing the data size to receive for it\&. We understand that the sizes are often not known a priori, in which case they can be obtained by a prior call to \fBp4est_transfer_fixed\fP\&. Optionally the split begin/end versions can be used for added flexibility and overlapping of messages\&. We use the type int to minimize the message size, and to conform to MPI that has no type for size_t\&. If dest has quadrants, must be non-NULL\&. 
.br
\fIsrc_data\fP User-allocated memory of sum_{i in \fBsrc->local_num_quadrants}\fP \fBsrc_sizes\fP [i] many bytes is sent from\&. If src has data to transfer, must be non-NULL\&. 
.br
\fIsrc_sizes\fP User-allocated memory of one integer for each quadrant, storing the data size to send for it\&. We use the type int to minimize the message size, and to conform to MPI that has no type for size_t\&. If src has quadrants, must be non-NULL\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBparticles/particles2\&.c\fP\&.
.SS "\fBp4est_transfer_context_t\fP* p4est_transfer_custom_begin (const \fBp4est_gloidx_t\fP * dest_gfq, const \fBp4est_gloidx_t\fP * src_gfq, sc_MPI_Comm mpicomm, int tag, void * dest_data, const int * dest_sizes, const void * src_data, const int * src_sizes)"

.PP
Initiate a variable-size data transfer between partitions\&. See \fBp4est_transfer_custom\fP for a full description\&. This functions calls asynchronous MPI send/receive and returns\&. Must be matched with \fBp4est_transfer_custom_end\fP for completion, which calls blocking MPI wait until all messages have been processed\&. All parameters must stay alive until the completion has been called\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest_gfq\fP The target partition encoded as a \fBp4est->global_first_quadrant\fP array\&. Has \fBmpisize\fP 
.IP "\(bu" 2
1 members, must be non-decreasing and satisfy gfq[0] == 0, gfq[mpisize] == global_num_quadrants\&. 
.PP
.br
\fIsrc_gfq\fP The original partition, analogous to \fBdest_gfq\fP\&. 
.br
\fImpicomm\fP The communicator to use\&. Its mpisize must match \fBdest_gfq\fP and \fBsrc_gfq\fP\&. 
.br
\fItag\fP This tag is used in all messages\&. The user must guarantee that \fBmpicomm\fP and \fBtag\fP do not conflict with other messages in transit\&. 
.br
\fIdest_data\fP User-allocated memory of sum_{i in \fBdest->local_num_quadrants}\fP \fBdest_sizes\fP [i] many bytes is received into\&. It must not be accessed before completion with \fBp4est_transfer_custom_end\fP\&. See below about how to choose its size\&. 
.br
\fIdest_sizes\fP User-allocated memory of one integer for each quadrant, storing the data size to receive for it\&. We understand that the sizes are often not known a priori, in which case they can be obtained by a prior call to \fBp4est_transfer_fixed\fP\&. Optionally the split begin/end versions can be used for added flexibility and overlapping of messages\&. We use the type int to minimize the message size, and to conform to MPI that has no type for size_t\&. 
.br
\fIsrc_data\fP User-allocated memory of sum_{i in \fBsrc->local_num_quadrants}\fP \fBsrc_sizes\fP [i] many bytes is sent from\&. It must not be accessed before completion with \fBp4est_transfer_custom_end\fP\&. 
.br
\fIsrc_sizes\fP User-allocated memory of one integer for each quadrant, storing the data size to send for it\&. We use the type int to minimize the message size, and to conform to MPI that has no type for size_t\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The context object must be passed to the matching call to \fBp4est_transfer_custom_end\fP\&. 
.RE
.PP

.SS "void p4est_transfer_custom_end (\fBp4est_transfer_context_t\fP * tc)"

.PP
Complete a variable-size data transfer between partitions\&. Waits for remaining messages to complete and frees the transfer context\&. 
.PP
\fBParameters\fP
.RS 4
\fItc\fP Context data from \fBp4est_transfer_custom_begin\fP\&. Is deallocated before this function returns\&. 
.RE
.PP

.SS "void p4est_transfer_end (\fBp4est_transfer_context_t\fP * tc)"

.PP
Complete any of the transfer_begin functions\&. The specialized transfer_end functions are recommended over this one for slightly stricter error checking: \fBp4est_transfer_fixed_end\fP, \fBp4est_transfer_custom_end\fP, and \fBp4est_transfer_items_end\fP\&.
.PP
\fBParameters\fP
.RS 4
\fItc\fP A valid context from one of the begin functions\&. This function waits for remaining communications to complete and frees the transfer context\&. 
.RE
.PP

.SS "void p4est_transfer_fixed (const \fBp4est_gloidx_t\fP * dest_gfq, const \fBp4est_gloidx_t\fP * src_gfq, sc_MPI_Comm mpicomm, int tag, void * dest_data, const void * src_data, size_t data_size)"

.PP
Transfer data associated with one forest partition to another\&. In \fBp4est_partition\fP, each quadrant's user data is transferred\&. If the application maintains per-quadrant data outside of the \fBp4est\fP object, this function can be used to transfer it, matching the call to partition\&. This variant of the function assumes that the quadrant data size is fixed\&. It sends point-to-point messages only and is blocking collective\&. There is a split collective version; see the functions \fBp4est_transfer_fixed_begin\fP and \fBp4est_transfer_fixed_end\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest_gfq\fP The target partition encoded as a \fBp4est->global_first_quadrant\fP array\&. Has \fBmpisize\fP 
.IP "\(bu" 2
1 members, must be non-decreasing and satisfy gfq[0] == 0, gfq[mpisize] == global_num_quadrants\&. 
.PP
.br
\fIsrc_gfq\fP The original partition, analogous to \fBdest_gfq\fP\&. 
.br
\fImpicomm\fP The communicator to use\&. Its mpisize must match \fBdest_gfq\fP and \fBsrc_gfq\fP\&. 
.br
\fItag\fP This tag is used in all messages\&. The user must guarantee that \fBmpicomm\fP and \fBtag\fP do not conflict with other messages in transit\&. 
.br
\fIdest_data\fP User-allocated memory of size \fBdata_size\fP * \fBdest->local_num_quadrants\fP is received into\&. If dest has quadrants, must be non-NULL\&. 
.br
\fIsrc_data\fP User-allocated memory of size \fBdata_size\fP * \fBsrc->local_num_quadrants\fP bytes is sent from\&. If src has quadrants, must be non-NULL\&. 
.br
\fIdata_size\fP Fixed data size per quadrant\&. If this is zero the whole transfer noops\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBparticles/particles2\&.c\fP, \fBspheres/spheres2\&.c\fP, and \fBuserdata/userdata_run2\&.c\fP\&.
.SS "\fBp4est_transfer_context_t\fP* p4est_transfer_fixed_begin (const \fBp4est_gloidx_t\fP * dest_gfq, const \fBp4est_gloidx_t\fP * src_gfq, sc_MPI_Comm mpicomm, int tag, void * dest_data, const void * src_data, size_t data_size)"

.PP
Initiate a fixed-size data transfer between partitions\&. See \fBp4est_transfer_fixed\fP for a full description\&. This functions calls asynchronous MPI send/receive and returns\&. Must be matched with \fBp4est_transfer_fixed_end\fP for completion, which calls blocking MPI wait until all messages have been processed\&. All parameters must stay alive until the completion has been called\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest_gfq\fP The target partition encoded as a \fBp4est->global_first_quadrant\fP array\&. Has \fBmpisize\fP 
.IP "\(bu" 2
1 members, must be non-decreasing and satisfy gfq[0] == 0, gfq[mpisize] == global_num_quadrants\&. 
.PP
.br
\fIsrc_gfq\fP The original partition, analogous to \fBdest_gfq\fP\&. 
.br
\fImpicomm\fP The communicator to use\&. Its mpisize must match \fBdest_gfq\fP and \fBsrc_gfq\fP\&. 
.br
\fItag\fP This tag is used in all messages\&. The user must guarantee that \fBmpicomm\fP and \fBtag\fP do not conflict with other messages in transit\&. 
.br
\fIdest_data\fP User-allocated memory of size \fBdata_size\fP * \fBdest->local_num_quadrants\fP bytes is received into\&. It must not be accessed before completion with \fBp4est_transfer_fixed_end\fP\&. 
.br
\fIsrc_data\fP User-allocated memory of size \fBdata_size\fP * \fBsrc->local_num_quadrants\fP bytes is sent from\&. It must not be accessed before completion with \fBp4est_transfer_fixed_end\fP\&. 
.br
\fIdata_size\fP Fixed data size per quadrant\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The context object must be passed to the matching call to \fBp4est_transfer_fixed_end\fP\&. 
.RE
.PP

.SS "void p4est_transfer_fixed_end (\fBp4est_transfer_context_t\fP * tc)"

.PP
Complete a fixed-size data transfer between partitions\&. Waits for remaining messages to complete and frees the transfer context\&. 
.PP
\fBParameters\fP
.RS 4
\fItc\fP Context data from \fBp4est_transfer_fixed_begin\fP\&. Is deallocated before this function returns\&. 
.RE
.PP

.SS "void p4est_transfer_items (const \fBp4est_gloidx_t\fP * dest_gfq, const \fBp4est_gloidx_t\fP * src_gfq, sc_MPI_Comm mpicomm, int tag, void * dest_data, const int * dest_counts, const void * src_data, const int * src_counts, size_t item_size)"

.PP
Transfer variable-count item data between partitions\&. Each quadrant may have a different number of items (including 0)\&. (See \fBp4est_transfer_fixed\fP that is optimized for fixed-count data, and \fBp4est_transfer_custom\fP for data that is not itemized at all\&.) The destination process may not know the item count for the elements it receives\&. In this case the counts need to be obtained separately in advance, for example by calling \fBp4est_transfer_fixed\fP with \fBsrc_sizes\fP as payload data, or alternatively its split begin/end versions\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest_gfq\fP The target partition encoded as a \fBp4est->global_first_quadrant\fP array\&. Has \fBmpisize\fP 
.IP "\(bu" 2
1 members, must be non-decreasing and satisfy gfq[0] == 0, gfq[mpisize] == global_num_quadrants\&. 
.PP
.br
\fIsrc_gfq\fP The original partition, analogous to \fBdest_gfq\fP\&. 
.br
\fImpicomm\fP The communicator to use\&. Its mpisize must match \fBdest_gfq\fP and \fBsrc_gfq\fP\&. 
.br
\fItag\fP This tag is used in all messages\&. The user must guarantee that \fBmpicomm\fP and \fBtag\fP do not conflict with other messages in transit\&. 
.br
\fIdest_data\fP User-allocated memory of sum_{i in \fBdest->local_num_quadrants}\fP item_size
.IP "\(bu" 2
dest_counts[i] many bytes is received into\&. See below about how to choose its size\&. If dest has data to transfer, must be non-NULL\&. 
.PP
.br
\fIdest_counts\fP User-allocated memory of one integer for each quadrant, storing the item count to receive for it\&. We understand that the counts are often not known a priori, in which case they can be obtained by a prior call to \fBp4est_transfer_fixed\fP\&. Optionally the split begin/end versions can be used for added flexibility and overlapping of messages\&. We use the type int to minimize the message size, and to conform to MPI that has no type for size_t\&. If dest has quadrants, must be non-NULL\&. 
.br
\fIsrc_data\fP User-allocated memory of sum_{i in \fBsrc->local_num_quadrants}\fP item_size
.IP "\(bu" 2
src_counts[i] many bytes is sent from\&. If src has data to transfer, must be non-NULL\&. 
.PP
.br
\fIsrc_counts\fP User-allocated memory of one integer for each quadrant, storing the item count to send for it\&. We use the type int to minimize the message size, and to conform to MPI that has no type for size_t\&. If src has quadrants, must be non-NULL\&. 
.br
\fIitem_size\fP Data size for each item in bytes\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBspheres/spheres2\&.c\fP\&.
.SS "\fBp4est_transfer_context_t\fP* p4est_transfer_items_begin (const \fBp4est_gloidx_t\fP * dest_gfq, const \fBp4est_gloidx_t\fP * src_gfq, sc_MPI_Comm mpicomm, int tag, void * dest_data, const int * dest_counts, const void * src_data, const int * src_counts, size_t item_size)"

.PP
Initiate a variable-count item transfer between partitions\&. See \fBp4est_transfer_items\fP for a full description\&. This functions calls asynchronous MPI send/receive and returns\&. Must be matched with \fBp4est_transfer_items_end\fP for completion, which calls blocking MPI wait until all messages have been processed\&. All parameters must stay alive until the completion has been called\&. 
.SS "void p4est_transfer_items_end (\fBp4est_transfer_context_t\fP * tc)"

.PP
Complete a variable-count item transfer between partitions\&. Waits for remaining messages to complete and frees the transfer context\&. 
.PP
\fBParameters\fP
.RS 4
\fItc\fP Context data from \fBp4est_transfer_items_begin\fP\&. Is deallocated before this function returns\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
