.TH "p6est_profile" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p6est_profile
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "p6est_profile_type_t \fBptype\fP"
.br
.ti -1c
.RI "\fBp8est_connect_type_t\fP \fBbtype\fP"
.br
.ti -1c
.RI "\fBp4est_lnodes_t\fP * \fBlnodes\fP"
.br
.ti -1c
.RI "\fBp4est_ghost_t\fP * \fBcghost\fP"
.br
.ti -1c
.RI "int \fBghost_owned\fP"
.br
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBlnode_ranges\fP"
.br
.ti -1c
.RI "sc_array_t * \fBlnode_columns\fP"
.br
.ti -1c
.RI "int * \fBlnode_changed\fP [2]"
.br
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBenode_counts\fP"
.br
.ti -1c
.RI "int \fBevenodd\fP"
.br
.ti -1c
.RI "\fBp4est_qcoord_t\fP \fBdiff\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
