.TH "p6est_connectivity" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p6est_connectivity \- This structure holds the 2D+1D inter-tree connectivity information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p6est\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_connectivity_t\fP * \fBconn4\fP"
.br
.RI "the 2D connecitvity; owned; vertices interpreted as the vertices of the bottom of the sheet "
.ti -1c
.RI "double * \fBtop_vertices\fP"
.br
.RI "if NULL, uniform vertical profile, otherwise the vertices of the top of the sheet: should be the same size as \fIconn4->tree_to_vertex\fP; owned\&. "
.ti -1c
.RI "double \fBheight\fP [3]"
.br
.RI "if \fItop_vertices\fP == NULL, this gives the offset from the bottom of the sheet to the top "
.in -1c
.SH "Detailed Description"
.PP 
This structure holds the 2D+1D inter-tree connectivity information\&. 

It is essentially a wrapper of the 2D p4est_connecitivity_t datatype, with some additional information about how the third dimension is embedded\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
