.TH "p8est_hang4" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_hang4 \- Store a hanging node that depends on four independent nodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_nodes\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBp8est_hang4_data\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_qcoord_t\fP \fBx\fP"
.br
.ti -1c
.RI "\fBp4est_qcoord_t\fP \fBy\fP"
.br
.ti -1c
.RI "\fBp4est_qcoord_t\fP \fBz\fP"
.br
.ti -1c
.RI "int8_t \fBlevel\fP"
.br
.ti -1c
.RI "int8_t \fBpad8\fP"
.br
.ti -1c
.RI "int16_t \fBpad16\fP"
.br
.ti -1c
.RI "union \fBp8est_hang4::p8est_hang4_data\fP \fBp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Store a hanging node that depends on four independent nodes\&. 

Keep this in sync with the p8est_t data structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
