.TH "p8est_mesh_face_neighbor_t" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_mesh_face_neighbor_t \- This structure can be used as the status of a face neighbor iterator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_mesh\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp8est_t\fP * \fBp4est\fP"
.br
.RI "the forest "
.ti -1c
.RI "\fBp8est_ghost_t\fP * \fBghost\fP"
.br
.RI "the ghost layer of the forest "
.ti -1c
.RI "\fBp8est_mesh_t\fP * \fBmesh\fP"
.br
.RI "a mesh derived from the forest "
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.RI "the current tree index "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBquadrant_id\fP"
.br
.RI "tree-local quadrant index "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBquadrant_code\fP"
.br
.RI "6 * (quadrant_id + tree_offset) "
.ti -1c
.RI "int \fBface\fP"
.br
.RI "Face number in 0\&.\&.5\&. "
.ti -1c
.RI "int \fBsubface\fP"
.br
.RI "Hanging neighbor number in 0\&.\&.3\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBcurrent_qtq\fP"
.br
.RI "track index of current neighboring quadrant "
.in -1c
.SH "Detailed Description"
.PP 
This structure can be used as the status of a face neighbor iterator\&. 

It always contains the face and subface of the neighbor to be processed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
