.TH "p8est_iter_face_side::p8est_iter_face_side_data" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_iter_face_side::p8est_iter_face_side_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp8est_iter_face_side_full_t\fP \fBfull\fP"
.br
.RI "if \fI!is_hanging\fP, use is\&.full to access per-quadrant data "
.ti -1c
.RI "\fBp8est_iter_face_side_hanging_t\fP \fBhanging\fP"
.br
.RI "if \fIis_hanging\fP, use is\&.hanging to access per-quadrant data "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
