.TH "p8est_edge_info_t" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_edge_info_t \- Information about the neighbors of an edge\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_connectivity\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int8_t \fBiedge\fP"
.br
.RI "The information of the edge\&. "
.ti -1c
.RI "sc_array_t \fBedge_transforms\fP"
.br
.RI "The array of neighbors of the originating edge\&. "
.in -1c
.SH "Detailed Description"
.PP 
Information about the neighbors of an edge\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
