.TH "p8est_tets" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_tets
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_array_t * \fBnodes\fP"
.br
.RI "The node array contains a triplet of double coordinates per node\&. "
.ti -1c
.RI "sc_array_t * \fBtets\fP"
.br
.RI "The tet array contains a quartet of p4est_topidx_t nodes per tet\&. "
.ti -1c
.RI "sc_array_t * \fBtet_attributes\fP"
.br
.RI "The element_attributes array can contain one int attribute per tet\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
