.TH "p4est_indep::p4est_indep_data" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_indep::p4est_indep_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBunused\fP"
.br
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.ti -1c
.RI "   int \fBowner_rank\fP"
.br
.ti -1c
.RI "} \fBpiggy1\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBfrom_tree\fP"
.br
.ti -1c
.RI "} \fBpiggy_unused2\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.ti -1c
.RI "   \fBp4est_locidx_t\fP \fBlocal_num\fP"
.br
.ti -1c
.RI "} \fBpiggy3\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
