.TH "p4est_iter_face_side" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_iter_face_side \- Information about one side of a face in the forest\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_iterate\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBp4est_iter_face_side_data\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBtreeid\fP"
.br
.RI "the tree on this side "
.ti -1c
.RI "int8_t \fBface\fP"
.br
.RI "which quadrant side the face touches "
.ti -1c
.RI "int8_t \fBis_hanging\fP"
.br
.RI "boolean: one full quad (0) or two smaller quads (1) "
.ti -1c
.RI "union \fBp4est_iter_face_side::p4est_iter_face_side_data\fP \fBis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about one side of a face in the forest\&. 

If a \fIquad\fP is local (\fIis_ghost\fP is false), then its \fIquadid\fP indexes the tree's quadrant array; otherwise, it indexes the ghosts array\&. If the face is hanging, then the quadrants are listed in z-order\&. If a quadrant should be present, but it is not included in the ghost layer, then quad = NULL, is_ghost is true, and quadid = -1\&. 
.PP
\fBExamples\fP
.in +1c
\fBsteps/p4est_step3\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
