.TH "p4est_quadrant::p4est_quadrant_data" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_quadrant::p4est_quadrant_data \- Union for quadrant data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.RI "never changed by \fBp4est\fP "
.ti -1c
.RI "long \fBuser_long\fP"
.br
.RI "never changed by \fBp4est\fP "
.ti -1c
.RI "int \fBuser_int\fP"
.br
.RI "never changed by \fBp4est\fP "
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.RI "the tree containing the quadrant (used in auxiliary octants such as the ghost octants in p4est_ghost_t) "
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.ti -1c
.RI "   int \fBowner_rank\fP"
.br
.ti -1c
.RI "} \fBpiggy1\fP"
.br
.RI "of ghost octants, store the tree and owner rank; not part of the API "
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBfrom_tree\fP"
.br
.ti -1c
.RI "} \fBpiggy2\fP"
.br
.RI "of transformed octants, store the original tree and the target tree; not part of the API "
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBp4est_topidx_t\fP \fBwhich_tree\fP"
.br
.ti -1c
.RI "   \fBp4est_locidx_t\fP \fBlocal_num\fP"
.br
.ti -1c
.RI "} \fBpiggy3\fP"
.br
.RI "of ghost octants, store the tree and index in the owner's numbering; only part of the API in \fBp4est_ghost_t::ghosts\fP "
.in -1c
.SH "Detailed Description"
.PP 
Union for quadrant data\&. 

It is important to notice that \fBpiggy1\fP and \fBpiggy2\fP are only used internally\&. Hence, they are not part of the API\&.
.PP
Usually \fBpiggy3\fP is also not part of the API\&. The only exception holds for quadrants in the \fBghosts\fP array of p4est_ghost_t (cf\&. documentation of \fBghosts\fP)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
