.TH "p4est_lnodes" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_lnodes \- Store a parallel numbering of Lobatto points of a given degree > 0\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_lnodes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_MPI_Comm \fBmpicomm\fP"
.br
.RI "Valid MPI communicator\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBnum_local_nodes\fP"
.br
.RI "Number of nodes known to process\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBowned_count\fP"
.br
.RI "Number of owned nodes of process\&. "
.ti -1c
.RI "\fBp4est_gloidx_t\fP \fBglobal_offset\fP"
.br
.RI "Global number of first local node\&. "
.ti -1c
.RI "\fBp4est_gloidx_t\fP * \fBnonlocal_nodes\fP"
.br
.RI "For nonlocal nodes: global number\&. "
.ti -1c
.RI "sc_array_t * \fBsharers\fP"
.br
.RI "Encoding of sharer processes' nodes\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBglobal_owned_count\fP"
.br
.RI "For each rank: owned count\&. "
.ti -1c
.RI "int \fBdegree\fP"
.br
.RI "Degree used in construction\&. "
.ti -1c
.RI "int \fBvnodes\fP"
.br
.RI "Number of nodes of each element\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBnum_local_elements\fP"
.br
.RI "Elements local to process\&. "
.ti -1c
.RI "\fBp4est_lnodes_code_t\fP * \fBface_code\fP"
.br
.RI "One entry per local element encoding its hanging situation\&. "
.ti -1c
.RI "\fBp4est_locidx_t\fP * \fBelement_nodes\fP"
.br
.RI "Flat list: element_nodes * vnodes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Store a parallel numbering of Lobatto points of a given degree > 0\&. 

Each element has degree+1 nodes per face and vnodes = (degree+1)^2 nodes per volume\&. num_local_elements is the number of local quadrants in the \fBp4est\fP\&. element_nodes is of dimension vnodes * num_local_elements and lists the nodes of each element in lexicographic yx-order (x varies fastest); so for degree == 2, this is the layout of nodes: 
.PP
.nf
        f_3
 c_2           c_3
     6---7---8
     |       |
f_0  3   4   5  f_1
     |       |
     0---1---2
 c_0           c_1
        f_2

.fi
.PP
 element_nodes indexes into the set of local nodes, layed out as follows: 
.PP
.nf
local nodes = [<-----owned_count----->|<-----nonlocal_nodes----->]
            = [<----------------num_local_nodes----------------->]

.fi
.PP
 nonlocal_nodes contains the globally unique numbers for independent nodes that are owned by other processes; for local nodes, the globally unique numbers are given by i + global_offset, where i is the local number\&. Hanging nodes are always local and don't have a global number\&. They index the geometrically corresponding independent nodes of a neighbor\&.
.PP
Whether nodes are hanging or not is decided based on the element faces\&. This information is encoded in face_code with one int8_t per element\&. If no faces are hanging, the value is zero, otherwise the face_code is interpreted by p4est_lnodes_decode\&.
.PP
Independent nodes can be shared by multiple MPI ranks\&. The owner rank of a node is the one from the lowest numbered element on the lowest numbered octree \fItouching\fP the node\&.
.PP
What is meant by \fItouching\fP? A quadrant is said to touch all faces/corners that are incident on it, and by extension all nodes that are contained in those faces/corners\&. 
.PP
.nf
        X +-----------+
        o |           |
        o |           |
+-----+ o |     p     |
|  q  | o |           |
|     | o |           |
+-----+ O +-----------+

.fi
.PP
 In this example degree = 6\&. There are 5 nodes that live on the face between q and p, and one at each corner of that face\&. The face is incident on q, so q owns the nodes on the face (provided q is from a lower tree or has a lower index than p)\&. The lower corner is incident on q, so q owns it as well\&. The upper corner is not incident on q, so q cannot own it\&.
.PP
global_owned_count contains the number of independent nodes owned by each process\&.
.PP
The sharers array contains items of type p4est_lnodes_rank_t that hold the ranks that own or share independent local nodes\&. If there are no shared nodes on this processor, it is empty\&. Otherwise, it is sorted by rank and the current process is included\&.
.PP
degree < 0 indicates that the lnodes data structure is being used to number the quadrant boundary object (faces and corners) rather than the $C^0$ Lobatto nodes:
.PP
if degree == -1, then one node is assigned per face, and no nodes are assigned per volume or per corner: this numbering can be used for low-order Raviart-Thomas elements\&. In this case, vnodes == 4, and the nodes are listed in face-order: 
.PP
.nf
        f_3
 c_2           c_3
     +---3---+
     |       |
f_0  0       1  f_1
     |       |
     +---2---+
 c_0           c_1
        f_2

.fi
.PP
 if degree == -2, then one node is assigned per face and per corner and no nodes are assigned per volume\&. In this case, vnodes == 8, and the nodes are listed in face-order, followed by corner-order: 
.PP
.nf
        f_3
 c_2           c_3
     6---3---7
     |       |
f_0  0       1  f_1
     |       |
     4---2---5
 c_0           c_1
        f_2

.fi
.PP
 
.PP
\fBExamples\fP
.in +1c
\fBtimings/timings2\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "int p4est_lnodes::degree"

.PP
Degree used in construction\&. Generally > 0, with further special cases; see \fBp4est_lnodes\fP\&. 
.SS "sc_array_t* p4est_lnodes::sharers"

.PP
Encoding of sharer processes' nodes\&. The array elements are of type \fBp4est_lnodes_rank\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
