.TH "p4est" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est \- The \fBp4est\fP forest datatype\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_MPI_Comm \fBmpicomm\fP"
.br
.RI "MPI communicator\&. "
.ti -1c
.RI "int \fBmpisize\fP"
.br
.RI "number of MPI processes "
.ti -1c
.RI "int \fBmpirank\fP"
.br
.RI "this process's MPI rank "
.ti -1c
.RI "int \fBmpicomm_owned\fP"
.br
.RI "flag if communicator is owned "
.ti -1c
.RI "size_t \fBdata_size\fP"
.br
.RI "size of per-quadrant p\&.user_data (see \fBp4est_quadrant_t::p4est_quadrant_data::user_data\fP) "
.ti -1c
.RI "void * \fBuser_pointer\fP"
.br
.RI "convenience pointer for users, never touched by \fBp4est\fP "
.ti -1c
.RI "long \fBrevision\fP"
.br
.RI "Gets bumped on mesh change\&. "
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBfirst_local_tree\fP"
.br
.RI "0-based index of first local tree, must be -1 for an empty processor "
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBlast_local_tree\fP"
.br
.RI "0-based index of last local tree, must be -2 for an empty processor "
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBlocal_num_quadrants\fP"
.br
.RI "number of quadrants on all trees on this processor "
.ti -1c
.RI "\fBp4est_gloidx_t\fP \fBglobal_num_quadrants\fP"
.br
.RI "number of quadrants on all trees on all processors "
.ti -1c
.RI "\fBp4est_gloidx_t\fP * \fBglobal_first_quadrant\fP"
.br
.RI "first global quadrant index for each process and 1 beyond "
.ti -1c
.RI "\fBp4est_quadrant_t\fP * \fBglobal_first_position\fP"
.br
.RI "first smallest possible quad for each process and 1 beyond "
.ti -1c
.RI "\fBp4est_connectivity_t\fP * \fBconnectivity\fP"
.br
.RI "connectivity structure, not owned "
.ti -1c
.RI "sc_array_t * \fBtrees\fP"
.br
.RI "array of all trees "
.ti -1c
.RI "sc_mempool_t * \fBuser_data_pool\fP"
.br
.RI "memory allocator for user data "
.ti -1c
.RI "sc_mempool_t * \fBquadrant_pool\fP"
.br
.RI "memory allocator for temporary quadrants "
.ti -1c
.RI "\fBp4est_inspect_t\fP * \fBinspect\fP"
.br
.RI "algorithmic switches "
.in -1c
.SH "Detailed Description"
.PP 
The \fBp4est\fP forest datatype\&. 
.PP
\fBExamples\fP
.in +1c
\fBparticles/particles2\&.c\fP, \fBsimple/simple2\&.c\fP, \fBspheres/spheres2\&.c\fP, \fBsteps/p4est_step1\&.c\fP, \fBsteps/p4est_step3\&.c\fP, \fBtimings/timings2\&.c\fP, and \fBuserdata/userdata_run2\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
