.TH "p4est_iter_corner_side" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_iter_corner_side \- Information about one side of a corner in the forest\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_iterate\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBtreeid\fP"
.br
.RI "the tree that contains \fIquad\fP "
.ti -1c
.RI "int8_t \fBcorner\fP"
.br
.RI "which of the quadrant's corners touches this corner "
.ti -1c
.RI "int8_t \fBis_ghost\fP"
.br
.RI "boolean: local (0) or ghost (1) "
.ti -1c
.RI "\fBp4est_quadrant_t\fP * \fBquad\fP"
.br
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBquadid\fP"
.br
.RI "the index in the tree or ghost array "
.ti -1c
.RI "int8_t \fBfaces\fP [2]"
.br
.RI "internal work data "
.in -1c
.SH "Detailed Description"
.PP 
Information about one side of a corner in the forest\&. 

If a \fIquad\fP is local (\fIis_ghost\fP is false), then its \fIquadid\fP indexes the tree's quadrant array; otherwise, it indexes the ghosts array\&. If a quadrant should be present, but it is not included in the ghost layer, then quad = NULL, is_ghost is true, and quadid = -1\&.
.PP
the \fIfaces\fP field provides some additional information about the local topology: if side[i]->faces[j] == side[k]->faces[l], this indicates that there is a common face between these two sides of the corner\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
