.TH "p4est_wrap" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p4est_wrap \- Wrapping a \fBp4est\fP object for an alternative API\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p4est_wrap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_wrap_params_t\fP \fBparams\fP"
.br
.ti -1c
.RI "sc_refcount_t \fBconn_rc\fP"
.br
.RI "This reference counter is a workaround for internal use only\&. "
.ti -1c
.RI "\fBp4est_connectivity_t\fP * \fBconn\fP"
.br
.ti -1c
.RI "struct \fBp4est_wrap\fP * \fBconn_owner\fP"
.br
.ti -1c
.RI "int \fBp4est_dim\fP"
.br
.ti -1c
.RI "int \fBp4est_half\fP"
.br
.ti -1c
.RI "int \fBp4est_faces\fP"
.br
.ti -1c
.RI "int \fBp4est_children\fP"
.br
.ti -1c
.RI "\fBp4est_t\fP * \fBp4est\fP"
.br
.RI "p4est->user_pointer is used internally "
.ti -1c
.RI "sc_array_t * \fBnewly_refined\fP"
.br
.RI "Indices of quadrants refined during most recent \fBp4est_wrap_adapt\fP\&. "
.ti -1c
.RI "sc_array_t * \fBnewly_coarsened\fP"
.br
.RI "Indices of quadrants coarsened during most recent \fBp4est_wrap_adapt\fP\&. "
.ti -1c
.RI "int \fBweight_exponent\fP"
.br
.ti -1c
.RI "uint8_t * \fBflags\fP"
.br
.ti -1c
.RI "uint8_t * \fBtemp_flags\fP"
.br
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBnum_refine_flags\fP"
.br
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBinside_counter\fP"
.br
.ti -1c
.RI "\fBp4est_locidx_t\fP \fBnum_replaced\fP"
.br
.ti -1c
.RI "\fBp4est_gloidx_t\fP * \fBold_global_first_quadrant\fP"
.br
.ti -1c
.RI "\fBp4est_ghost_t\fP * \fBghost\fP"
.br
.ti -1c
.RI "\fBp4est_mesh_t\fP * \fBmesh\fP"
.br
.ti -1c
.RI "\fBp4est_ghost_t\fP * \fBghost_aux\fP"
.br
.ti -1c
.RI "\fBp4est_mesh_t\fP * \fBmesh_aux\fP"
.br
.ti -1c
.RI "int \fBmatch_aux\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapping a \fBp4est\fP object for an alternative API\&. 
.SH "Field Documentation"
.PP 
.SS "sc_refcount_t p4est_wrap::conn_rc"

.PP
This reference counter is a workaround for internal use only\&. Until we have refcounting/copy-on-write for the connectivity, we count the references to conn by copies of this wrap structure\&. There must be no external references left when this wrap is destroyed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
