.TH "p6est" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p6est \- The \fBp6est\fP forest datatype\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p6est\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_MPI_Comm \fBmpicomm\fP"
.br
.RI "MPI communicator\&. "
.ti -1c
.RI "int \fBmpisize\fP"
.br
.RI "number of MPI processes "
.ti -1c
.RI "int \fBmpirank\fP"
.br
.RI "this process's MPI rank "
.ti -1c
.RI "int \fBmpicomm_owned\fP"
.br
.RI "whether this communicator is owned by the forest "
.ti -1c
.RI "size_t \fBdata_size\fP"
.br
.RI "size of per-quadrant p\&.user_data (see p2est_quadrant_t::p2est_quadrant_data::user_data) "
.ti -1c
.RI "void * \fBuser_pointer\fP"
.br
.RI "convenience pointer for users, never touched by \fBp4est\fP "
.ti -1c
.RI "\fBp6est_connectivity_t\fP * \fBconnectivity\fP"
.br
.RI "topology of sheet, not owned\&. "
.ti -1c
.RI "\fBp4est_t\fP * \fBcolumns\fP"
.br
.RI "2D description of column layout built from \fIconnectivity\fP\&. "
.ti -1c
.RI "sc_array_t * \fBlayers\fP"
.br
.RI "single array that stores p2est_quadrant_t layers within columns "
.ti -1c
.RI "sc_mempool_t * \fBuser_data_pool\fP"
.br
.RI "memory allocator for user data "
.ti -1c
.RI "sc_mempool_t * \fBlayer_pool\fP"
.br
.RI "memory allocator for temporary layers "
.ti -1c
.RI "\fBp4est_gloidx_t\fP * \fBglobal_first_layer\fP"
.br
.RI "first global quadrant index for each process and 1 beyond "
.ti -1c
.RI "\fBp4est_qcoord_t\fP \fBroot_len\fP"
.br
.RI "height of the domain "
.in -1c
.SH "Detailed Description"
.PP 
The \fBp6est\fP forest datatype\&. 
.SH "Field Documentation"
.PP 
.SS "\fBp4est_t\fP* p6est::columns"

.PP
2D description of column layout built from \fIconnectivity\fP\&. 
.PP
\fBNote\fP
.RS 4
columns->p\&.user_data cannot be used\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
