.TH "p8est_mesh_params_t" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_mesh_params_t \- This structure contains the different parameters of mesh creation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_mesh\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcompute_tree_index\fP"
.br
.RI "Boolean to decide whether to allocate and compute the quad_to_tree list\&. "
.ti -1c
.RI "int \fBcompute_level_lists\fP"
.br
.RI "Boolean to decide whether to compute the level lists in quad_level\&. "
.ti -1c
.RI "\fBp8est_connect_type_t\fP \fBbtype\fP"
.br
.RI "Flag indicating the connection types (face, edge, corner) stored in the mesh\&. "
.ti -1c
.RI "int \fBedgehanging_corners\fP"
.br
.RI "Boolean to decide whether to add corner neighbors across coarse edges\&. "
.in -1c
.SH "Detailed Description"
.PP 
This structure contains the different parameters of mesh creation\&. 

A default instance can be initialzed by calling \fBp8est_mesh_params_init\fP and used for mesh creation by calling \fBp8est_mesh_new_params\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
