.TH "p8est_iter_face_info" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_iter_face_info \- The information that is available to the user-defined p8est_iter_face_t callback\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_iterate\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp8est_t\fP * \fBp4est\fP"
.br
.ti -1c
.RI "\fBp8est_ghost_t\fP * \fBghost_layer\fP"
.br
.ti -1c
.RI "int8_t \fBorientation\fP"
.br
.RI "the orientation of the sides to each other, as in the definition of p8est_connectivity_t "
.ti -1c
.RI "int8_t \fBtree_boundary\fP"
.br
.RI "boolean: interior face (0), tree boundary face (true) "
.ti -1c
.RI "sc_array_t \fBsides\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The information that is available to the user-defined p8est_iter_face_t callback\&. 

The orientation is 0 if the face is within one tree; otherwise, it is the same as the orientation value between the two trees given in the connectivity\&. If the face is on the outside of the forest, then there is only one side\&. If tree_boundary is false, the face is on the interior of a tree\&. When tree_boundary false, sides[0] contains the lowest z-order quadrant that touches the face\&. When tree_boundary is true, its value is P8EST_CONNECT_FACE\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
