.TH "p8est_edge_transform_t" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_edge_transform_t \- Generic interface for transformations between a tree and any of its edge\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_connectivity\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp4est_topidx_t\fP \fBntree\fP"
.br
.RI "The number of the tree\&. "
.ti -1c
.RI "int8_t \fBnedge\fP"
.br
.RI "The number of the edge\&. "
.ti -1c
.RI "int8_t \fBnaxis\fP [3]"
.br
.RI "The 3 edge coordinate axes\&. "
.ti -1c
.RI "int8_t \fBnflip\fP"
.br
.RI "The orientation of the edge\&. "
.ti -1c
.RI "int8_t \fBcorners\fP"
.br
.RI "The corners connected to the edge\&. "
.in -1c
.SH "Detailed Description"
.PP 
Generic interface for transformations between a tree and any of its edge\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
