.TH "p8est_connectivity_shared" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p8est_connectivity_shared \- Management information for a connectivity shared by MPI3\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <p8est_connectivity\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBp8est_connectivity_t\fP * \fBconn\fP"
.br
.RI "The members of this connectivity are MPI3 shared windows\&. "
.in -1c
.SH "Detailed Description"
.PP 
Management information for a connectivity shared by MPI3\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
