.TH "src/p8est_extended.h" 3 "Thu Mar 13 2025" "Version 2.8.6.316-59dc-dirty" "p4est" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/p8est_extended.h \- Interface routines with extended capabilities\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sc_uint128\&.h>\fP
.br
\fC#include <p8est_mesh\&.h>\fP
.br
\fC#include <p8est_iterate\&.h>\fP
.br
\fC#include <p8est_lnodes\&.h>\fP
.br
\fC#include <p8est_io\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBp8est_inspect\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef sc_uint128_t \fBp8est_lid_t\fP"
.br
.RI "A datatype to handle the linear id in 3D\&. "
.ti -1c
.RI "typedef void(* \fBp8est_replace_t\fP) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, int num_outgoing, \fBp8est_quadrant_t\fP *outgoing[], int num_incoming, \fBp8est_quadrant_t\fP *incoming[])"
.br
.RI "Callback function prototype to replace one set of quadrants with another\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBp8est_lid_compare\fP (const \fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b)"
.br
.RI "Compare the p8est_lid_t \fIa\fP and the p8est_lid_t \fIb\fP\&. "
.ti -1c
.RI "int \fBp8est_lid_is_equal\fP (const \fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b)"
.br
.RI "Checks if the p8est_lid_t \fIa\fP and the p8est_lid_t \fIb\fP are equal\&. "
.ti -1c
.RI "void \fBp8est_lid_init\fP (\fBp8est_lid_t\fP *input, uint64_t high, uint64_t low)"
.br
.RI "Initializes a linear index to a given value\&. "
.ti -1c
.RI "void \fBp8est_lid_set_zero\fP (\fBp8est_lid_t\fP *input)"
.br
.RI "Initializes a linear index to zero\&. "
.ti -1c
.RI "void \fBp8est_lid_set_one\fP (\fBp8est_lid_t\fP *input)"
.br
.RI "Initializes a linear index to one\&. "
.ti -1c
.RI "void \fBp8est_lid_set_uint64\fP (\fBp8est_lid_t\fP *input, uint64_t u)"
.br
.RI "Initializes a linear index to an unsigned 64 bit integer\&. "
.ti -1c
.RI "int \fBp8est_lid_chk_bit\fP (const \fBp8est_lid_t\fP *input, int bit_number)"
.br
.RI "Returns the bit_number-th bit of \fIinput\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_set_bit\fP (\fBp8est_lid_t\fP *input, int bit_number)"
.br
.RI "Sets the exponent-th bit of \fIinput\fP to one\&. "
.ti -1c
.RI "void \fBp8est_lid_copy\fP (const \fBp8est_lid_t\fP *input, \fBp8est_lid_t\fP *output)"
.br
.RI "Copies an initialized p8est_lid_t to a p8est_lid_t\&. "
.ti -1c
.RI "void \fBp8est_lid_add\fP (const \fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b, \fBp8est_lid_t\fP *result)"
.br
.RI "Adds the uint128_t \fIb\fP to the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_sub\fP (const \fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b, \fBp8est_lid_t\fP *result)"
.br
.RI "Subtracts the p8est_lid_t \fIb\fP from the p8est_lid_t \fIa\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_bitwise_neg\fP (const \fBp8est_lid_t\fP *a, \fBp8est_lid_t\fP *result)"
.br
.RI "Calculates the bitwise negation of the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_bitwise_or\fP (const \fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b, \fBp8est_lid_t\fP *result)"
.br
.RI "Calculates the bitwise or of the uint128_t \fIa\fP and \fIb\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_bitwise_and\fP (const \fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b, \fBp8est_lid_t\fP *result)"
.br
.RI "Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_shift_right\fP (const \fBp8est_lid_t\fP *input, unsigned shift_count, \fBp8est_lid_t\fP *result)"
.br
.RI "Calculates the bit right shift of uint128_t \fIinput\fP by shift_count bits\&. "
.ti -1c
.RI "void \fBp8est_lid_shift_left\fP (const \fBp8est_lid_t\fP *input, unsigned shift_count, \fBp8est_lid_t\fP *result)"
.br
.RI "Calculates the bit left shift of uint128_t \fIinput\fP by shift_count bits\&. "
.ti -1c
.RI "void \fBp8est_lid_add_inplace\fP (\fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b)"
.br
.RI "Adds the p8est_lid_t \fIb\fP to the p8est_lid_t \fIa\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_sub_inplace\fP (\fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b)"
.br
.RI "Subtracts the uint128_t \fIb\fP from the uint128_t \fIa\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_bitwise_or_inplace\fP (\fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b)"
.br
.RI "Calculates the bitwise or of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. "
.ti -1c
.RI "void \fBp8est_lid_bitwise_and_inplace\fP (\fBp8est_lid_t\fP *a, const \fBp8est_lid_t\fP *b)"
.br
.RI "Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. "
.ti -1c
.RI "void \fBp8est_quadrant_linear_id_ext128\fP (const \fBp8est_quadrant_t\fP *quadrant, int level, \fBp8est_lid_t\fP *id)"
.br
.RI "Computes the linear position as p8est_lid_t of a quadrant in a uniform grid\&. "
.ti -1c
.RI "void \fBp8est_quadrant_set_morton_ext128\fP (\fBp8est_quadrant_t\fP *quadrant, int level, const \fBp8est_lid_t\fP *id)"
.br
.RI "Set quadrant Morton indices based on linear position given as p8est_lid_t in uniform grid\&. "
.ti -1c
.RI "\fBp8est_t\fP * \fBp8est_new_ext\fP (sc_MPI_Comm mpicomm, \fBp8est_connectivity_t\fP *connectivity, \fBp4est_locidx_t\fP min_quadrants, int min_level, int fill_uniform, size_t data_size, \fBp8est_init_t\fP init_fn, void *user_pointer)"
.br
.RI "Create a new forest\&. "
.ti -1c
.RI "\fBp8est_mesh_t\fP * \fBp8est_mesh_new_ext\fP (\fBp8est_t\fP *\fBp8est\fP, \fBp8est_ghost_t\fP *ghost, int compute_tree_index, int compute_level_lists, \fBp8est_connect_type_t\fP btype)"
.br
.RI "Create a new mesh\&. "
.ti -1c
.RI "\fBp8est_t\fP * \fBp8est_copy_ext\fP (\fBp8est_t\fP *input, int copy_data, int duplicate_mpicomm)"
.br
.RI "Make a deep copy of a \fBp8est\fP\&. "
.ti -1c
.RI "void \fBp8est_refine_ext\fP (\fBp8est_t\fP *\fBp8est\fP, int refine_recursive, int maxlevel, \fBp8est_refine_t\fP refine_fn, \fBp8est_init_t\fP init_fn, \fBp8est_replace_t\fP replace_fn)"
.br
.RI "Refine a forest with a bounded refinement level and a replace option\&. "
.ti -1c
.RI "void \fBp8est_coarsen_ext\fP (\fBp8est_t\fP *\fBp8est\fP, int coarsen_recursive, int callback_orphans, \fBp8est_coarsen_t\fP coarsen_fn, \fBp8est_init_t\fP init_fn, \fBp8est_replace_t\fP replace_fn)"
.br
.RI "Coarsen a forest\&. "
.ti -1c
.RI "void \fBp8est_balance_ext\fP (\fBp8est_t\fP *\fBp8est\fP, \fBp8est_connect_type_t\fP btype, \fBp8est_init_t\fP init_fn, \fBp8est_replace_t\fP replace_fn)"
.br
.RI "2:1 balance the size differences of neighboring elements in a forest\&. "
.ti -1c
.RI "void \fBp8est_balance_subtree_ext\fP (\fBp8est_t\fP *\fBp8est\fP, \fBp8est_connect_type_t\fP btype, \fBp4est_topidx_t\fP which_tree, \fBp8est_init_t\fP init_fn, \fBp8est_replace_t\fP replace_fn)"
.br
.ti -1c
.RI "\fBp4est_gloidx_t\fP \fBp8est_partition_ext\fP (\fBp8est_t\fP *\fBp8est\fP, int partition_for_coarsening, \fBp8est_weight_t\fP weight_fn)"
.br
.RI "Repartition the forest\&. "
.ti -1c
.RI "\fBp4est_gloidx_t\fP \fBp8est_partition_for_coarsening\fP (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_locidx_t\fP *num_quadrants_in_proc)"
.br
.RI "Correct partition to allow one level of coarsening\&. "
.ti -1c
.RI "void \fBp8est_iterate_ext\fP (\fBp8est_t\fP *\fBp8est\fP, \fBp8est_ghost_t\fP *ghost_layer, void *user_data, \fBp8est_iter_volume_t\fP iter_volume, \fBp8est_iter_face_t\fP iter_face, \fBp8est_iter_edge_t\fP iter_edge, \fBp8est_iter_corner_t\fP iter_corner, int remote)"
.br
.RI "p8est_iterate_ext adds the option \fIremote:\fP if this is false, then it is the same as p8est_iterate; if this is true, then corner/edge callbacks are also called on corners/edges for hanging faces/edges touched by local quadrants\&. "
.ti -1c
.RI "void \fBp8est_save_ext\fP (const char *filename, \fBp8est_t\fP *\fBp8est\fP, int save_data, int save_partition)"
.br
.RI "Save the complete connectivity/p8est data to disk\&. "
.ti -1c
.RI "\fBp8est_t\fP * \fBp8est_load_ext\fP (const char *filename, sc_MPI_Comm mpicomm, size_t data_size, int load_data, int autopartition, int broadcasthead, void *user_pointer, \fBp8est_connectivity_t\fP **connectivity)"
.br
.RI "Load the complete connectivity/p4est structure from disk\&. "
.ti -1c
.RI "\fBp8est_t\fP * \fBp8est_source_ext\fP (sc_io_source_t *src, sc_MPI_Comm mpicomm, size_t data_size, int load_data, int autopartition, int broadcasthead, void *user_pointer, \fBp8est_connectivity_t\fP **connectivity)"
.br
.RI "The same as p8est_load_ext, but reading the connectivity/p8est from an open sc_io_source_t stream\&. "
.ti -1c
.RI "void \fBp8est_get_plex_data_ext\fP (\fBp8est_t\fP *\fBp8est\fP, \fBp8est_ghost_t\fP **ghost, \fBp8est_lnodes_t\fP **lnodes, \fBp8est_connect_type_t\fP ctype, int overlap, \fBp4est_locidx_t\fP *first_local_quad, sc_array_t *out_points_per_dim, sc_array_t *out_cone_sizes, sc_array_t *out_cones, sc_array_t *out_cone_orientations, sc_array_t *out_vertex_coords, sc_array_t *out_children, sc_array_t *out_parents, sc_array_t *out_childids, sc_array_t *out_leaves, sc_array_t *out_remotes, int custom_numbering)"
.br
.RI "Create the data necessary to create a PETsc DMPLEX representation of a forest, as well as the accompanying lnodes and ghost layer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface routines with extended capabilities\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef sc_uint128_t \fBp8est_lid_t\fP"

.PP
A datatype to handle the linear id in 3D\&. We use the implementation of unsigned 128 bit integer in libsc, i\&.e\&., a struct with the members high_bits and low_bits (both uint64_t)\&. 
.SS "typedef void(* p8est_replace_t) (\fBp8est_t\fP *\fBp8est\fP, \fBp4est_topidx_t\fP which_tree, int num_outgoing, \fBp8est_quadrant_t\fP *outgoing[], int num_incoming, \fBp8est_quadrant_t\fP *incoming[])"

.PP
Callback function prototype to replace one set of quadrants with another\&. This is used by extended routines when the quadrants of an existing, valid \fBp8est\fP are changed\&. The callback allows the user to make changes to newly initialized quadrants before the quadrants that they replace are destroyed\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP A valid forest for context\&. 
.br
\fIwhich_tree\fP Tree index of the invocation\&. 
.br
\fInum_outgoing\fP The number of outgoing quadrants\&. 
.br
\fIoutgoing\fP The outgoing quadrants: after the callback, the user_data, if \fIp8est->data_size\fP is nonzero, will be destroyed\&. 
.br
\fInum_incoming\fP The number of incoming quadrants\&. 
.br
\fIincoming\fP The incoming quadrants: prior to the callback, the user_data, if \fIp8est->data_size\fP is nonzero, is allocated, and the p8est_init_t callback, if it has been provided, will be called\&.
.RE
.PP
If the mesh is being refined, num_outgoing will be 1 and num_incoming will be 8, and vice versa if the mesh is being coarsened\&. 
.SH "Function Documentation"
.PP 
.SS "void p8est_balance_ext (\fBp8est_t\fP * p8est, \fBp8est_connect_type_t\fP btype, \fBp8est_init_t\fP init_fn, \fBp8est_replace_t\fP replace_fn)"

.PP
2:1 balance the size differences of neighboring elements in a forest\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The \fBp8est\fP to be worked on\&. 
.br
\fIbtype\fP Balance type (face, edge, or corner/full)\&. Corner balance is almost never required when discretizing a PDE; just causes smoother mesh grading\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.br
\fIreplace_fn\fP Callback function that allows the user to change incoming quadrants based on the quadrants they replace\&. 
.RE
.PP

.SS "void p8est_coarsen_ext (\fBp8est_t\fP * p8est, int coarsen_recursive, int callback_orphans, \fBp8est_coarsen_t\fP coarsen_fn, \fBp8est_init_t\fP init_fn, \fBp8est_replace_t\fP replace_fn)"

.PP
Coarsen a forest\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The forest is changed in place\&. 
.br
\fIcoarsen_recursive\fP Boolean to decide on recursive coarsening\&. 
.br
\fIcallback_orphans\fP Boolean to enable calling coarsen_fn even on non-families\&. In this case, the second quadrant pointer in the argument list of the callback is NULL, subsequent pointers are undefined, and the return value is ignored\&. If coarsen_recursive is true, it is possible that a quadrant is called once or more as an orphan and eventually becomes part of a family\&. With coarsen_recursive false and callback_orphans true, it is guaranteed that every quadrant is passed exactly once into the coarsen_fn callback\&. 
.br
\fIcoarsen_fn\fP Callback function that returns true if a family of quadrants shall be coarsened\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is already allocated automatically\&. 
.br
\fIreplace_fn\fP Callback function that allows the user to change incoming quadrants based on the quadrants they replace\&. 
.RE
.PP

.SS "\fBp8est_t\fP* p8est_copy_ext (\fBp8est_t\fP * input, int copy_data, int duplicate_mpicomm)"

.PP
Make a deep copy of a \fBp8est\fP\&. The connectivity is not duplicated\&. Copying of quadrant user data is optional\&. If old and new data sizes are 0, the user_data field is copied regardless\&. The inspect member of the copy is set to NULL\&. The revision counter of the copy is set to zero\&.
.PP
\fBParameters\fP
.RS 4
\fIinput\fP Valid forest to return a copy of\&. 
.br
\fIcopy_data\fP If true, data are copied\&. If false, data_size is set to 0\&. 
.br
\fIduplicate_mpicomm\fP If true, MPI communicator is copied\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a valid \fBp8est\fP that does not depend on the input, except for borrowing the same connectivity\&. Its revision counter is 0\&. 
.RE
.PP

.SS "void p8est_get_plex_data_ext (\fBp8est_t\fP * p8est, \fBp8est_ghost_t\fP ** ghost, \fBp8est_lnodes_t\fP ** lnodes, \fBp8est_connect_type_t\fP ctype, int overlap, \fBp4est_locidx_t\fP * first_local_quad, sc_array_t * out_points_per_dim, sc_array_t * out_cone_sizes, sc_array_t * out_cones, sc_array_t * out_cone_orientations, sc_array_t * out_vertex_coords, sc_array_t * out_children, sc_array_t * out_parents, sc_array_t * out_childids, sc_array_t * out_leaves, sc_array_t * out_remotes, int custom_numbering)"

.PP
Create the data necessary to create a PETsc DMPLEX representation of a forest, as well as the accompanying lnodes and ghost layer\&. The forest must be at least face balanced (see \fBp4est_balance()\fP)\&. See test/test_plex2\&.c for example usage\&.
.PP
All arrays should be initialized to hold sizeof (p4est_locidx_t), except for \fIout_remotes\fP, which should be initialized to hold (2 * sizeof (p4est_locidx_t))\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP the forest 
.br
\fIghost\fP the ghost layer 
.br
\fIlnodes\fP the lnodes 
.br
\fIctype\fP the type of adjacency for the overlap 
.br
\fIoverlap\fP the number of layers of overlap (zero is acceptable) 
.br
\fIfirst_local_quad\fP the local quadrants are assigned contiguous plex indices, starting with this index 
.br
\fIout_points_per_dim\fP filled with argument for DMPlexCreateFromDAG() 
.br
\fIout_cone_sizes\fP filled with argument for DMPlexCreateFromDAG() 
.br
\fIout_cones\fP filled with argument for DMPlexCreateFromDAG() 
.br
\fIout_cone_orientations\fP filled with argument for DMPlexCreateFromDAG() 
.br
\fIout_vertex_coords\fP filled with argument for DMPlexCreateFromDAG() 
.br
\fIout_children\fP filled with argument for DMPlexSetTree() 
.br
\fIout_parents\fP filled with argument for DMPlexSetTree() 
.br
\fIout_childids\fP filled with argument for DMPlexSetTree() 
.br
\fIout_leaves\fP filled with argument for PetscSFSetGraph() 
.br
\fIout_remotes\fP filled with argument for PetscSFSetGraph() 
.br
\fIcustom_numbering\fP Whether or use the default numbering (0) of DMPlex child ids or the custom (1)\&. 
.RE
.PP

.SS "void p8est_lid_add (const \fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b, \fBp8est_lid_t\fP * result)"

.PP
Adds the uint128_t \fIb\fP to the uint128_t \fIa\fP\&. \fIresult\fP == \fIa\fP or \fIresult\fP == \fIb\fP is not allowed\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.br
\fIresult\fP A pointer to a p8est_lid_t\&. The sum \fIa\fP + \fIb\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void p8est_lid_add_inplace (\fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b)"

.PP
Adds the p8est_lid_t \fIb\fP to the p8est_lid_t \fIa\fP\&. The result is saved in \fIa\fP\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. \fIa\fP will be overwritten by \fIa\fP + \fIb\fP\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.RE
.PP

.SS "void p8est_lid_bitwise_and (const \fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b, \fBp8est_lid_t\fP * result)"

.PP
Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. \fIa\fP == \fIresult\fP is allowed\&. Furthermore, \fIa\fP == \fIresult\fP and/or \fIb\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.br
\fIresult\fP A pointer to a p8est_lid_t\&. The bitwise and of \fIa\fP and \fIb\fP will be saved\&. in \fIresult\fP\&. 
.RE
.PP

.SS "void p8est_lid_bitwise_and_inplace (\fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b)"

.PP
Calculates the bitwise and of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. The bitwise and will be saved in \fIa\fP\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.RE
.PP

.SS "void p8est_lid_bitwise_neg (const \fBp8est_lid_t\fP * a, \fBp8est_lid_t\fP * result)"

.PP
Calculates the bitwise negation of the uint128_t \fIa\fP\&. \fIa\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. 
.br
\fIresult\fP A pointer to a p8est_lid_t\&. The bitwise negation of \fIa\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void p8est_lid_bitwise_or (const \fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b, \fBp8est_lid_t\fP * result)"

.PP
Calculates the bitwise or of the uint128_t \fIa\fP and \fIb\fP\&. \fIa\fP == \fIresult\fP is allowed\&. Furthermore, \fIa\fP == \fIresult\fP and/or \fIb\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.br
\fIresult\fP A pointer to a p8est_lid_t\&. The bitwise or of \fIa\fP and \fIb\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void p8est_lid_bitwise_or_inplace (\fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b)"

.PP
Calculates the bitwise or of the uint128_t \fIa\fP and the uint128_t \fIb\fP\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. The bitwise or will be saved in \fIa\fP\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.RE
.PP

.SS "int p8est_lid_chk_bit (const \fBp8est_lid_t\fP * input, int bit_number)"

.PP
Returns the bit_number-th bit of \fIinput\fP\&. This function checks a bit of an existing, initialized value\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a p8est_lid_t\&. 
.br
\fIbit_number\fP The bit (counted from the right hand side) that is checked by logical and\&. Require 0 <= \fIbit_number\fP < 128\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if bit is set, false if not\&. 
.RE
.PP

.SS "int p8est_lid_compare (const \fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b)"

.PP
Compare the p8est_lid_t \fIa\fP and the p8est_lid_t \fIb\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns -1 if a < b, 1 if a > b and 0 if a == b\&. 
.RE
.PP

.SS "void p8est_lid_copy (const \fBp8est_lid_t\fP * input, \fBp8est_lid_t\fP * output)"

.PP
Copies an initialized p8est_lid_t to a p8est_lid_t\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to the sc_uint128 that is copied\&. 
.br
\fIoutput\fP A pointer to a p8est_lid_t\&. The high and low bits of \fIoutput\fP will be set to the high and low bits of \fIinput\fP, respectively\&. 
.RE
.PP

.SS "void p8est_lid_init (\fBp8est_lid_t\fP * input, uint64_t high, uint64_t low)"

.PP
Initializes a linear index to a given value\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to the p8est_lid_t that will be initialized\&. 
.br
\fIhigh\fP The given high bits to initialize \fIa\fP\&. 
.br
\fIlow\fP The given low bits to initialize \fIa\fP\&. 
.RE
.PP

.SS "int p8est_lid_is_equal (const \fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b)"

.PP
Checks if the p8est_lid_t \fIa\fP and the p8est_lid_t \fIb\fP are equal\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a true value if \fIa\fP and \fIb\fP are equal, false otherwise 
.RE
.PP

.SS "void p8est_lid_set_bit (\fBp8est_lid_t\fP * input, int bit_number)"

.PP
Sets the exponent-th bit of \fIinput\fP to one\&. This function modifies an existing, initialized value\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a p8est_lid_t\&. 
.br
\fIbit_number\fP The bit (counted from the right hand side) that is set to one by logical or\&. Require 0 <= \fIbit_number\fP < 128\&. 
.RE
.PP

.SS "void p8est_lid_set_one (\fBp8est_lid_t\fP * input)"

.PP
Initializes a linear index to one\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a p4est_lid_t that will be initialized\&. 
.RE
.PP

.SS "void p8est_lid_set_uint64 (\fBp8est_lid_t\fP * input, uint64_t u)"

.PP
Initializes a linear index to an unsigned 64 bit integer\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a p4est_lid_t that will be initialized\&. 
.RE
.PP

.SS "void p8est_lid_set_zero (\fBp8est_lid_t\fP * input)"

.PP
Initializes a linear index to zero\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a p4est_lid_t that will be initialized\&. 
.RE
.PP

.SS "void p8est_lid_shift_left (const \fBp8est_lid_t\fP * input, unsigned shift_count, \fBp8est_lid_t\fP * result)"

.PP
Calculates the bit left shift of uint128_t \fIinput\fP by shift_count bits\&. We shift in zeros from the right\&. If \fIshift_count\fP >= 128, \fIresult\fP is 0\&. All bits left from the 127th bit (counted zero based from the right hand side) drop out\&. \fIinput\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a p8est_lid_t\&. 
.br
\fIshift_count\fP Bits to shift\&. \fIshift_count\fP >= 0\&. 
.br
\fIresult\fP A pointer to a p8est_lid_t\&. The left shifted number will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void p8est_lid_shift_right (const \fBp8est_lid_t\fP * input, unsigned shift_count, \fBp8est_lid_t\fP * result)"

.PP
Calculates the bit right shift of uint128_t \fIinput\fP by shift_count bits\&. We shift in zeros from the left\&. If \fIshift_count\fP >= 128, \fIresult\fP is 0\&. All bits right from the zeroth bit (counted from the right hand side) drop out\&. \fIinput\fP == \fIresult\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP A pointer to a p8est_lid_t\&. 
.br
\fIshift_count\fP Bits to shift\&. \fIshift_count\fP >= 0\&. 
.br
\fIresult\fP A pointer to a p8est_lid_t\&. The right shifted number will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void p8est_lid_sub (const \fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b, \fBp8est_lid_t\fP * result)"

.PP
Subtracts the p8est_lid_t \fIb\fP from the p8est_lid_t \fIa\fP\&. This function assumes that the result is >= 0\&. \fIresult\fP == \fIa\fP or \fIresult\fP == \fIb\fP is not allowed\&. \fIa\fP == \fIb\fP is allowed\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.br
\fIresult\fP A pointer to a p8est_lid_t\&. The difference \fIa\fP - \fIb\fP will be saved in \fIresult\fP\&. 
.RE
.PP

.SS "void p8est_lid_sub_inplace (\fBp8est_lid_t\fP * a, const \fBp8est_lid_t\fP * b)"

.PP
Subtracts the uint128_t \fIb\fP from the uint128_t \fIa\fP\&. The result is saved in \fIa\fP\&. \fIa\fP == \fIb\fP is allowed\&. This function assumes that the result is >= 0\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP A pointer to a p8est_lid_t\&. \fIa\fP will be overwritten by \fIa\fP - \fIb\fP\&. 
.br
\fIb\fP A pointer to a p8est_lid_t\&. 
.RE
.PP

.SS "\fBp8est_t\fP* p8est_load_ext (const char * filename, sc_MPI_Comm mpicomm, size_t data_size, int load_data, int autopartition, int broadcasthead, void * user_pointer, \fBp8est_connectivity_t\fP ** connectivity)"

.PP
Load the complete connectivity/p4est structure from disk\&. It is possible to load the file with a different number of processors than has been used to write it\&. The partition will then be uniform\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file to read\&. 
.br
\fImpicomm\fP A valid MPI communicator\&. 
.br
\fIdata_size\fP Size of data for each quadrant which can be zero\&. Then user_data_pool is set to NULL\&. If data_size is zero, load_data is ignored\&. 
.br
\fIload_data\fP If true, the element data is loaded\&. This is only permitted if the saved data size matches\&. If false, the stored data size is ignored\&. 
.br
\fIautopartition\fP Ignore saved partition and make it uniform\&. 
.br
\fIbroadcasthead\fP Have only rank 0 read headers and bcast them\&. 
.br
\fIuser_pointer\fP Assign to the user_pointer member of the \fBp4est\fP before init_fn is called the first time\&. 
.br
\fIconnectivity\fP Connectivity must be destroyed separately\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a valid forest structure\&. A pointer to a valid connectivity structure is returned through the last argument\&. 
.RE
.PP
\fBNote\fP
.RS 4
Aborts on file errors or invalid file contents\&. 
.RE
.PP

.SS "\fBp8est_mesh_t\fP* p8est_mesh_new_ext (\fBp8est_t\fP * p8est, \fBp8est_ghost_t\fP * ghost, int compute_tree_index, int compute_level_lists, \fBp8est_connect_type_t\fP btype)"

.PP
Create a new mesh\&. This function sets a subset of the mesh creation parameters\&. For full control use \fBp8est_mesh_new_params\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP A forest that is fully 2:1 balanced\&. 
.br
\fIghost\fP The ghost layer created from the provided \fBp4est\fP\&. 
.br
\fIcompute_tree_index\fP Boolean to decide whether to allocate and compute the quad_to_tree list\&. 
.br
\fIcompute_level_lists\fP Boolean to decide whether to compute the level lists in quad_level\&. 
.br
\fIbtype\fP Flag indicating the connection types (face, edge, corner) stored in the mesh\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A fully allocated mesh structure\&. 
.RE
.PP

.SS "\fBp8est_t\fP* p8est_new_ext (sc_MPI_Comm mpicomm, \fBp8est_connectivity_t\fP * connectivity, \fBp4est_locidx_t\fP min_quadrants, int min_level, int fill_uniform, size_t data_size, \fBp8est_init_t\fP init_fn, void * user_pointer)"

.PP
Create a new forest\&. This is a more general form of \fBp8est_new\fP\&. The forest created is either uniformly refined at a given level or created with the coarsest possible refinement that fits the exact partition that would have been created in the uniform mode\&. The latter, coarse refinement depends on the number of MPI processes! The initial level is currently limited to \fBP8EST_OLD_QMAXLEVEL\fP\&. Regardless, \fBp8est_refine\fP can go as deep as \fBP8EST_QMAXLEVEL\fP\&.
.PP
\fBParameters\fP
.RS 4
\fImpicomm\fP A valid MPI communicator\&. 
.br
\fIconnectivity\fP This is the connectivity information that the forest is built with\&. Note the forest does not take ownership of the memory\&. 
.br
\fImin_quadrants\fP Minimum initial quadrants per processor\&. Makes the refinement pattern mpisize-specific\&. For maximum reproducibility, set this to 0\&. 
.br
\fImin_level\fP The forest is refined at most to this level\&. Later coarsening and refinement is unaffected\&. May be negative or 0, then it has no effect\&. 
.br
\fIfill_uniform\fP If true, fill the forest with a uniform mesh instead of the coarsest possible one\&. The latter is partition-specific, which is not a good idea wrt\&. reproducibility\&. 
.br
\fIdata_size\fP The size of data for each quadrant\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data which is internally allocated using data_size\&. 
.br
\fIuser_pointer\fP Assigned to the user_pointer member of the forest before init_fn is called the first time\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Valid \fBp8est\fP object\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBsimple/simple3\&.c\fP\&.
.SS "\fBp4est_gloidx_t\fP p8est_partition_ext (\fBp8est_t\fP * p8est, int partition_for_coarsening, \fBp8est_weight_t\fP weight_fn)"

.PP
Repartition the forest\&. The forest is partitioned between processors such that each processor has an approximately equal number of quadrants (or weight)\&.
.PP
The user data of a \fBp8est_quadrant\fP is transferred along within this function\&.
.PP
The only extension of this function over \fBp8est_partition\fP is the return value\&.
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The forest that will be partitioned\&. 
.br
\fIpartition_for_coarsening\fP If true, the partition is modified to allow one level of coarsening\&. 
.br
\fIweight_fn\fP A weighting function or NULL for uniform partitioning\&. A weighting function with constant weight 1 on each quadrant is equivalent to weight_fn == NULL but other constant weightings may result in different uniform partitionings\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The global number of shipped quadrants 
.RE
.PP

.SS "\fBp4est_gloidx_t\fP p8est_partition_for_coarsening (\fBp8est_t\fP * p8est, \fBp4est_locidx_t\fP * num_quadrants_in_proc)"

.PP
Correct partition to allow one level of coarsening\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP forest whose partition is corrected 
.br
\fInum_quadrants_in_proc\fP partition that will be corrected 
.RE
.PP
\fBReturns\fP
.RS 4
absolute number of moved quadrants 
.RE
.PP

.SS "void p8est_quadrant_linear_id_ext128 (const \fBp8est_quadrant_t\fP * quadrant, int level, \fBp8est_lid_t\fP * id)"

.PP
Computes the linear position as p8est_lid_t of a quadrant in a uniform grid\&. The grid and quadrant levels need not coincide\&. If they do, this is the inverse of \fBp4est_quadrant_set_morton\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIquadrant\fP Quadrant whose linear index will be computed\&. If the quadrant is smaller than the grid (has a higher quadrant->level), the result is computed from its ancestor at the grid's level\&. If the quadrant has a smaller level than the grid (it is bigger than a grid cell), the grid cell sharing its lower left corner is used as reference\&. 
.br
\fIlevel\fP The level of the regular grid compared to which the linear position is to be computed\&. 
.br
\fIid\fP A pointer to an allocated or static p8est_lid_t\&. id will be the linear position of this quadrant on a uniform grid\&. 
.RE
.PP
\fBNote\fP
.RS 4
The user_data of \fIquadrant\fP is never modified\&. 
.RE
.PP

.SS "void p8est_quadrant_set_morton_ext128 (\fBp8est_quadrant_t\fP * quadrant, int level, const \fBp8est_lid_t\fP * id)"

.PP
Set quadrant Morton indices based on linear position given as p8est_lid_t in uniform grid\&. This is the inverse operation of \fBp4est_quadrant_linear_id\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIquadrant\fP Quadrant whose Morton indices will be set\&. 
.br
\fIlevel\fP Level of the grid and of the resulting quadrant\&. 
.br
\fIid\fP Linear index of the quadrant on a uniform grid\&. 
.RE
.PP
\fBNote\fP
.RS 4
The user_data of \fIquadrant\fP is never modified\&. 
.RE
.PP

.SS "void p8est_refine_ext (\fBp8est_t\fP * p8est, int refine_recursive, int maxlevel, \fBp8est_refine_t\fP refine_fn, \fBp8est_init_t\fP init_fn, \fBp8est_replace_t\fP replace_fn)"

.PP
Refine a forest with a bounded refinement level and a replace option\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBp8est\fP\fP The forest is changed in place\&. 
.br
\fIrefine_recursive\fP Boolean to decide on recursive refinement\&. 
.br
\fImaxlevel\fP Maximum allowed refinement level (inclusive)\&. If this is negative the level is restricted only by the compile-time constant QMAXLEVEL in \fBp8est\&.h\fP\&. 
.br
\fIrefine_fn\fP Callback function that must return true if a quadrant shall be refined\&. If refine_recursive is true, refine_fn is called for every existing and newly created quadrant\&. Otherwise, it is called for every existing quadrant\&. It is possible that a refinement request made by the callback is ignored\&. To catch this case, you can examine whether init_fn or replace_fn gets called\&. 
.br
\fIinit_fn\fP Callback function to initialize the user_data for newly created quadrants, which is guaranteed to be allocated\&. This function pointer may be NULL\&. 
.br
\fIreplace_fn\fP Callback function that allows the user to change incoming quadrants based on the quadrants they replace; may be NULL\&. 
.RE
.PP

.SS "void p8est_save_ext (const char * filename, \fBp8est_t\fP * p8est, int save_data, int save_partition)"

.PP
Save the complete connectivity/p8est data to disk\&. This is a collective operation that all MPI processes need to call\&. All processes write into the same file, so the filename given needs to be identical over all parallel invocations\&. See p8est_load_ext for information on the autopartition parameter\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file to write\&. 
.br
\fI\fBp8est\fP\fP Valid forest structure\&. 
.br
\fIsave_data\fP If true, the element data is saved\&. Otherwise, a data size of 0 is saved\&. 
.br
\fIsave_partition\fP If false, save file as if 1 core was used\&. If true, save core count and partition\&. Advantage: Partition can be recovered on loading with same mpisize and autopartition false\&. Disadvantage: Makes the file depend on mpisize\&. Either way the file can be loaded with autopartition true\&. 
.RE
.PP
\fBNote\fP
.RS 4
Aborts on file errors\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for p4est from the source code\&.
