# This file is part of p4est.
# Makefile.am in blockforest (at the repository root)
# included non-recursively from toplevel directory

if P4EST_ENABLE_BUILD_3D
bin_PROGRAMS += blockforest/p8est_blockforest
blockforest_p8est_blockforest_SOURCES = \
  blockforest/blockforest3.c blockforest/blockforest_run.c \
  blockforest/blockforest_global.h \
  blockforest/blockforest_config.ini
endif
