
# This file is part of p4est.
# Makefile.am in example/blockforest
# included non-recursively from toplevel directory

if P4EST_ENABLE_BUILD_3D
bin_PROGRAMS += example/blockforest/p8est_blockforest
example_blockforest_p8est_blockforest_SOURCES = \
  example/blockforest/blockforest3.c example/blockforest/blockforest_run.c \
  example/blockforest/blockforest_global.h \
  example/blockforest/blockforest_config.ini
endif
